<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Geoip
 */
?>
<?php
/**
 * @var \Amasty\Geoip\Block\Adminhtml\Settings\Import $block
 */
?>
<button id="am-import"
        class="action-default scalable" <?= $block->getImportFilesAvailable() ? '' : 'disabled="disabled"' ?>
        data-ui-id="widget-button-0" type="button" title="<?= $block->escapeHtml(__('Import')) ?>">
    <span><?= $block->escapeHtml(__('Import')) ?></span>
</button>
<br/>
<br/> var/amasty/geoip/GeoLite2-City-Blocks-IPv4.csv
<div class="<?= $block->getBlockFileExist() ? 'amgeoip-files-available' : 'amgeoip-files-unavailable' ?> "></div>
<br/> var/amasty/geoip/GeoLite2-City-Blocks-IPv6.csv
<div class="<?= $block->getBlockV6FileExist() ? 'amgeoip-files-available' : 'amgeoip-files-unavailable' ?> "></div>
<br/> var/amasty/geoip/GeoLite2-City-Locations-en.csv
<div class="<?= $block->getLocationFileExist() ? 'amgeoip-files-available' : 'amgeoip-files-unavailable' ?> "></div>
<br/>
<div class="progressbar">
    <div class="am_processer_container"><span class="begin"></span>

        <div class="am_line">
            <div class="am_processer" style="width: <?= (int)$block->getWidth() ?>%"><span>&nbsp</span></div>
        </div>
        <span class="<?= $block->escapeHtml($block->getImportedClass()) ?>"></span></div>
    <span class="import"><div class="bubble"><?= $block->escapeHtml(__('Import')) ?></div></span><span class="completed"><div
                class="bubble"><?= $block->escapeHtml(__("Completed")) ?></div></span>
</div>
<br/> <?= $block->escapeHtml($block->getImportDate()) ?>
<script type="text/javascript">
    require([
        'jquery',
        'Amasty_Geoip/js/import'
    ], function ($) {
        var imp = $('#am-import');

        imp.amGeoip({
            importItems: <?= /* @noEscape */ $block->getConfig(); ?>,
            type: 'import'
        });

    });

</script>

