<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Promo
 */
?>
<?php /** @var \Amasty\Promo\Block\Notification $block */?>
<?php if ($block->isEnabled()) :?>
    <?php if ($block->getNewItemsCount() > 0) :?>
        <?php $_text = $block->getText();?>
        <?php if ($_text !== '') :?>
            <div class="message-notice notice message">
                <div><?= $_text;?></div>
            </div>
        <?php endif;?>
    <?php endif;?>
<?php endif;?>
