<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Checkout
 */
?>
<div class="fields-comment message">
    <?= $block->escapeHtml(__('Please use drag and drop to reorder the fields position and enable/disable the fields by moving them into the appropriate section')); ?>
</div>
<div class="fields-comment message">
    <?= $block->escapeHtml(__('When disabling City, Country, State/Province, Zip/Postal Code, please keep in mind that shopping cart will also be affected since those attributes are used in estimations and calculations.')); ?>
</div>
