<?php
/**
 *
 * SM Listing Tabs - Version 2.5.0
 * Copyright (c) 2017 YouTech Company. All Rights Reserved.
 * @license - Copyrighted Commercial Software
 * Author: YouTech Company
 * Websites: http://www.magentech.com
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
if ($this->_isAjax()) {
	$products = $this->_ajaxLoad();
	$config   = $this->_getConfig();
} else {
	$config   = $this->getData('config');
	$products = $this->getData('products');
}
$_helper         = $this->helper('Magento\Catalog\Helper\Output');
$viewMode        = 'grid';
$image           = 'category_page_grid';
$imageBig        = 'category_page_grid_big';
$showDescription = false;
$templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$type_loadmore   = $config['type_show'] == 'loadmore' ? true : false;
$cls_mark        = $type_loadmore ? ' ltabs-mark ' : '';

$_config   = $this->helper('Sm\Market\Helper\Data');
$lthelper  = $this->helper('Sm\ListingTabs\Helper\Data');
$homeStyle = $_config->getThemeLayout('home_style');

$nb_type_show = $config['type_show'];

$nb_rows = 7;
$i       = 0;
$count   = count($products);
/**
 * Position for actions regarding image size changing in vde if needed
 */
$pos = $block->getPositioned();
?>
<div class="<?php /* @escapeNotVerified */
echo $viewMode; ?> products-<?php /* @escapeNotVerified */
echo $viewMode; ?>">
        <?php $iterator = 1; ?>
    <div class="products list items product-items  <?php echo $type_loadmore == false ? ' owl-carousel ' : ''; ?>" <?php echo $type_loadmore ? 'data-liffect="fadeIn"' : ''; ?>>
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
		<?php foreach ($products as $_product):
			$i++;
			?>


			<?php if ($nb_type_show == 'slider' && ($i % $nb_rows == 1 || $nb_rows == 1)) { ?>
            <div class="item product product-item">
		<?php } ?>
			<?php if ($nb_type_show == 'loadmore'){ ?>
            <div class="item product product-item ltabs-mark">
		<?php } ?>


			<?php if ($i % 7 == 1){ ?>
            <div class="item-wrap">
            <div class="row">
            <div class="col-lg-5 item-first">
							<?php
							$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
							$product       = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
							$images        = $product->getMediaGalleryImages();
							$productInfo   = "product_" . rand() . time();;
							?>
                <div class="item <?php echo $productInfo; ?>">
								<div class="item-inner">
									<!--Featured Item-->
									<?php
									$productImage = $block->getImage($_product, $imageBig);
									if ($pos != null) {
										$position = ' style="left:' . $productImage->getWidth() . 'px;'
											. 'top:' . $productImage->getHeight() . 'px;"';
									}
									?>
									<?php
									if ((int)$config['display_countdown'] && !empty($_product->getSpecialPrice()) && !empty($_product->getSpecialToDate())) {
										$specialToDate = $_product->getSpecialToDate();
										?>
                                        <div class="deals-countdown" data-timer="<?php echo date("Y/m/d H:i:s", strtotime($specialToDate)); ?>">
										<div class="deals-time time-day"><div class="num-time"></div><div class="title-time"></div></div>
										<div class="deals-time time-hours"><div class="num-time"></div><div class="title-time"></div></div>
										<div class="deals-time time-mins"><div class="num-time"></div><div class="title-time"></div></div>
										<div class="deals-time time-secs"><div class="num-time"></div><div class="title-time"></div></div>
									</div>
									<?php } ?>
									<?php // Product Image ?>
                                    <div class="box-image">
										<a href="<?php /* @escapeNotVerified */
										echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
											<?php echo $productImage->toHtml(); ?>
										</a>

                                        <!--LABEL PRODUCT-->

										<?php
										$specialprice         = $_product->getSpecialPrice();
										$specialPriceFromDate = $_product->getSpecialFromDate();
										$specialPriceToDate   = $_product->getSpecialToDate();

										$today = time();

										if ($specialprice && $_config->getAdvanced('show_salelabel')) {
											if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
                                                <div class="label-product label-sale">
															<span class="sale-product-icon">
																<?php echo __('Sale'); ?>
															</span>
														</div>
											<?php }
										}
										?>

										<?php
										$now      = date("Y-m-d");
										$newsFrom = substr($_product->getNewsFromDate(), 0, 10);
										$newsTo   = substr($_product->getNewsToDate(), 0, 10);


										if (($newsTo != '' || $newsFrom != '') && $_config->getAdvanced('show_newlabel')) {
											if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) { ?>
                                                <div class="label-product label-new">
															<span class="new-product-icon"><?php echo __('New'); ?></span>
														</div>
											<?php }
										} ?>


                                        <!--END LABEL PRODUCT-->

										<?php if ($homeStyle == 'home-16' || $homeStyle == 'home-17' || $homeStyle == 'home-18') { ?>
                                            <div class="button-action">
												<?php if ($_config->getAdvanced('show_wishlist_button')) { ?>
													<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                        <a href="#" class="action towishlist btn-action link-wishlist" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */
														echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button">
															<span><?php /* @escapeNotVerified */
																echo __('Add to Wish List') ?></span>
														</a>
													<?php endif; ?>
												<?php } ?>

												<?php if ($_config->getAdvanced('show_compare_button')) { ?>
													<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                    <a href="#" class="action tocompare btn-action link-compare" title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" data-post='<?php /* @escapeNotVerified */
													echo $compareHelper->getPostDataParams($_product); ?>' role="button">
														<span><?php /* @escapeNotVerified */
															echo __('Add to Compare') ?></span>
													</a>
												<?php } ?>
											</div>
										<?php } ?>
									</div>
									
									<div class="product details product-item-details box-info">
										<?php
										$_productNameStripped = $block->stripTags($_product->getName(), null, true);
										?>
                                        <h2 class="product name product-item-name product-name">
											<a class="product-item-link"
                                               href="<?php /* @escapeNotVerified */
											   echo $_product->getProductUrl() ?>">
												<?php /* @escapeNotVerified */
												echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
											</a>
										</h2>
										<?php echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>
										<?php /* @escapeNotVerified */
										echo $block->getProductPrice($_product) ?>
										<?php echo $block->getProductDetailsHtml($_product); ?>

										<?php if ($homeStyle == 'home-16' || $homeStyle == 'home-17' || $homeStyle == 'home-18') { ?>
                                            <div class="bottom-action">
												<?php if ($_config->getAdvanced('show_addtocart_button')) { ?>
													<?php if ($_product->isSaleable()): ?>
														<?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
														echo $postParams['action']; ?>" method="post">
															<input type="hidden" name="product" value="<?php /* @escapeNotVerified */
															echo $postParams['data']['product']; ?>">
															<input type="hidden" name="<?php /* @escapeNotVerified */
															echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */
															echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
															<?php echo $block->getBlockHtml('formkey') ?>
                                                            <button type="submit"
                                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                                    class="action tocart primary btn-action btn-cart">
																<span><?php /* @escapeNotVerified */
																	echo __('Add to Cart') ?></span>
															</button>
														</form>
													<?php else: ?>
														<?php if ($_product->getIsSalable()): ?>
                                                            <div class="stock available"><span><?php /* @escapeNotVerified */
																	echo __('In stock') ?></span></div>
														<?php else: ?>
                                                            <div class="stock unavailable btn-action btn-cart"><span><?php /* @escapeNotVerified */
																	echo __('Out of stock') ?></span></div>
														<?php endif; ?>
													<?php endif; ?>
												<?php } ?>
											</div>
										<?php } ?>

										<?php if ($homeStyle != 'home-16' && $homeStyle != 'home-17' && $homeStyle != 'home-18') { ?>
                                            <div class="bottom-action">
												<?php if ($_config->getAdvanced('show_wishlist_button')) { ?>
													<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                        <a href="#" class="action towishlist btn-action link-wishlist" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */
														echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button">
															<span><?php /* @escapeNotVerified */
																echo __('Add to Wish List') ?></span>
														</a>
													<?php endif; ?>
												<?php } ?>

												<?php if ($_config->getAdvanced('show_addtocart_button')) { ?>
													<?php if ($_product->isSaleable()): ?>
														<?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
														echo $postParams['action']; ?>" method="post">
															<input type="hidden" name="product" value="<?php /* @escapeNotVerified */
															echo $postParams['data']['product']; ?>">
															<input type="hidden" name="<?php /* @escapeNotVerified */
															echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */
															echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
															<?php echo $block->getBlockHtml('formkey') ?>
                                                            <button type="submit"
                                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                                    class="action tocart primary btn-action btn-cart">
																<span><?php /* @escapeNotVerified */
																	echo __('Add to Cart') ?></span>
															</button>
														</form>
													<?php else: ?>
														<?php if ($_product->getIsSalable()): ?>
                                                            <div class="stock available"><span><?php /* @escapeNotVerified */
																	echo __('In stock') ?></span></div>
														<?php else: ?>
                                                            <div class="stock unavailable btn-action btn-cart"><span><?php /* @escapeNotVerified */
																	echo __('Out of stock') ?></span></div>
														<?php endif; ?>
													<?php endif; ?>
												<?php } ?>

												<?php if ($_config->getAdvanced('show_compare_button')) { ?>
													<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                    <a href="#" class="action tocompare btn-action link-compare" title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" data-post='<?php /* @escapeNotVerified */
													echo $compareHelper->getPostDataParams($_product); ?>' role="button">
														<span><?php /* @escapeNotVerified */
															echo __('Add to Compare') ?></span>
													</a>
												<?php } ?>
											</div>
										<?php } ?>
									</div>
									
									<div class="thumbs-product">
										<?php
										$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
										$product       = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
										$images        = $product->getMediaGalleryImages();
										$limit         = 0;

										foreach ($images as $child) {
											$limit++;
											//var_dump($child->getData('file'));die('123123');
											if ($limit <= 4) {
												$img = $lthelper->_getImageThumbnail($child->getData('file'));
												if (!empty($img) && isset($img[0])) {
													$big_image_config   = [
														'width'      => 500,
														'height'     => 500,
														'background' => '#ffffff',
														'function'   => 1
													];
													$small_image_config = [
														'width'      => 80,
														'height'     => 80,
														'background' => '#ffffff',
														'function'   => 1
													];
													$resizedImageBig    = $lthelper->_resizeImage($img[0], $big_image_config, 'product');
													$resizedImageUrl    = $lthelper->_resizeImage($img[0], $small_image_config, 'product'); ?>
                                                    <div class="item-img" data-src="<?php echo $resizedImageBig; ?>">
														<img src="<?php echo $resizedImageUrl; ?>" alt="image"/>
													
													</div>
													<?php
												}
											}
										} ?>
									</div>
									
									<script type="text/javascript">
										require([
                                            'jquery'
                                        ], function ($) {
                                            $(".<?php echo $productInfo;?> .thumbs-product .item-img").click(function () {
                                                $(".<?php echo $productInfo;?> .thumbs-product .item-img").removeClass('thumb-active');
                                                $(this).addClass('thumb-active');
                                                var thumb_src = $(this).attr("data-src");
                                                $(".<?php echo $productInfo;?> .box-image a img").attr("src", thumb_src);
                                            });
                                        });
									</script>
									
								</div>
							</div>
						</div>
		<?php } ?>

			<?php if ($i % 7 == 2){ ?>
            <div class="col-lg-7">
            <div class="right-container">
            <div class="row">
		<?php } ?>

			<?php if ($i % 7 > 1 || $i % 7 == 0) { ?>
            <div class="item col-lg-4 col-md-4 col-6">
							<div class="item-inner">
								<!--Small Items-->
								<?php
								$productImage = $block->getImage($_product, $image);
								if ($pos != null) {
									$position = ' style="left:' . $productImage->getWidth() . 'px;'
										. 'top:' . $productImage->getHeight() . 'px;"';
								}
								?>
								<?php
								if ((int)$config['display_countdown'] && !empty($_product->getSpecialPrice()) && !empty($_product->getSpecialToDate())) {
									$specialToDate = $_product->getSpecialToDate();
									?>
                                    <div class="deals-countdown" data-timer="<?php echo date("Y/m/d H:i:s", strtotime($specialToDate)); ?>">
									<div class="deals-time time-day"><div class="num-time"></div><div class="title-time"></div></div>
									<div class="deals-time time-hours"><div class="num-time"></div><div class="title-time"></div></div>
									<div class="deals-time time-mins"><div class="num-time"></div><div class="title-time"></div></div>
									<div class="deals-time time-secs"><div class="num-time"></div><div class="title-time"></div></div>
								</div>
								<?php } ?>
								<?php // Product Image ?>
                                <div class="box-image">
									<a href="<?php /* @escapeNotVerified */
									echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
										<?php echo $productImage->toHtml(); ?>
									</a>

                                    <!--LABEL PRODUCT-->

									<?php
									$specialprice         = $_product->getSpecialPrice();
									$specialPriceFromDate = $_product->getSpecialFromDate();
									$specialPriceToDate   = $_product->getSpecialToDate();

									$today = time();

									if ($specialprice && $_config->getAdvanced('show_salelabel')) {
										if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
                                            <div class="label-product label-sale">
														<span class="sale-product-icon">
															<?php echo __('Sale'); ?>
														</span>
													</div>
										<?php }
									}
									?>

									<?php
									$now      = date("Y-m-d");
									$newsFrom = substr($_product->getNewsFromDate(), 0, 10);
									$newsTo   = substr($_product->getNewsToDate(), 0, 10);


									if (($newsTo != '' || $newsFrom != '') && $_config->getAdvanced('show_newlabel')) {
										if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) { ?>
                                            <div class="label-product label-new">
														<span class="new-product-icon"><?php echo __('New'); ?></span>
													</div>
										<?php }
									} ?>


                                    <!--END LABEL PRODUCT-->

									<?php if ($homeStyle == 'home-16' || $homeStyle == 'home-17' || $homeStyle == 'home-18') { ?>
                                        <div class="button-action">
											<?php if ($_config->getAdvanced('show_wishlist_button')) { ?>
												<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                    <a href="#" class="action towishlist btn-action link-wishlist" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */
													echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button">
														<span><?php /* @escapeNotVerified */
															echo __('Add to Wish List') ?></span>
													</a>
												<?php endif; ?>
											<?php } ?>

											<?php if ($_config->getAdvanced('show_compare_button')) { ?>
												<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                <a href="#" class="action tocompare btn-action link-compare" title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" data-post='<?php /* @escapeNotVerified */
												echo $compareHelper->getPostDataParams($_product); ?>' role="button">
													<span><?php /* @escapeNotVerified */
														echo __('Add to Compare') ?></span>
												</a>
											<?php } ?>
										</div>
									<?php } ?>
								</div>
								
								<div class="product details product-item-details box-info">
									<?php
									$_productNameStripped = $block->stripTags($_product->getName(), null, true);
									?>
                                    <h2 class="product name product-item-name product-name">
										<a class="product-item-link"
                                           href="<?php /* @escapeNotVerified */
										   echo $_product->getProductUrl() ?>">
											<?php /* @escapeNotVerified */
											echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
										</a>
									</h2>
									<?php echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>
									<?php /* @escapeNotVerified */
									echo $block->getProductPrice($_product) ?>
									<?php echo $block->getProductDetailsHtml($_product); ?>

									<?php if ($homeStyle == 'home-16' || $homeStyle == 'home-17' || $homeStyle == 'home-18') { ?>
                                        <div class="bottom-action">
											<?php if ($_config->getAdvanced('show_addtocart_button')) { ?>
												<?php if ($_product->isSaleable()): ?>
													<?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
													echo $postParams['action']; ?>" method="post">
														<input type="hidden" name="product" value="<?php /* @escapeNotVerified */
														echo $postParams['data']['product']; ?>">
														<input type="hidden" name="<?php /* @escapeNotVerified */
														echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */
														echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
														<?php echo $block->getBlockHtml('formkey') ?>
                                                        <button type="submit"
                                                                title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                                class="action tocart primary btn-action btn-cart">
															<span><?php /* @escapeNotVerified */
																echo __('Add to Cart') ?></span>
														</button>
													</form>
												<?php else: ?>
													<?php if ($_product->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */
																echo __('In stock') ?></span></div>
													<?php else: ?>
                                                        <div class="stock unavailable btn-action btn-cart"><span><?php /* @escapeNotVerified */
																echo __('Out of stock') ?></span></div>
													<?php endif; ?>
												<?php endif; ?>
											<?php } ?>
										</div>
									<?php } ?>

									<?php if ($homeStyle != 'home-16' && $homeStyle != 'home-17' && $homeStyle != 'home-18') { ?>
                                        <div class="bottom-action">
											<?php if ($_config->getAdvanced('show_wishlist_button')) { ?>
												<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                    <a href="#" class="action towishlist btn-action link-wishlist" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */
													echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button">
														<span><?php /* @escapeNotVerified */
															echo __('Add to Wish List') ?></span>
													</a>
												<?php endif; ?>
											<?php } ?>

											<?php if ($_config->getAdvanced('show_addtocart_button')) { ?>
												<?php if ($_product->isSaleable()): ?>
													<?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
													echo $postParams['action']; ?>" method="post">
														<input type="hidden" name="product" value="<?php /* @escapeNotVerified */
														echo $postParams['data']['product']; ?>">
														<input type="hidden" name="<?php /* @escapeNotVerified */
														echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */
														echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
														<?php echo $block->getBlockHtml('formkey') ?>
                                                        <button type="submit"
                                                                title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                                class="action tocart primary btn-action btn-cart">
															<span><?php /* @escapeNotVerified */
																echo __('Add to Cart') ?></span>
														</button>
													</form>
												<?php else: ?>
													<?php if ($_product->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */
																echo __('In stock') ?></span></div>
													<?php else: ?>
                                                        <div class="stock unavailable btn-action btn-cart"><span><?php /* @escapeNotVerified */
																echo __('Out of stock') ?></span></div>
													<?php endif; ?>
												<?php endif; ?>
											<?php } ?>

											<?php if ($_config->getAdvanced('show_compare_button')) { ?>
												<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                <a href="#" class="action tocompare btn-action link-compare" title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" data-post='<?php /* @escapeNotVerified */
												echo $compareHelper->getPostDataParams($_product); ?>' role="button">
													<span><?php /* @escapeNotVerified */
														echo __('Add to Compare') ?></span>
												</a>
											<?php } ?>
										</div>
									<?php } ?>
								</div>
							</div>
						</div>


		<?php } ?>

			<?php if ($i % 7 == 0 || $i == $count){ ?>
            </div>
            </div>
            </div>
            </div>
            </div>
		<?php } ?>

			<?php if ($nb_type_show == 'slider' && ($i % $nb_rows == 0 || $i == $count)) { ?>
            </div>
		<?php }
			if ($nb_type_show == 'loadmore') { ?>
                </div>
			<?php } ?>
		<?php endforeach; ?>
        </div>
    </div>