<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Remove $block */
?>

<div class="primary actions-primary">
    <a href="#" data-post-remove='<?= /* @noEscape */ $block->getItemRemoveParams($block->getItem()) ?>' title="<?= $block->escapeHtmlAttr(__('Remove Item')) ?>" class="btn-remove action delete">
        <button type="button" class="action submitbtn btn-warning">
            <span><?= $block->escapeHtml(__('Remove item')) ?></span>
        </button>
    </a>
</div>
