<div class="vesbrand-sidebar-mobile-btn d-block d-sm-block d-md-none d-lg-none">
<i class="fa fa-filter"></i>
  <?php echo __('Brands - Trademarks') ?>
</div>

<script type="text/javascript">
require(['jquery'], function ($) {
  $(document).ready(function(){
    $('.vesbrand-sidebar-mobile-btn').click(function(event){
      $('body').toggleClass("sidebar-active");
      $(".sidebar-left").toggleClass("active");
      if($(".sidebar-left").hasClass("active")) {
        $('.vesbrand-index-index.sidebar-active .sidebar-left, .vesbrand-brand-view.sidebar-active .sidebar-left').animate({'left': '0px'}, 200);
      }else{
        $('.vesbrand-index-index .sidebar-left, .vesbrand-brand-view .sidebar-left').animate({'left': '-300px'}, 200);
      }
    });
  });
});
</script>