<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $order = $block->getOrder();
    $infoBlock = $objectManager->get('Chottvn\Sales\Rewrite\Magento\Sales\Model\Order\Email\Sender\OrderSender');
?>
<td>
    <?php if ($order->getFrontendStatusLabel() == 'đang được giao!'): ?>
        <?= $infoBlock->footerShipping($order); ?>
    <?php endif ?>
    <?php if ($order->getFrontendStatusLabel() == 'đã được giao thành công!'): ?>
        <?= $infoBlock->footerSuccessfulDelivery($order); ?>
    <?php endif ?>
    <?php if ($order->getFrontendStatusLabel() == 'đã hủy bỏ!'): ?>
        <?= $infoBlock->footerCanceled($order); ?>
    <?php endif ?>
</td>