<?php $crumbs = $block->getCrumbs(); ?>
<?php if ($crumbs && is_array($crumbs)) : ?>
    <div class="breadcrumbs">
	<div class="container">
		<ul class="items">
			<?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
                <li class="item <?php /* @escapeNotVerified */
				echo $crumbName ?>">
				<?php if ($crumbInfo['link']) : ?>
                    <a href="<?php /* @escapeNotVerified */
					echo $crumbInfo['link'] ?>" title="<?php echo $block->escapeHtml($crumbInfo['title']) ?>">
						<?php echo $block->escapeHtml($crumbInfo['label']) ?>
					</a>
					<span>›</span>
				<?php else: ?>
					<?php echo $block->escapeHtml($crumbInfo['label']) ?>
				<?php endif; ?>
				</li>
			<?php endforeach; ?>
		</ul>
	</div>
</div>
<?php endif; ?>
