<?php
$percent_rating = (int) $block->getPercentRating();
?>
<div class="star-ratings-css">
    <div class="star-ratings-css-top" style="width: <?php echo $percent_rating; ?>%"><span><i class="fas fa-star"></i></span><span><i class="fas fa-star"></i></span><span><i class="fas fa-star"></i></span><span><i class="fas fa-star"></i></span><span><i class="fas fa-star"></i></span></div>
    <div class="star-ratings-css-bottom"><span><i class="fas fa-star"></i></span><span><i class="fas fa-star"></i></span><span><i class="fas fa-star"></i></span><span><i class="fas fa-star"></i></span><span><i class="fas fa-star"></i></span></div>
</div>