<?php
/**
 *
 * SM Listing Tabs - Version 2.5.0
 * Copyright (c) 2017 YouTech Company. All Rights Reserved.
 * @license - Copyrighted Commercial Software
 * Author: YouTech Company
 * Websites: http://www.magentech.com
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
if ($this->_isAjax()) {
	$products = $this->_ajaxLoad();
	$config   = $this->_getConfig();
} else {
	$config   = $this->getData('config');
	$products = $this->getData('products');
}
$_helper         = $this->helper('Magento\Catalog\Helper\Output');
$_config         = $this->helper('Sm\Market\Helper\Data');
$homeStyle       = $_config->getThemeLayout('home_style');
$viewMode        = 'grid';
$image           = 'category_page_grid';
$showDescription = false;
$templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$type_loadmore   = $config['type_show'] == 'loadmore' ? true : false;
$cls_mark        = $type_loadmore ? ' ltabs-mark ' : '';

$nb_type_show = $config['type_show'];

$nb_rows = 7;
$i       = 0;
$count   = count($products);
/**
 * Position for actions regarding image size changing in vde if needed
 */
$pos = $block->getPositioned();
?>
<div class="<?php /* @escapeNotVerified */
echo $viewMode; ?> products-<?php /* @escapeNotVerified */
echo $viewMode; ?>">
        <?php $iterator = 1; ?>
    <div class="scroll-container">
			<div class="scroll-block">
				<div class="grid-product-type products list items product-items item-table  <?php echo $type_loadmore == false ? ' ' : ''; ?>" <?php echo $type_loadmore ? 'data-liffect="fadeIn"' : ''; ?>>
					<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
					<?php foreach ($products as $_product):

						?>
						<?php /* @escapeNotVerified */
						echo ($iterator++ == 1) ? '<div class="item product product-item item-table-cell ' . $cls_mark . '">' : '</div><div class="item product product-item item-table-cell ' . $cls_mark . '">' ?>
                        <div class="item-inner">
							<div class="product-item-info" data-container="product-grid">
								<?php
								$productImage = $block->getImage($_product, $image);
								if ($pos != null) {
									$position = ' style="left:' . $productImage->getWidth() . 'px;'
										. 'top:' . $productImage->getHeight() . 'px;"';
								}
								?>

								<?php // Product Image 
								?>
                                <div class="product-item-image box-image">
									<a href="<?php /* @escapeNotVerified */
									echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
										<?php echo $productImage->toHtml(); ?>
									</a>

                                    <!--LABEL PRODUCT-->
									<?php
									$specialprice         = $_product->getSpecialPrice();
									$specialPriceFromDate = $_product->getSpecialFromDate();
									$specialPriceToDate   = $_product->getSpecialToDate();

									$today = time();

									if ($specialprice && $_config->getAdvanced('show_salelabel')) {
										if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
                                            <div class="label-product label-sale">
													<span class="sale-product-icon">
														<?php echo __('Sale'); ?>
													</span>
												</div>
										<?php }
									}
									?>

									<?php
									$now      = date("Y-m-d");
									$newsFrom = substr($_product->getNewsFromDate(), 0, 10);
									$newsTo   = substr($_product->getNewsToDate(), 0, 10);


									if (($newsTo != '' || $newsFrom != '') && $_config->getAdvanced('show_newlabel')) {
										if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) { ?>
                                            <div class="label-product label-new">
													<span class="new-product-icon"><?php echo __('New'); ?></span>
												</div>
										<?php }
									} ?>
                                    <!--END LABEL PRODUCT-->
								</div>
								
								<div class="product details product-item-details box-info">
									<?php
									$_productNameStripped = $block->stripTags($_product->getName(), null, true);
									?>
                                    <div class="product name product-item-name">
										<a class="product-item-link"
                                           href="<?php /* @escapeNotVerified */
										   echo $_product->getProductUrl() ?>">
											<?php /* @escapeNotVerified */
											echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
										</a>
									</div>
									<?php echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>
									<?php /* @escapeNotVerified */
									echo $block->getProductPrice($_product) ?>
									<?php echo $block->getProductDetailsHtml($_product); ?>

									<?php
									if ((int)$config['display_countdown'] && !empty($_product->getSpecialPrice()) && !empty($_product->getSpecialToDate())) {
										$specialToDate = $_product->getSpecialToDate();
										?>
                                        <div class="deals-countdown" data-timer="<?php echo date("Y/m/d H:i:s", strtotime($specialToDate)); ?>">
										<div class="deals-time time-day"><div class="num-time"></div><div class="title-time"></div></div>
										<div class="deals-time time-hours"><div class="num-time"></div><div class="title-time"></div></div>
										<div class="deals-time time-mins"><div class="num-time"></div><div class="title-time"></div></div>
										<div class="deals-time time-secs"><div class="num-time"></div><div class="title-time"></div></div>
									</div>
									<?php } ?>

                                    <div class="product-item-inner">
										<div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
											<?php if ($_config->getAdvanced('show_wishlist_button')) { ?>
												<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                    <a href="#" class="action towishlist btn-action link-wishlist" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */
													echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button">
														<span><?php /* @escapeNotVerified */
															echo __('Add to Wish List') ?></span>
													</a>
												<?php endif; ?>
											<?php } ?>

											<?php if ($_config->getAdvanced('show_addtocart_button')) { ?>
                                                <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
													<?php if ($_product->isSaleable()): ?>
														<?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
														echo $postParams['action']; ?>" method="post">
															<input type="hidden" name="product" value="<?php /* @escapeNotVerified */
															echo $postParams['data']['product']; ?>">
															<input type="hidden" name="<?php /* @escapeNotVerified */
															echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */
															echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
															<?php echo $block->getBlockHtml('formkey') ?>
                                                            <button type="submit"
                                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                                    class="action tocart primary">
																<span><?php /* @escapeNotVerified */
																	echo __('Add to Cart') ?></span>
															</button>
														</form>
													<?php else: ?>
														<?php if ($_product->getIsSalable()): ?>
                                                            <div class="stock available"><span><?php /* @escapeNotVerified */
																	echo __('In stock') ?></span></div>
														<?php else: ?>
                                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */
																	echo __('Out of stock') ?></span></div>
														<?php endif; ?>
													<?php endif; ?>
												</div>
											<?php } ?>

											<?php if ($_config->getAdvanced('show_compare_button')) { ?>
												<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                <a href="#" class="action tocompare btn-action link-compare" title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" data-post='<?php /* @escapeNotVerified */
												echo $compareHelper->getPostDataParams($_product); ?>' role="button">
													<span><?php /* @escapeNotVerified */
														echo __('Add to Compare') ?></span>
												</a>
											<?php } ?>
										</div>

									</div>
								
								</div>
							</div>
						</div>
						<?php echo ($iterator == count($products) + 1) ? '</div>' : '' ?>
					<?php endforeach; ?>
				</div>
			</div>
		</div>
    </div>
