<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\Resetpassword $block */
?>
<div class="chottvn-ui-v2">
    <div class="block block-send-otp block-form">
        <div class="block-title">
            <h1><span id="block-customer-login-heading" role="heading" aria-level="2"><i class="fas fa-check-square"></i> <?= __('Activated Successful') ?></span></h1>
        </div>
        <div class="block-content" aria-labelledby="block-customer-login-heading">
            <form action="<?= $block->escapeUrl($block->getUrl('*/*/resetpasswordpost')) ?>" method="post" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off" <?php endif; ?> id="form-validate" class="form password reset" data-mage-init='{"validation":{}}'>
                <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                    <div class="field mb-0">
                        <label class="label greeting"><span><?= $block->escapeHtmlAttr(__('Congratulations on becoming an Affiliate of chotructuyen.co!')) ?></span></label>
                    </div>
                    <div class="field mb-0">
                        <label class="label announcement-message"><span><?= $block->escapeHtmlAttr(__('Please setup a password to login to the chotructuyen.co system')) ?></span></label>
                    </div>
                    <div class="field password required" data-mage-init='{"passwordStrengthIndicator": {}}'>
                        <label class="label" for="password"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                        <div class="control">
                            <input type="password" class="input-text" name="password" id="password" placeholder="<?= $block->escapeHtml(__('Input Password')) ?>" data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>" data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>" data-validate="{'required-new-pass':true, 'chottvn-validate-password-length':true}" autocomplete="off">
                        </div>
                    </div>
                    <div class="field confirmation required">
                        <label class="label" for="password-confirmation"><span><?= $block->escapeHtml(__('Confirm Password')) ?></span></label>
                        <div class="control">
                            <input type="password" class="input-text" name="password_confirmation" id="password-confirmation" placeholder="<?= $block->escapeHtml(__('Input Confirm Password')) ?>" data-validate="{required:true, 'required-confirm-pass': true, equalTo:'#password'}" autocomplete="off">
                        </div>
                    </div>
                    <div class="field required">
                        <label class="label" for="auth_code"><span><?= $block->escapeHtml(__('Enter the OTP code we just sent to your phone number')) ?></span></label>
                        <div class="control group-controls">
                            <input name="auth_code" type="text" placeholder="<?= $block->escapeHtmlAttr(__('Input Authenticate Code')) ?>" class="input-text" id="auth_code" title="<?= $block->escapeHtmlAttr(__('Authenticate Code')) ?>" data-validate="{required:true}">
                            <!-- <button id="btn-send-otp" class="btn-inline" type="button"><?= $block->escapeHtmlAttr(__('_Send')) ?></button> -->
                        </div>
                    </div>
                    <div class="resend-section">
                        <a class="resend" href="javascript:;" id="send_otp" style="display: none;">
                            <div class="resend-icon">
                                <i class="fas fa-redo"></i>
                            </div>
                            <span class="resend-text"><?= $block->escapeHtml(__('Resend authenticate code')) ?></span>
                        </a>
                        <div class="resend" id="count_down" style="display: none;">
                            <div class="resend-icon">
                            </div>
                            <span class="resend-text"><?= $block->escapeHtml(__('Resend authenticate code')) ?></span>
                        </div>
                    </div>
                </fieldset>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Set a Password')) ?></span></button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    require([
        'Magento_Ui/js/modal/alert',
        'jquery'
    ], function(alert, $) {
        var sendOTPUrl = window.location.origin + "<?= $block->getAPIResendOtpResetPw(); ?>";
        var timeToResendOTP = <?= $block->getTimeToResendOTP(); ?>;
        var effectiveTime = <?= $block->getEffectiveTime(); ?>;
        var sentOTP = (timeToResendOTP <= 0) ? false : true;

        function intervalManager(flag, func, time) {
            if (flag) {
                var x = setInterval(func, time);
            } else {
                clearInterval(x);
            }
        }

        function countDown() {
            timeToResendOTP -= 1;
            displayCountDown(timeToResendOTP);
            if (timeToResendOTP <= 0) {
                intervalManager(false);
                hideCountDown();
                sentOTP = false;
                $('#btn-send-otp').prop('disabled', false);
            }
        }

        function hideCountDown() {
            $(".resend-announcement").hide();
            $("#send_otp").show();
            $("#count_down").hide();
        }

        function showCountDown() {
            $(".resend-announcement").show();
            $("#send_otp").hide();
            $("#count_down").show();
        }

        function displayCountDown(secs) {
            let min = Math.floor(secs / 60);
            let sec = secs % 60;
            let display_sec = (sec < 10) ? "0" + sec : sec;
            let time = min + ":" + display_sec;
            $("#count_down .resend-icon").html(time);
        }

        $(document).ready(function() {
            if (timeToResendOTP > 0) {
                intervalManager(true, countDown, 1000);
                showCountDown();
                $('#btn-send-otp').prop('disabled', true);
            } else {
                hideCountDown();
            }
        });

        function sendOTP() {
            $('#btn-send-otp').prop('disabled', true);
            if (!sentOTP) {
                $.ajax({
                    url: sendOTPUrl,
                    type: "post",
                    contentType: "application/json",
                    dataType: "json",
                    showLoader: true,
                    data: JSON.stringify({
                        phoneNumber: "<?= $block->getForgottenPhone(); ?>"
                    }),
                    success: function(result) {
                        let rs = JSON.parse(result);
                        if (rs.status) {
                            sentOTP = true;
                            timeToResendOTP = effectiveTime;
                            showCountDown();
                            intervalManager(true, countDown, 1000);
                        } else {
                            $('#btn-send-otp').prop('disabled', false);
                        }

                        alert({
                            title: "<?= $block->escapeHtml(__('Resend authenticate code')) ?>",
                            content: rs.message,
                            actions: {
                                always: function() {}
                            }
                        });
                    },
                    error: function(result) {
                        $('#btn-send-otp').prop('disabled', false);
                    }
                });
            }
        }

        $('#send_otp').click(function() {
            sendOTP();
        });

        $('#btn-send-otp').click(function() {
            sendOTP();
        });
    });
</script>