<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<div class="chottvn-ui-v2">
    <div class="block block-form">
        <form class="form password forget" action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>" method="post" id="form-validate" data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                <h1><span><i class="fas fa-user"></i> <?= $block->escapeHtml(__('Forgot Password')) ?></span></h1>
                <!-- <legend class="legend"><span><i class="fas fa-lock"></i> <?= __('Forgot Password') ?></span></legend><br> -->
                <div class="field note"><?= $block->escapeHtml(__('Please enter your phone number below to receive a OTP code for reset password.')) ?></div>
                <div class="field required">
                    <label class="label" for="full_name"><span><?= $block->escapeHtml(__('Full Name')) ?></span></label>
                    <div class="control">
                        <input type="text" name="full_name" placeholder="<?= __('Input First name') ?>" alt="<?= $block->escapeHtml(__('Full Name')) ?>" id="full_name" class="input-text" data-validate="{required:true, 'required-firstname':true}">
                    </div>
                </div>
                <div class="field required">
                    <label class="label" for="phone_number"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
                    <div class="control">
                        <input type="tel" name="phone_number" placeholder="<?= __('Input Phone number') ?>" alt="<?= $block->escapeHtml(__('Phone Number')) ?>" id="phone_number" class="input-text" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-phone-VN':true}">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
            </fieldset>
            <div class="actions-toolbar register-action">
                <div class="primary">
                    <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Submit')) ?></span></button>
                </div>
                <div class="secondary back">
                    <a class="action back" href="<?= $block->escapeUrl($block->getUrl('*/*/login')) ?>"><span><i class="fas fa-backward"></i> <?= $block->escapeHtml(__('Back')) ?></span></a>
                </div>
            </div>
        </form>
    </div>
</div>