<?php
/**
 * Brand list template
 *
 * @var $block \Ves\Brand\Block\BrandList
 */
?>
<?php
$_brandCollection = $block->getBrandCollection();
$_brandData = $_brandCollection->getData();
$_helper = $this->helper('Ves\Brand\Helper\Data');
$blockId = rand().time();
$addition_class = $this->getConfig('brand_block/addition_class');
$interval = $this->getConfig('brand_block/interval',1000);
$dots = $this->getConfig('brand_block/dots',true);
?>
<?php if (!empty($_brandData)): ?>
<?php if (!empty( $_brandCollection)): ?>
<div class="block widget ves-widget brand-widget brand-widget-product <?php echo $addition_class?$addition_class:'' ?>">
	<div id="productcarousel-<?php echo $blockId ?>" class="block-content carousel slide" data-ride="carousel" data-interval="<?php echo $interval?$interval:"false"; ?>">
		<!-- Wrapper for slides -->
		<div class="carousel-inner" role="listbox">
            <?php foreach ($_brandData as $item): ?>
                <?php foreach ($_brandCollection as $_brand) : ?>
                    <?php if($item['brand_id'] == $_brand->getBrandId()): ?>
                        <div class="brand-item">
                            <div class="brand-image"><a href="<?php echo $_brand->getUrl(); ?>" title="<?php echo $_brand->getName(); ?>"><img src="<?php echo $_brand->getThumbnailUrl(); ?>" alt="<?php echo $_brand->getName(); ?>"/></a></div>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endforeach; ?>
		</div>
	</div>
</div>
<?php endif; ?>
<?php endif; ?>
