<?php
namespace Sm\ListingTabs\Block;
 
use Magento\Framework\View\Element\Template;
 
class Ajax extends Template
{
  protected $_storeManager;
  protected $_storeId;
  protected $_storeCode;

  public function __construct(
    Template\Context $context,
    array $data = []
  ){
    $this->_storeManager = $context->getStoreManager();
    $this->_storeId = (int)$this->_storeManager->getStore()->getId();
    $this->_storeCode = $this->_storeManager->getStore()->getCode();
    parent::__construct($context, $data);
  }

  protected function _prepareLayout()
  {
    return parent::_prepareLayout(); // TODO: Change the autogenerated stub
  }

  public function getAjaxUrl(){
    return $this->_storeManager->getStore()->getBaseUrl().'listingtabs/ajax/index';
  }

  function generateBlockName($length = 5,$timestamp = 0) {
    $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
    $charactersLength = strlen($characters);
    $randomString = '';
    for ($i = 0; $i < $length; $i++) {
        $randomString .= $characters[rand(0, $charactersLength - 1)];
    }
    return $randomString.$timestamp;
  }
}
