<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * @var $block \Magento\Sales\Block\Order\Comments
 * @see \Magento\Sales\Block\Order\Comments
 */
?>

<style>
    .order.additional.details.comments {
        text-align: end;
        padding: 0 5px;
    }
    .order.additional.details.comments .subtitle {
        margin-bottom: 10px;
        font-size: 16px;
        font-weight: 600;
    }
</style>

<?php if ($block->hasComments()) : ?>
    <div class="order additional details comments">
        <h3 class="subtitle"><?= $block->escapeHtml($block->getTitle()) ?></h3>
        <dl class="order comments">
            <?php foreach ($block->getComments() as $_commentItem) : ?>
                <dd class="comment text">
                    <?= $block->escapeHtml($_commentItem->getComment()) ?> | <?= $block->formatDate($_commentItem->getCreatedAt(), \IntlDateFormatter::MEDIUM, true) ?>
                </dd>
            <?php endforeach; ?>
        </dl>
    </div>
<?php endif;?>
