<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Sales\Block\Order\Items $block */
?>
<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $checkoutSession = $objectManager->get('Magento\Checkout\Model\Session');
    $_order = $checkoutSession->getLastRealOrder();
    $salesHelper = $this->helper('Chottvn\Sales\Helper\Data');
    try {
        $timefc = $objectManager->create('\Magento\Framework\Stdlib\DateTime\TimezoneInterface');
        $createdDate = $timefc->date($_order->getCreatedAt())->format('Y-m-d');
        $maxDeliveryDates = $_order->getMaxDeliveryDates();
        $estimatedDeliveryDate = date('d/m/Y', strtotime($createdDate . " + ".$maxDeliveryDates." day"));
    } catch(\Exception $e) {
        $estimatedDeliveryDate = 0;
    }
?>
<div class="row">
    <!-- OrderItems-Header -->
    <div class="col-sm-8 item-head">
            <?php if($maxDeliveryDates): ?>
                <?= __("Estimated delivery date"); ?>: <?= $estimatedDeliveryDate;; ?>
            <?php else: ?>
                <?= __("Estimated delivery date"); ?>: <?= __("Max Delivery Dates Contact"); ?>
            <?php endif; ?>
    </div>
    <div class="col-sm-2 hidden-xs item-head p-l-r" style="text-align:right;">
        <?= $block->escapeHtml(__('Quantity x Price')) ?>
    </div>
    <div class="col-sm-2 hidden-xs text-right item-head">
        <?= $block->escapeHtml(__('Amount')) ?>
    </div>
</div>
<?php $giftMessage = ''?>
<?php 
    $orderItems =  $block->getItems(); 
    $arrayMain = array();
    $arrayMain = $salesHelper->getListOrder($orderItems);
?>
<?php
    if(!empty($arrayMain) && count($arrayMain) > 0){ ?>
        <?php foreach ($arrayMain as $item): ?>
            <div class="row">
                <?= $block->getItemHtml($item) ?>
                <?php if ($this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order_item', $item) && $item->getGiftMessageId()): ?>
                    <?php $giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessageForEntity($item); ?>
                    <tr>
                        <td class="col options" colspan="5">
                            <a href="#"
                                id="order-item-gift-message-link-<?= /* @escapeNotVerified */ $item->getId() ?>"
                                class="action show"
                                aria-controls="order-item-gift-message-<?= /* @escapeNotVerified */ $item->getId() ?>"
                                data-item-id="<?= /* @escapeNotVerified */ $item->getId() ?>">
                                <?= /* @escapeNotVerified */ __('Gift Message') ?>
                            </a>
                            <?php $giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessageForEntity($item); ?>
                            <div class="order-gift-message" id="order-item-gift-message-<?= /* @escapeNotVerified */ $item->getId() ?>" role="region" aria-expanded="false" tabindex="-1">
                                <a href="#"
                                    title="<?= /* @escapeNotVerified */ __('Close') ?>"
                                    aria-controls="order-item-gift-message-<?= /* @escapeNotVerified */ $item->getId() ?>"
                                    data-item-id="<?= /* @escapeNotVerified */ $item->getId() ?>"
                                    class="action close">
                                    <?= /* @escapeNotVerified */ __('Close') ?>
                                </a>
                                <dl class="item-options">
                                    <dt class="item-sender"><strong class="label"><?= /* @escapeNotVerified */ __('From') ?></strong><?= $block->escapeHtml($giftMessage->getSender()) ?></dt>
                                    <dt class="item-recipient"><strong class="label"><?= /* @escapeNotVerified */ __('To') ?></strong><?= $block->escapeHtml($giftMessage->getRecipient()) ?></dt>
                                    <dd class="item-message"><?= /* @escapeNotVerified */ $this->helper('Magento\GiftMessage\Helper\Message')->getEscapedGiftMessage($item) ?></dd>
                                </dl>
                            </div>
                        </td>
                    </tr>
                <?php endif ?>
            </div>
        <?php endforeach; ?>
    <?php } ?>
<?php if ($giftMessage): ?>
<script type="text/x-magento-init">
    {
        "a.action.show, a.action.close": {
            "giftMessage": {}
        }
    }
</script>
<?php endif; ?>
