<?php
/**
 * PriceQuote Request View template
 *
 * @var $block \Magento\PriceQuote\Block\Request\View
 */


$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$reviewFactory = $objectManager->create('Magento\Review\Model\Review');
$storeId = $storeManager->getStore()->getId();
$saleRuleFactory = $objectManager->create('Magento\SalesRule\Model\ResourceModel\Rule\CollectionFactory');
$salesHelper = $this->helper('Chottvn\Sales\Helper\Data');
$imageHelper = $this->helper('Magento\Catalog\Helper\Image');
$productBrandHelper = $this->helper('Ves\Brand\Helper\ProductBrand');
$amPromoHelper = $this->helper('Amasty\Promo\Helper\Item');
$priceQuoteHelper = $this->helper('Chottvn\PriceQuote\Helper\Data');
$detectMobile = $objectManager->get('\Chottvn\Frontend\Helper\DetectMobile');
$blockRules = $block->getLayout()->createBlock('Chottvn\Frontend\Block\Rules');
$priceQuoteRequest = $block->getPriceQuoteRequest();
$requestId = $priceQuoteRequest->getData('request_id');
$actual_link = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]";
$messages_prefix = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('ampromo/messages/prefix');
$productRepository = $objectManager->get('\Magento\Catalog\Model\Product');
$itemOptions = $objectManager->get('Magento\Quote\Model\ResourceModel\Quote\Item\Option\CollectionFactory');
?>
<div class="desktop">
    <div class="price_quote-request-view-pdf">
        <div class="page-wrapper container">
        <table style="width: 100%;">
            <tr>
                <td class="header-section" style="width: 65%;">
                    <div class="logo">
                        <img src="<?= $this->getViewFileUrl('images/logo-cho-truc-tuyen-desktop.png'); ?>"
                            alt="<?php echo $block->getLogoAlt() ?>"
                            />
                    </div>
                </td>
                <td class="header-section" style="width: 35%;">
                    <?= $this->getLayout()
                        ->createBlock('Magento\Cms\Block\Block')
                        ->setBlockId('price-quote-print-header-right')
                        ->toHtml(); ?>
                </td>
            </tr>
        </table>
    <?php 
        $request = $block->getPriceQuoteRequest(); 
        $company_name = $request->getData('company_name');
        $company_address = $request->getData('company_address');
        $company_vat_number = $request->getData('company_vat_number');
        $contact_name = $request->getData('contact_name');
        $contact_phone_number = $request->getData('contact_phone_number');
        $contact_email = $request->getData('contact_email');
    ?>
    <table style="width: 100%; ">
        <tr>
        <td class="quote-title">
            <h1><?= __("Price Quote Table") ?></h1>
            <p><?= __("Date") ?>: <?= $block->getRequestDate() ?></p>
        </td>
        </tr>
    </table>
    <table class="greeting-first" style="width: 100%; ">
        <tr>
        <td class="greeting-section" style="width: 62px; white-space: nowrap;">
            <p><?= __("Dear") ?>:</p>
        </td>
        <td class="greeting-section">
            <p><strong><?php echo $company_name; ?></strong> - <?php echo $company_vat_number; ?></p>
        </td>
        </tr>
        <tr>
        <td class="greeting-section" style="width: 62px;">
        </td>
        <td class="greeting-section">
            <p><?php echo $company_address; ?></p>
            <?php if ($contact_name || $contact_phone_number || $contact_email) : ?>
                <p><?= __("Contact/Price quote receiver info") ?></p>
                <?php if ($contact_name) : ?>
                    <p> <?= __("Mr/Mrs") ?>&nbsp;<span class="contact-name"><?= $block->getContactName(); ?></span></p>
                <?php endif; ?>
                    <p> 
                        <?= $contact_phone_number ? $contact_phone_number: ''; ?> <?= $contact_phone_number && $contact_email ? '<span class="sign-price-quote"> - </span>': ''; ?> <?= $contact_email ? '<span class="email-price-quote">'.$contact_email.'</span>': ''; ?>
                    </p>
            <?php endif; ?>
        </td>
        </tr>
        <tr>
        <td colspan="2" class="greeting-section">
            <?= $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('price-quote-greeting')
                ->toHtml(); ?>
        </td>
        </tr>
    </table>
    </div><!-- ./page-header -->
        <div class="page-content" style="width: 100%;">
                <?php if(! $block->isRequestNotFound()){ //Request EXIST ?>
                        <?php
                        // Cart - items
                        if ($block->getItemsCount($requestId) > 0) {
                            $requestQuote = $priceQuoteHelper->getCollectionRequest($requestId);
                            $originalTotal = $requestQuote->getData('original_total');
                            $savingsAmount = $requestQuote->getData('savings_amount');
                            $discountAmount = $requestQuote->getData('discount_amount');
                            $shippingAmount = $requestQuote->getData('shipping_amount');
                            $couponcode = $requestQuote->getData('coupon_code');
                            $grandTotal = $requestQuote->getData('grand_total');
                            $flagShipping = $requestQuote->getData('flag_shipping');
                            $requestItems = $priceQuoteHelper->getCollectionItems($requestId);
                            $arrayMain = array();
                            $arrayMain = $priceQuoteHelper->getListPriceQuote($requestItems);
                            if(!empty($arrayMain) && count($arrayMain) > 0){
                        ?>
                            <table class="quote-table" style="width: 100%;">
                                <thead>
                                <tr>
                                    <th colspan="2" style="text-align: left;white-space: nowrap;padding: 15px 15px 15px 0px;">
                                    <?= $block->escapeHtml(__('Product information')) ?>
                                    </th>
                                    <th style="width: 170px; text-align: right;white-space: nowrap;padding: 15px 0px 15px 0px;">
                                    <?= $block->escapeHtml(__('Quantity x Price')) ?>
                                    </th>
                                    <th style="width: 170px; text-align: right; white-space: nowrap;padding: 15px 0px 15px 15px;">
                                    <?= $block->escapeHtml(__('Amount')) ?>
                                    </th>
                                </tr>
                                </thead>
                                <tbody class="cart-items">
                                <?php foreach ($arrayMain as $item) :?>
                                    <?php
                                        $product = $objectManager->create('Magento\Catalog\Model\Product')->load($item['product_id']);
                                        // guaranteeInfo
                                        $guaranteeInfo = $item['guarantee'] ? $item['guarantee']:'';
                                        
                                        // productunit
                                        $productunit = $item['product_unit'] ? $item['product_unit'] : '';
                                        // all rule
                                        // $ruleNames = $saleRuleFactory->create()->addFieldToFilter('rule_id', array('in' => json_decode($item['all_rule_ids'])) )->addFieldToSelect('name');
                                        $applied_rule_ids = $item['applied_rule_ids'];
                                        $parentrequestItemId = $item['id'];
                                        $itemId = $item['item_id'];
                                        $ruleNames = $priceQuoteHelper->getRulesNameWithPriceQuoteCTT($itemId,$requestId,$applied_rule_ids);
                                        // brand id
                                        $brandId = $item['product_brand_id'] ? $item['product_brand_id']: '';
                                    
                                       
                                        // $isPromoItem = $priceQuoteHelper->isPromoItem($itemId);

                                        $cartPromoOption = $item['cart_promo_option'];
                                        $isPromoItem = $priceQuoteHelper->isPromoItemCTT($cartPromoOption);
          
                                        $attributesOption = array();
                                        if(isset($item['product_options'])){
                                            $attributesOption = json_decode($item['product_options']);
                                        }
                                        // url and image
                                        $jacket = array();
                                        $productidOfconfigurable = $item['product_id'];
                                        if($attributesOption){
                                            $itemQuote = $objectManager->get('Magento\Quote\Model\ResourceModel\Quote\Item\CollectionFactory');
                                            $itemQuoteCollection = $itemQuote->create()->addFieldToFilter('parent_item_id',$item['item_id'])->addFieldToFilter('product_type','simple');
                                            $lastItemQuote = $itemQuoteCollection->getLastItem();
                                            $productidOfconfigurable = $lastItemQuote->getData('product_id');
                                        }
                                        $productTypeInstance = $objectManager->get('Magento\Catalog\Model\ResourceModel\Eav\Attribute');
                                        if ($attributesOption) {
                                            foreach ($attributesOption as $key => $attr) {
                                                $_attr = $productTypeInstance->load($key);
                                                $attributeCode = $_attr->getAttributeCode();
                                                $jacket[$attributeCode] = $attr;
                                            }
                                        }
                                        
                                        $getProductUrl = $product->getProductUrl();
                                        if ($jacket) {
                                            $getProductUrl = $getProductUrl . '#';
                                            foreach($jacket as $key => $value){
                                                $getProductUrl = $getProductUrl .$key. '='. $value .'&';
                                            }
                                            $getProductUrl = substr($getProductUrl, 0, -1);
                                        }
                                        $productImage = null;
                                        $productModel = $item['model'];
                                        if($productidOfconfigurable != $item['product_id']){
                                            $productResourceConfiguration = $objectManager->create('Magento\Catalog\Model\Product')->load($productidOfconfigurable);
                                            if(!$productModel){
                                                $productModel = $productResourceConfiguration->getData('model');
                                            }
                                            $productImage = $imageHelper->init($productResourceConfiguration, 'category_page_list')->getUrl();
                                        }else{
                                            $productImage = $imageHelper->init($product, 'category_page_list')->setImageFile($product->getImage())->getUrl();
                                        }
                                        
                                        if (!isset($productImage)) {
                                            $imageHelper = $objectManager->get(\Magento\Catalog\Helper\Image::class);
                                            $productImage = $imageHelper->getDefaultPlaceholderUrl('image');
                                        }
                                       
                                    ?>
                                <tr class="cart-item-body">
                                    <td class="item-body" style="width: 170px;">
                                        <div class="product-item-photo product-item-photo-desktop">
                                            <div class="img-box ">
                                                <?php if ($priceQuoteHelper->hasProductUrl($product)) : ?>
                                                    <a href="<?= $block->escapeUrl($priceQuoteHelper->getProductUrl($product)) ?>" title="<?= $block->escapeHtml($item['name']) ?>">
                                                        <img src="<?=$productImage?>" alt="<?= $block->escapeHtml($item['name']) ?>" />
                                                    </a>
                                                <?php else : ?>
                                                    <img src="<?=$productImage?>" alt="<?= $block->escapeHtml($item['name']) ?>" />
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="item-body">
                                    <p class="product-item-name">
                                            <?php
                                                $itemId = $item->getData('item_id');
                                                $lastItemOptions = $itemOptions->create()->addFieldToFilter('item_id', array('eq' => $itemId));
                                                $lastItemOptions = $lastItemOptions->getLastItem();
                                                $rulesId = ''; $nameRule = '';
                                                if(isset($lastItemOptions['value'])){
                                                    $arrRulesId = json_decode($lastItemOptions['value'], true);
                                                    if(isset($arrRulesId["options"]) && isset($arrRulesId["options"]['ampromo_rule_id'])){
                                                        $rulesId = $arrRulesId["options"]['ampromo_rule_id'];
                                                    }
                                                }
                                                if($rulesId){
                                                    $nameRule = $priceQuoteHelper->getRulesNameByIdRule($rulesId);
                                                }
                                            ?>
                                            <?php if ($priceQuoteHelper->hasProductUrl($product)) : ?>
                                                <a href="<?= $block->escapeUrl($getProductUrl) ?>" title="<?= $block->escapeHtml($block->getProductName()) ?>">
                                                    <?php if($isPromoItem){ ?>
                                                        <!-- Rule Name -->
                                                        <?= $nameRule ? '<strong>'.$nameRule.'</strong>': ''; ?>
                                                        <span><?= $product->getName(); ?></span>
                                                    <?php }else{ ?>
                                                        <?= $product->getNameLongHtml(); ?>
                                                    <?php } ?>
                                                </a>
                                            <?php else : ?>
                                                <?php if($isPromoItem){ ?>
                                                    <!-- Rule Name -->
                                                    <?= $nameRule ? '<strong>'.$nameRule.'</strong>': ''; ?>
                                                    <!-- Name Product -->
                                                    <span><?= $product->getName(); ?></span>
                                                <?php }else{ ?>
                                                    <?= $product->getNameLongHtml(); ?>
                                                <?php } ?>
                                            <?php endif; ?>
                                    </p>
                                    <?php
                                    $productBrand = $productBrandHelper->getBrandById($brandId);
                                        if ($productBrand ){
                                    ?>
                                    <p class="brand-name">
                                        <span><?php echo __('Brands: '); ?></span>
                                        <span class="name"><?php echo $productBrand->getName(); ?></span>
                                    </p>
                                    <?php } ?>
                                    <?php
                                        if ($productModel) {
                                    ?>
                                    <p class="model-name">
                                        <span><?php echo __('Model: '); ?></span>
                                        <span class="name"><?php echo $productModel; ?></span>
                                    </p>
                                    <?php } ?>
                                        <?php if (!$isPromoItem) { ?>
                                        <!-- Reviews -->
                                            <?php  if (false && $ratingSummary) { ?>
                                            <p class="rating-summary">
                                                <span class="rating-result" title="<?= $block->escapeHtmlAttr($ratingSummary); ?>%">
                                                <?php
                                                for ($x = 0; $x < $starSolid; $x++) {
                                                    echo "<i class='fas fa-star star solid'></i>";
                                                }
                                                for ($x = 0; $x < $starTransparent; $x++) {
                                                    echo "<i class='fas fa-star star'></i>";
                                                }
                                                ?>
                                                </span>
                                                <span class="rating-label">
                                                <?php if ($ratingCount == 0) {
                                                echo __('No review on product');
                                                } else {
                                                echo __('Have %1 reviews', $ratingCount);
                                                }
                                                ?>
                                                </span>
                                            </p>
                                            <?php } ?>
                                            <!-- Guarantee -->
                                            <?php if ($guaranteeInfo) { ?>
                                                <p class="guarantee-info">
                                                    <span><?php echo __('Guarantee: '); ?></span>
                                                    <span class="name"><?php echo $guaranteeInfo; ?></span>
                                                </p>
                                            <?php } ?>
                                            <?php if ($attributesOption) { ?>
                                                <p class="guarantee-info">
                                                    <?php foreach($attributesOption as $key => $value): ?>
                                                        <?php 
                                                            $productTypeInstance = $objectManager->get('Magento\ConfigurableProduct\Model\Product\Type\Configurable');
                                                            $productAttributeOptions = $productTypeInstance->getConfigurableAttributesAsArray($product);
                                                            $labelOptions = '';
                                                            $valueOptions = '';
                                                            foreach ($productAttributeOptions as $key_o => $value_o) {
                                                                $tmp_option = $value_o['values'];
                                                                if(count($tmp_option) > 0)
                                                                {   
                                                                    foreach ($tmp_option as $tmp) {
                                                                        if($key_o == $key && $tmp['value_index'] == $value){
                                                                            $labelOptions = $value_o['store_label'];
                                                                            $valueOptions = $tmp['label'];
                                                                            break;
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        ?>
                                                        <span class="span-options-right"><?php echo $labelOptions; ?>: <?php echo $valueOptions; ?></span>
                                                    <?php endforeach; ?>
                                                </p>
                                            <?php } ?>
                                            <!-- Cart Rules -->
                                            <?php if ((!empty($ruleNames)) && (count($ruleNames) > 0)) { ?>
                                                    <div class="promotion-info">
                                                        <ul class="rules-list">
                                                            <?php foreach ($ruleNames as $key => $rules) { ?>
                                                                <?php if(!empty($rules['sku']) && count($rules['sku']) > 0){ ?>
                                                                    <?php foreach($rules['sku'] as $index => $sku){ ?>
                                                                        <?php 
                                                                            $productData = $productRepository->loadByAttribute('sku',$sku);
                                                                            if (!empty($productData)){
                                                                                $productId = $productData->getId();
                                                                                $nameproduct = $productData->getName();
                                                                                $visibility = $priceQuoteHelper->hasProductUrl($productRepository->load($productId));
                                                                                $urlProduct = $productData->getProductUrl();
                                                                                $unitProduct = $rules['unit_product'][$index] ? ' '.$rules['unit_product'][$index]: '';
                                                                                $qtyGift = $rules['qty'][$index] ? (int) $rules['qty'][$index] * (int) $item['qty']: '';
                                                                                $resultString = '('.$qtyGift.$unitProduct.')';
                                                                        ?>
                                                                        <li>
                                                                            <img class="img-gift" src="<?= $actual_link.'/pub/media/amasty/amoptimizer_dump/icon/icon_gift.png' ?>"/></strong><span class="span-product"><?php echo $nameproduct; ?> <?php echo $resultString; ?> </span>
                                                                            <?php if($visibility){?>
                                                                                <a class="see-more-rules" href= '<?php echo $urlProduct; ?>' title="<?= $nameproduct ?>">
                                                                                    <span class="span-load-more"><?= __('Load more details'); ?> &raquo;</span>
                                                                                </a>
                                                                            <?php }?>
                                                                        </li>
                                                            <?php }}}} ?>
                                                        </ul>
                                                    </div>
                                            <?php } ?>
                                            <?php if(false && $isPromoItem){ ?>
                                            <div class="message-gift">
                                                <i class="fas fa-gift"></i> <span><?= $item['message']; ?></span>
                                            </div>
                                            <?php } ?>
                                        <?php } ?>
                                        </td>
                                        <td class="item-body" style="width: 140px;">
                                            <?php if (!$isPromoItem) { ?>
                                            <div class="product-price">
                                                <p class="order-quantity"><?= (int) $item['qty'];  ?><?php if($productunit): ?> <?= $productunit;  ?><?php endif; ?></span></p>
                                                <p class="order-price"><?= $block->formatPrice($item['price']);  ?></p>
                                                    <?php
                                                    $priceOriginal = $item['original_price'];
                                                    $priceFinal = $item['price_incl_tax'];

                                                    $savePercent = ($priceOriginal == 0) ? 0 : 100 - round(@($priceFinal / $priceOriginal) * 100);
                                                    if ($savePercent != 0) {
                                                    ?>
                                                        <div class="order-save-price">
                                                            <span class="save-percent">-<?= $savePercent; ?>%</span>
                                                            <span class="price-original" style="margin-left: 10px;"><?= $block->formatPrice($priceOriginal); ?></span>
                                                        </div>
                                                    <?php } ?>
                                            </div>
                                            <?php } ?>
                                        </td>
                                    <td class="item-body" style="width: 140px;text-alight: right">
                                        <?php if (!$isPromoItem) { ?>
                                            <div class="sales-price" style="text-alight: right;padding:0">
                                                <?= $block->formatPrice($item['row_total']);  ?>
                                            </div>
                                        <?php } ?>
                                    </td>
                                </tr><!-- /.cart-item-body -->
                                <?php endforeach ?>
                                </tbody>
                                <tfoot>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td width="200px">
                                        <p class="totals sub">
                                            <?= $block->escapeHtml(__('Original Total')) ?>:
                                        </p>
                                        <?php if ((int)$savingsAmount > 0): ?>
                                            <p class="totals">
                                            <?= $block->escapeHtml(__('Savings Amount')) ?>:
                                            </p>
                                        <?php endif ?>
                                        <?php if ((int)$discountAmount < 0) : ?>
                                            <p class="totals">
                                            <?= $block->escapeHtml(__('Discount Amount')) ?>:
                                            </p>
                                        <?php endif ?>
                                        <p class="totals shipping">
                                            <?= $block->escapeHtml(__('Shipping & Handling(temp)')) ?>:
                                        </p>
                                        <p class="totals grand" style="font-weight: bold">
                                            <?= $priceQuoteHelper->getCustomTitleGrandTotal($requestQuote) ?>:
                                        </p>
                                        <?php if($couponcode): ?> 
                                            <p class="total-couponcode">
                                                <?= __('Discount code'); ?>:
                                            </p>
                                        <?php endif; ?>
                                    </td>
                                    <td style="text-align: right;">
                                        <p class="totals sub">
                                            <span class="amount" style="font-weight: bold;"><?= $block->formatPrice($originalTotal); ?></span>
                                        </p>
                                        <?php if ((int)$savingsAmount > 0): ?>
                                            <p class="totals savings">
                                                <span class="amount">
                                                    <?= $block->formatPrice($savingsAmount); ?>
                                                </span>
                                            </p>
                                        <?php endif ?>
                                        <?php if ((int)$discountAmount < 0) : ?>
                                            <p class="totals">
                                                <span class="amount">
                                                    <?php 
                                                        $discountAmount = (string) $discountAmount;
                                                        $discountAmount = (int) substr($discountAmount, 1);
                                                    ?>
                                                    <?= $block->formatPrice($discountAmount); ?>
                                                </span>
                                            </p>
                                        <?php endif ?>
                                        <p class="totals shipping">
                                            <span class="amount"><?= $priceQuoteHelper->getCustomShippingAmount($requestQuote); ?></span>
                                        </p>
                                        <p class="totals grand">
                                            <span class="grand-total"> <?= $block->formatPrice($grandTotal);?></span>
                                            <span class="vat-info"><?php echo __('Include VAT') ?></span>
                                            </span>
                                        </p>
                                        <?php if($couponcode): ?>
                                            <p class="totals" style="font-weight: 600 !important;">
                                                <?= $couponcode;?>
                                            </p>
                                        <?php endif; ?>
                                    </td>
                                </tr>
                                </tfoot>
                            </table>
                        <?php } ?>
                        <table style="width: 100%; margin-left: -15px;">
                            <tr>
                            <td class="price-quote-note">
                                <?= $this->getLayout()
                                    ->createBlock('Magento\Cms\Block\Block')
                                    ->setBlockId('price-quote-note')
                                    ->toHtml(); ?>
                            </td>
                            </tr>
                        </table>
            <?php
                // Cart - empty
                } else{
            ?>
            <div class="cart-empty">
                    <p>
                        <i class="fa fa-cart-plus cart-icon"></i>
                    </p>
                    <p>
                        <?= $block->escapeHtml(__('Shopping cart is empty')) ?>
                    </p>
                    <p>
                        <a href="<?= $block->escapeUrl($block->getContinueShoppingUrl()); ?>"
                            title="<?= $block->escapeHtml(__('Continue shopping')); ?>"
                            class="btn btn-primary btn-continue-shopping">
                            <?= $block->escapeHtml(__('Continue shopping')); ?>
                        </a>
                    </p>
            </div>
                <?php
                }
                ?>
                <?php }else{ // Request NOT FOUND ?>
                    <div class="page-title text-center mt-3">
                        <h3><?= __("Price Quote Not Found") ?></h3>
                    </div>
                <?php } ?>
        </div><!-- .page-content -->
    </div>
</div>
<!-- mobile -->
<div class="mobile">
    <div class="price_quote-request-view-pdf-mobile">
        <div class="page-wrapper container">
        <table style="width: 100%;">
            <tr>
                <td class="header-section" style="width: 50px;">
                    <div class="logo">
                        <img src="<?= $this->getViewFileUrl('images/logo-cho-truc-tuyen-short.png'); ?>"
                            alt="<?php echo $block->getLogoAlt() ?>"
                            />
                    </div>
                </td>
                <td class="header-section">
                    <?= $this->getLayout()
                        ->createBlock('Magento\Cms\Block\Block')
                        ->setBlockId('price-quote-print-header-right')
                        ->toHtml(); ?>
                </td>
            </tr>
        </table>
    <?php 
        $request = $block->getPriceQuoteRequest(); 
        $company_name = $request->getData('company_name');
        $company_address = $request->getData('company_address');
        $company_vat_number = $request->getData('company_vat_number');
        $contact_name = $request->getData('contact_name');
        $contact_phone_number = $request->getData('contact_phone_number');
        $contact_email = $request->getData('contact_email');
    ?>
    <table style="width: 100%; ">
        <tr>
        <td class="quote-title">
            <h1><?= __("Price Quote Table") ?></h1>
            <p><?= __("Date") ?>: <?= $block->getRequestDate() ?></p>
        </td>
        </tr>
    </table>
    <table class="greeting-first" style="width: 100%; ">
        <tr>
            <td style="width: 62px; white-space: nowrap;">
                <p><?= __("Dear") ?>:</p>
            </td>
            <td>
                <p><strong><?php echo $company_name; ?></strong> - <?php echo $company_vat_number; ?></p>
            </td>
        </tr>
        <tr>
            <td style="width: 62px;">
            </td>
            <td>
                <p><?php echo $company_address; ?></p>
                <?php if ($contact_name || $contact_phone_number || $contact_email) : ?>
                    <p><?= __("Contact/Price quote receiver info") ?></p>
                    <?php if ($contact_name) : ?>
                        <p> <?= __("Mr/Mrs") ?>&nbsp;<span class="contact-name"><?= $block->getContactName(); ?></span></p>
                    <?php endif; ?>
                        <p> 
                            <?= $contact_phone_number ? $contact_phone_number: ''; ?> <?= $contact_phone_number && $contact_email ? '<span class="sign-price-quote"> - </span>': ''; ?> <?= $contact_email ? '<span class="email-price-quote-contact">'.$contact_email.'</span>': ''; ?>
                        </p>
                <?php endif; ?>
            </td>
        </tr>
        <tr>
        <td colspan="2" class="greeting-section">
            <?= $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('price-quote-greeting')
                ->toHtml(); ?>
        </td>
        </tr>
    </table>
    </div><!-- ./page-header -->
        <div class="page-content" style="width: 100%;">
                <?php if(! $block->isRequestNotFound()){ //Request EXIST ?>
                    <?php
                    // Cart - items
                    if ($block->getItemsCount($requestId) > 0) {
                        $requestQuote = $priceQuoteHelper->getCollectionRequest($requestId);
                        $originalTotal = $requestQuote->getData('original_total');
                        $savingsAmount = $requestQuote->getData('savings_amount');
                        $discountAmount = $requestQuote->getData('discount_amount');
                        $shippingAmount = $requestQuote->getData('shipping_amount');
                        $couponcode = $requestQuote->getData('coupon_code');
                        $grandTotal = $requestQuote->getData('grand_total');
                        $flagShipping = $requestQuote->getData('flag_shipping');
                        $requestItems = $priceQuoteHelper->getCollectionItems($requestId);
                        $arrayMain = array();
                        $arrayMain = $priceQuoteHelper->getListPriceQuote($requestItems);
                        if(!empty($arrayMain) && count($arrayMain) > 0){
                    ?>
                        <table style="width: 100% !important;">
                            <tbody style="width: 100% !important;">
                                <?php foreach ($arrayMain as $item){ ?>
                                    <?php
                                        $product = $objectManager->create('Magento\Catalog\Model\Product')->load($item['product_id']);
                                        // guaranteeInfo
                                        $guaranteeInfo = $item['guarantee'] ? $item['guarantee']:'';
                                        // productunit
                                        $productunit = $item['product_unit'] ? $item['product_unit'] : '';
                                        // all rule
                                        // $ruleNames = $saleRuleFactory->create()->addFieldToFilter('rule_id', array('in' => json_decode($item['all_rule_ids'])) )->addFieldToSelect('name');
                                        $applied_rule_ids = $item['applied_rule_ids'];
                                        $parentrequestItemId = $item['id'];
                                        $itemId = $item['item_id'];
                                        $ruleNames = $priceQuoteHelper->getRulesNameWithPriceQuoteCTT($itemId,$requestId,$applied_rule_ids);
                                        // brand id
                                        $brandId = $item['product_brand_id'] ? $item['product_brand_id']: '';
                                        // $isPromoItem = $priceQuoteHelper->isPromoItem($itemId);
                                        
                                        $cartPromoOption = $item['cart_promo_option'];
                                        $isPromoItem = $priceQuoteHelper->isPromoItemCTT($cartPromoOption);
          
                                        $attributesOption = array();
                                        if(isset($item['product_options'])){
                                            $attributesOption = json_decode($item['product_options']);
                                        }
                                        // url and image
                                        $jacket = array();
                                        $productidOfconfigurable = $item['product_id'];
                                        if($attributesOption){
                                            $itemQuote = $objectManager->get('Magento\Quote\Model\ResourceModel\Quote\Item\CollectionFactory');
                                            $itemQuoteCollection = $itemQuote->create()->addFieldToFilter('parent_item_id',$item['item_id'])->addFieldToFilter('product_type','simple');
                                            $lastItemQuote = $itemQuoteCollection->getLastItem();
                                            $productidOfconfigurable = $lastItemQuote->getData('product_id');
                                        }
                                        $productTypeInstance = $objectManager->get('Magento\Catalog\Model\ResourceModel\Eav\Attribute');
                                        if ($attributesOption) {
                                            foreach ($attributesOption as $key => $attr) {
                                                $_attr = $productTypeInstance->load($key);
                                                $attributeCode = $_attr->getAttributeCode();
                                                $jacket[$attributeCode] = $attr;
                                            }
                                        }
                                        
                                        $getProductUrl = $product->getProductUrl();
                                        if ($jacket) {
                                            $getProductUrl = $getProductUrl . '#';
                                            foreach($jacket as $key => $value){
                                                $getProductUrl = $getProductUrl .$key. '='. $value .'&';
                                            }
                                            $getProductUrl = substr($getProductUrl, 0, -1);
                                        }
                                        $productImage = null;
                                        $productModel = $item['model'];
                                        if($productidOfconfigurable != $item['product_id']){
                                            $productResourceConfiguration = $objectManager->create('Magento\Catalog\Model\Product')->load($productidOfconfigurable);
                                            if(!$productModel){
                                                $productModel = $productResourceConfiguration->getData('model');
                                            }
                                            $productImage = $imageHelper->init($productResourceConfiguration, 'category_page_list')->getUrl();
                                        }else{
                                            $productImage = $imageHelper->init($product, 'category_page_list')->setImageFile($product->getImage())->getUrl();
                                        }
                                        
                                        if (!isset($productImage)) {
                                            $imageHelper = $objectManager->get(\Magento\Catalog\Helper\Image::class);
                                            $productImage = $imageHelper->getDefaultPlaceholderUrl('image');
                                        }
                                    ?>
                                    <div class="list-product-mobile">
                                        <tr>
                                            <td>
                                                <!-- name product -->
                                                <!-- <div class="product-item-details-mobile clearfix"> -->
                                                <?php if (!$isPromoItem) { ?>
                                                    <div class="product-item-details-mobile clearfix">
                                                        <span class="product-item-name">
                                                            <?php if ($priceQuoteHelper->hasProductUrl($product)) : ?>
                                                                <a href="<?= $block->escapeUrl($getProductUrl) ?>" title="<?= $block->escapeHtml($block->getProductName()) ?>">
                                                                    <?= $product->getNameLongHtml(); ?>
                                                                </a>
                                                            <?php else : ?>
                                                                <span><?= $product->getNameLongHtml(); ?></span>
                                                            <?php endif; ?>
                                                        </span>
                                                    </div>
                                                <?php } ?>
                                                <!-- Brand, Model -->
                                                    <?php
                                                        $productBrand = $productBrandHelper->getFirstBrandByProduct($product);
                                                        $model = $product->getData('model');
                                                        if ($productBrand || $model){
                                                    ?>
                                                        <div class="brand-model-mobile clearfix">
                                                            <?php 
                                                                    if ($productBrand ){
                                                            ?>
                                                                <div class="brand-name">
                                                                    <span><?php echo __('Brands: '); ?></span>
                                                                    <span class="name"><?php echo $productBrand->getName(); ?></span>
                                                                </div>
                                                            <?php } ?>
                                                            <?php if($model){ ?>
                                                                <div class="model-name">
                                                                    <span class="label"><?php echo __('Model: '); ?></span>
                                                                    <span class="name"><?php echo $model; ?></span>
                                                                </div>
                                                            <?php } ?>
                                                        </div>
                                                    <?php } ?>
                                                    <?php if (!$isPromoItem) { ?>
                                                        <!-- Guarantee -->
                                                        <?php if ($guaranteeInfo) { ?>
                                                            <div class="guarantee-info">
                                                                <span><?php echo __('Guarantee: '); ?></span>
                                                                <span class="name"><?php echo $guaranteeInfo; ?></span>
                                                            </div>
                                                        <?php } ?>
                                                        <!-- options -->
                                                        <?php if ($attributesOption) { ?>
                                                                    <p class="guarantee-info">
                                                                        <?php foreach($attributesOption as $key => $value): ?>
                                                                            <?php 
                                                                                $productTypeInstance = $objectManager->get('Magento\ConfigurableProduct\Model\Product\Type\Configurable');
                                                                                $productAttributeOptions = $productTypeInstance->getConfigurableAttributesAsArray($product);
                                                                                $labelOptions = '';
                                                                                $valueOptions = '';
                                                                                foreach ($productAttributeOptions as $key_o => $value_o) {
                                                                                    $tmp_option = $value_o['values'];
                                                                                    if(count($tmp_option) > 0)
                                                                                    {   
                                                                                        foreach ($tmp_option as $tmp) {
                                                                                            if($key_o == $key && $tmp['value_index'] == $value){
                                                                                                $labelOptions = $value_o['store_label'];
                                                                                                $valueOptions = $tmp['label'];
                                                                                                break;
                                                                                            }
                                                                                        }
                                                                                    }
                                                                                }
                                                                            ?>
                                                                            <span class="span-options-right"><?php echo $labelOptions; ?>: <?php echo $valueOptions; ?></span>
                                                                        <?php endforeach; ?>
                                                                    </p>
                                                                <?php } ?>
                                                    <?php } ?>
                                                    <!-- image -->
                                                    <div class="product-item-photo mobile-view">
                                                        <div class="img-box">
                                                            <?php if ($priceQuoteHelper->hasProductUrl($product)) : ?>
                                                                <a href="<?= $block->escapeUrl($priceQuoteHelper->getProductUrl($product)) ?>" title="<?= $block->escapeHtml($item['name']) ?>">
                                                                    <img src="<?= $productImage ?>" alt="<?= $block->escapeHtml($item['name']) ?>" />
                                                                </a>
                                                            <?php else : ?>
                                                                <img src="<?= $productImage ?>" alt="<?= $block->escapeHtml($item['name']) ?>" />
                                                            <?php endif ;?>
                                                        </div>
                                                    </div>
                                                    <?php if(!$isPromoItem){ ?>
                                                        <!-- box thông tin  -->
                                                        <div class="product-item-info">
                                                            <!-- Product Price mobile -->
                                                            <div class="product-price" style="padding: 0;">
                                                                <?= $block->escapeHtml(__('Qty')) ?>:&nbsp;<?= (int) $item['qty']  ?><?php if($productunit): ?> <?= $productunit;  ?><?php endif; ?>
                                                                <br>
                                                                <span class="price"><?= $block->formatPrice($item['price']);  ?></span>
                                                                    <?php
                                                                            $priceOriginal = $item['original_price'];
                                                                            $priceFinal = $item['price_incl_tax'];

                                                                            $savePercent = ($priceOriginal == 0) ? 0 : 100 - round(@($priceFinal / $priceOriginal) * 100);
                                                                            if ($savePercent != 0) {
                                                                            ?>
                                                                            <div class="order-save-price">
                                                                                <span class="save-percent">-<?= $savePercent; ?>%</span>
                                                                                <span class="price-original"><?= $block->formatPrice($priceOriginal); ?></span>
                                                                            </div>
                                                                    <?php } ?>
                                                            </div>
                                                            <!-- Sales Price -->
                                                            <div class="sales-price" style="padding: 0;">
                                                                <span class="d-inline-block d-sm-none">
                                                                    <?= $block->escapeHtml(__('Amount')) ?>:
                                                                </span>
                                                                <span class="price"><?= $block->formatPrice($item['row_total']);  ?></span>
                                                            </div>
                                                        
                                                        </div>
                                                    <?php }else{ ?>  
                                                        <?php
                                                            $itemId = $item['item_id'];
                                                            $lastItemOptions = $itemOptions->create()->addFieldToFilter('item_id', array('eq' => $itemId));
                                                            $lastItemOptions = $lastItemOptions->getLastItem();
                                                            $rulesId = '';
                                                            $nameRule = '';
                                                            if(isset($lastItemOptions['value'])){
                                                                $arrRulesId = json_decode($lastItemOptions['value'], true);
                                                                if(isset($arrRulesId["options"]) && isset($arrRulesId["options"]['ampromo_rule_id'])){
                                                                    $rulesId = $arrRulesId["options"]['ampromo_rule_id'];
                                                                }
                                                            }
                                                            if($rulesId){
                                                                $nameRule = $priceQuoteHelper->getRulesNameByIdRule($rulesId);
                                                            }
                                                            
                                                        ?>
                                                        <div class="product-item-info gift">
                                                            <div class="rules-name-mobile">
                                                                <?= $nameRule ? '<strong>'.$nameRule.'</strong>': ''; ?>
                                                                <br>
                                                                <?php if ($priceQuoteHelper->hasProductUrl($product)) : ?>
                                                                    <a href="<?= $block->escapeUrl($getProductUrl) ?>" title="<?= $block->escapeHtml($block->getProductName()) ?>">
                                                                        <?= $product->getName(); ?>
                                                                    </a>
                                                                <?php else : ?>
                                                                    <span><?= $product->getName(); ?></span>
                                                                <?php endif; ?>
                                                            </div>
                                                        </div>
                                                    <?php }?>  
                                                    <!-- end box  -->
                                                    <!-- Cart Rules -->
                                                    <?php if (!$isPromoItem) { ?>
                                                        <?php if ((!empty($ruleNames)) && (count($ruleNames) > 0)) { ?>
                                                            <div class="product-item-rule-mobile clearfix">
                                                                <div class="promotion-info">
                                                                    <ul class="rules-list">
                                                                        <?php foreach ($ruleNames as $key => $rules) { ?>
                                                                            <?php if(count($rules['sku']) > 0){ ?>
                                                                                <?php foreach($rules['sku'] as $index => $sku){ ?>
                                                                                    <?php 
                                                                                        $productData = $productRepository->loadByAttribute('sku',$sku);
                                                                                        if (!empty($productData)){
                                                                                            $productId = $productData->getId();
                                                                                            $nameproduct = $productData->getName();
                                                                                            $visibility = $priceQuoteHelper->hasProductUrl($productRepository->load($productId));
                                                                                            $urlProduct = $productData->getProductUrl();
                                                                                            $unitProduct = $rules['unit_product'][$index] ? ' '.$rules['unit_product'][$index]: '';
                                                                                            $qtyGift = $rules['qty'][$index] ? (int) $rules['qty'][$index] * (int) $item['qty']: '';
                                                                                            $resultString = '('.$qtyGift.$unitProduct.')';
                                                                                    ?>
                                                                                
                                                                                    <li>
                                                                                        <img class="img-gift" src="<?= $actual_link.'/pub/media/amasty/amoptimizer_dump/icon/icon_gift.png' ?>"/><strong><?php echo __('Gift: '); ?></strong><span class="span-product"><?php echo $nameproduct; ?> <?php echo $resultString; ?> </span>
                                                                                        <?php if($visibility){?>
                                                                                            <a class="see-more-rules" href= '<?php echo $urlProduct; ?>' title="<?= $nameproduct ?>">
                                                                                                <span class="span-load-more"><?= __('Load more details'); ?> &raquo;</span>
                                                                                            </a>
                                                                                        <?php }?>
                                                                                    </li>
                                                                        <?php }}}} ?>
                                                                    </ul>
                                                                </div>
                                                            </div>
                                                        <?php } ?>
                                                    <?php } ?>                 
                                            </td>
                                        </tr>
                                        </div>
                                <?php } ?>
                            </tbody>
                        </table>
                    <?php } ?>
                    <table style="width: 100% !important;">
                        <tbody style="width: 100% !important; padding: 15px 0 !important; ">
                            <tr>
                                <td>
                                    <p class="totals sub">
                                        <?= $block->escapeHtml(__('Original Total')) ?>:
                                    </p>
                                    <?php if ((int)$savingsAmount > 0): ?>
                                        <p class="totals">
                                            <?= $block->escapeHtml(__('Savings Amount')) ?>:
                                        </p>
                                    <?php endif ?>
                                    <?php if ((int)$discountAmount < 0) : ?>
                                        <p class="totals">
                                            <?= $block->escapeHtml(__('Discount Amount')) ?>:
                                        </p>
                                    <?php endif ?>
                                    <p class="totals shipping">
                                        <?= $block->escapeHtml(__('Shipping & Handling(temp)')) ?>:
                                    </p>
                                    <p class="totals grand" style="font-weight: bold">
                                        <?= $priceQuoteHelper->getCustomTitleGrandTotal($requestQuote) ?>:
                                    </p>
                                    <?php if($couponcode): ?>
                                        <p class="total-couponcode-mobile">
                                            <?= __('Discount code'); ?>:
                                        </p>
                                    <?php endif; ?>
                                </td>
                                <td style="text-align: right;">
                                    <p class="totals sub totals-mobile">
                                        <span class="amount" style="font-weight: 600;"><?= $block->formatPrice($originalTotal); ?></span>
                                    </p>
                                    <?php if ((int)$savingsAmount > 0): ?>
                                        <p class="totals totals-mobile">
                                        <span class="amount" style="color: #ff6000;"><?= $block->formatPrice($savingsAmount); ?></span>
                                        </p>
                                    <?php endif ?>
                                    <?php if ((int)$discountAmount < 0) : ?>
                                        <p class="totals totals-mobile">
                                                <?php 
                                                    $discountAmount = (string) $discountAmount;
                                                    $discountAmount = (int) substr($discountAmount, 1);
                                                ?>
                                            <span class="amount"><?= $block->formatPrice($discountAmount); ?></span>
                                        </p>
                                    <?php endif ?>
                                    <p class="totals shipping totals-mobile" >
                                        <span class="amount"><?= $priceQuoteHelper->getCustomShippingAmount($requestQuote); ?></span>
                                    </p>
                                    <p class="totals grand">
                                        <?= $block->formatPrice($grandTotal);  ?>
                                        <span class="vat-info"><?php echo __('Include VAT') ?></span>
                                    </p>  
                                    <?php if($couponcode): ?>   
                                        <p class="totals couponcode" style="font-weight: 600 !important;">
                                            <?= $couponcode;?>
                                        </p>  
                                    <?php endif; ?>     
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <table style="width: 100%; margin-left: -15px;">
                        <tr>
                        <td class="price-quote-note">
                            <?= $this->getLayout()
                                ->createBlock('Magento\Cms\Block\Block')
                                ->setBlockId('price-quote-note')
                                ->toHtml(); ?>
                        </td>
                        </tr>
                    </table>
                <?php
                    // Cart - empty
                    } else{
                ?>
            <div class="cart-empty">
                    <p>
                        <i class="fa fa-cart-plus cart-icon"></i>
                    </p>
                    <p>
                        <?= $block->escapeHtml(__('Shopping cart is empty')) ?>
                    </p>
                    <p>
                        <a href="<?= $block->escapeUrl($block->getContinueShoppingUrl()); ?>"
                            title="<?= $block->escapeHtml(__('Continue shopping')); ?>"
                            class="btn btn-primary btn-continue-shopping">
                            <?= $block->escapeHtml(__('Continue shopping')); ?>
                        </a>
                    </p>
            </div>
                <?php
                }
                ?>
                <?php }else{ // Request NOT FOUND ?>
                    <div class="page-title text-center mt-3">
                        <h3><?= __("Price Quote Not Found") ?></h3>
                    </div>
                <?php } ?>
        </div><!-- .page-content -->
    </div>
</div>