<?php
/**
 * PriceQuote Request View template
 *
 * @var $block \Magento\PriceQuote\Block\Request\View
 */


$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$reviewFactory = $objectManager->create('Magento\Review\Model\Review');
$storeId = $storeManager->getStore()->getId();
$saleRuleFactory = $objectManager->create('Magento\SalesRule\Model\ResourceModel\Rule\CollectionFactory');
$imageHelper = $this->helper('Magento\Catalog\Helper\Image');
$productBrandHelper = $this->helper('Ves\Brand\Helper\ProductBrand');
$amPromoHelper = $this->helper('Amasty\Promo\Helper\Item');
$priceQuoteHelper = $this->helper('Chottvn\PriceQuote\Helper\Data');
$detectMobile = $objectManager->get('\Chottvn\Frontend\Helper\DetectMobile');
$blockRules = $block->getLayout()->createBlock('Chottvn\Frontend\Block\Rules');
$priceQuoteRequest = $block->getPriceQuoteRequest();
$requestId = $priceQuoteRequest->getData('request_id');
$messages_prefix = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('ampromo/messages/prefix');
$productRepository = $objectManager->get('\Magento\Catalog\Model\Product');
$itemOptions = $objectManager->get('Magento\Quote\Model\ResourceModel\Quote\Item\Option\CollectionFactory');
?>

<style type="text/css">
    	*{
    		font-family: "Arial", "DejaVu Sans", Helvetica, "Times New Roman", serif;
    	}
    	.price_quote-request-view-pdf{
  			background-image: url("<?=$this->getViewFileUrl('images/logo-cho-truc-tuyen-watermark-3.png'); ?>") !important;
  			background-repeat: no-repeat !important;
  	    background-size: 50% auto !important;
  	    background-position: center !important;
  	    -webkit-print-color-adjust: exact;
  		}
  		@media print {
    		* {
    		    -webkit-print-color-adjust: exact !important; /*Chrome, Safari */
    		    color-adjust: exact !important;  /*Firefox*/
    		  }
  		}
    </style>
<style  type="text/css">
        /*Bootstrap*/
        .clearfix:after {
            content: "";
            display: table;
            clear: both;
        }
        .float-right {
            float: right !important;
        }
        .text-right{
        	text-align: right;
        }
        .text-left{
        	text-align: left;
        }
        .text-center{
            text-align: center;
        }
        .text-uppercase {
            text-transform: uppercase !important;
        }

        /*FontAwesome*/
        @font-face {
          font-family: "FontAwesomeRegular";
          font-weight: normal;
          font-style : normal;
                 src : url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/webfonts/fa-regular-400.ttf") format("truetype");
        }
        @font-face {
          font-family: "FontAwesomeBrands";
          font-weight: normal;
          font-style : normal;
                 src : url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/webfonts/fa-brands-400.ttf") format("truetype");
        }
        @font-face {
          font-family: "FontAwesomeSolid";
          font-weight: bold;
          font-style : normal;
                 src : url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/webfonts/fa-solid-900.ttf") format("truetype");
        }
        .fas{
            font-weight: bold !important;
             font-family: FontAwesomeSolid !important;
        }
        .fas:before{
            font-weight: bold !important;
            font-family: FontAwesomeSolid !important;
        }
        .fab{
            font-weight: normal !important;
             font-family: FontAwesomeBrands !important;
        }
        .fab:before{
             font-weight: normal !important;
            font-family: FontAwesomeBrands !important;
        }
        .far{
            font-weight: normal !important;
             font-family: FontAwesomeRegular !important;
        }
        .far:before{
             font-weight: normal !important;
            font-family: FontAwesomeRegular !important;
        }



        /*Page CSS*/
        .price_quote-request-view-pdf {
          background-color: #ffffff !important;
        }
        /* .price_quote-request-view-pdf table,
        .price_quote-request-view-pdf tr,
        .price_quote-request-view-pdf td {
          font-size: 13px;
          padding: 0px;
          margin: 0px;
          line-height: 18px;
        } */
        .price_quote-request-view-pdf p {
          font-size: 14px;
          padding: 0px;
          margin: 0px;
          line-height: 18px;
        }
        .price_quote-request-view-pdf .header-section {
          font-size: 14px !important;
          padding: 0px !important;
          margin: 0px !important;
          line-height: 16px !important;
        }
        .price_quote-request-view-pdf .header-section .logo img {
            max-height: 70px!important;
            margin-left: -15px !important;
        }
        .price_quote-request-view-pdf .header-section p {
          font-size: 14px !important;
          padding: 0px !important;
          margin: 0px !important;
          line-height: 20px !important;
        }
        .price_quote-request-view-pdf .header-section .text-uppercase {
          text-transform: uppercase !important;
          font-weight: bold !important;
          padding: 15px 0px 2px 0px !important;
        }
        .price_quote-request-view-pdf .quote-title {
          text-align: center !important;
        }
        .price_quote-request-view-pdf .quote-title h1 {
          font-size: 28px !important;
          text-transform: uppercase !important;
          font-weight: bold !important;
          padding: 40px 0px 0px 0px !important;
          margin: 0px !important;
        }
        .price_quote-request-view-pdf .quote-title p {
          font-size: 14px !important;
          padding: 10px 0px 20px 0px;
          margin: 0px;
        }

        .price_quote-request-view-pdf .quote-table thead th {
          padding-bottom: 15px;
          margin: 0;
          font-size: 14px;
          font-weight: bold;
          border-bottom: solid 1px #f5f5f5;
        }
        .price_quote-request-view-pdf .quote-table tbody tr td {
         
          font-size: 14px;
          /* padding: 5px; */
          vertical-align: top;
        }
        .price_quote-request-view-pdf .item-body .product-item-photo {
          padding-right: 15px;
        }
        .price_quote-request-view-pdf .item-body .product-item-photo img {
          max-width: 120px;
          margin: 0px;
          padding: 0px;
        }

        .price_quote-request-view-pdf .item-body .product-item-name {
          font-size: 14px;
          color: #000 !important;
          line-height: 20px;
          padding-bottom: 5px;
        }

        .price_quote-request-view-pdf .item-body .product-item-name strong {
          font-weight: bold;
        }

        .price_quote-request-view-pdf .item-body .brand-name{
          font-size: 14px!important;
          color: #3e3e3e!important;
          line-height: 20px !important;
          padding-bottom: 5px!important;
          padding-right: 15px!important;
          width: 40%;
          display: inline !important;
        }
        .price_quote-request-view-pdf .item-body .model-name {
          font-size: 14px !important;
          color: #3e3e3e!important;
          line-height: 20px !important;
          padding-bottom: 5px!important;
          width: 60%;
          display: inline !important; 
        }
        .price_quote-request-view-pdf .item-body .rating-summary  {
          padding-bottom: 0 0 5px 0;
          margin: 0px;
          line-height: 16px!important;
        }
        .price_quote-request-view-pdf .item-body .rating-summary .rating-result{
          font-size: 11px;
          /* display: inline-block; */
          color: #707070;
        }
        .price_quote-request-view-pdf .item-body .rating-summary i {
          font-size: 11px!important;
          line-height: 16px!important;
          display: inline-block;
        }
        .price_quote-request-view-pdf .item-body .rating-summary .rating-result .star.solid{
          color: #ffce00;
        }
        .price_quote-request-view-pdf .item-body .rating-summary .rating-label {
          color: #707070;
          padding-left: 5px;
          font-size: 11px!important;
          line-height: 20px!important;
        }

        .price_quote-request-view-pdf .item-body .rules-list{
          list-style: none;
          padding-inline-start: 0 !important;
          margin: 0;
          padding: 0 0 5px 0;
        }
        .price_quote-request-view-pdf .item-body .rules-list li {
          font-size: 12px;
          color: #3e3e3e;
          line-height: 20px;
        }
        .price_quote-request-view-pdf .item-body .rules-list li i {
          font-size: 15px;
          color: #ef0000;
          line-height: 16px;
          /* display: inline-block; */
        }
        .price_quote-request-view-pdf .item-body .rules-list li span {
          font-size: 13px;
          color: #3e3e3e;
          line-height: 18px;
        }
        
        .price_quote-request-view-pdf .item-body .message-gift {
          margin: 10px 0 0 0;
          display: inline-block;
          color: #fff !important;
          background: #ef0000 !important;
          font-size: 12px;
          padding: 1px 8px;
          border-radius: 8px;
          -moz-border-radius: 8px;
          -webkit-border-radius: 8px;
          line-height: 16px;
        }
        .price_quote-request-view-pdf .item-body .message-gift i,
        .price_quote-request-view-pdf .item-body .message-gift span {
          display: inline-block;
          line-height: 20px;
        }

        .price_quote-request-view-pdf .item-body .product-price {
          padding: 0px;
          text-align: right;
          line-height: 20px;
        }

        .price_quote-request-view-pdf .item-body .product-price .order-quantity {
          font-size: 14px;
          color: #000;
          line-height: 20px;
        }
        .price_quote-request-view-pdf .item-body .product-price .order-price {
          font-size: 14px;
          color: #000;
          line-height: 20px;
        }
        .price_quote-request-view-pdf .item-body .product-price .order-save-price {
          line-height: 16px;
          font-size: 14px;
          color: #707070;
          display: inline-block;
        }
        
        .price_quote-request-view-pdf .item-body .product-price .order-save-price .price-original {
          text-decoration: line-through;
          font-size: 14px;
          margin: -10px 0 0 10px;
          font-weight: 400;
        }
        .price_quote-request-view-pdf .item-body .product-price .order-save-price .price-original .price {
          font-size: 14px;
          color: #707070;
        }
        .save-percent {
          font-size: 10px;
          margin: -1px 0 0 0;
          padding: 2px 4px;
          border-radius: 6px;
          -moz-border-radius: 6px;
          -webkit-border-radius: 6px;
          font-weight: 400 !important;
          vertical-align: middle;
          color: #ffffff !important;
          display: inline-block !important;
          line-height: 12px;
          background: #ff6000 !important;
        }
        td.item-body {
            padding: 15px 0px;
            border-top: unset;
            border-bottom: solid 1px #f5f5f5;
        }
        .price_quote-request-view-pdf .item-body .sales-price {
          padding: 0px 5px;
          text-align: right;
        }
        .price_quote-request-view-pdf .item-body .sales-price .price {
          font-size: 14px;
          font-weight: bold;
          color: #000;
          line-height: 24px;
        }
        .price_quote-request-view-pdf .quote-table tfoot tr {
          font-size: 14px;
        }
        .price_quote-request-view-pdf .quote-table tfoot tr td {
          vertical-align: top;
          padding: 0 !important;
          margin: 0 !important;
        }
        .price_quote-request-view-pdf .quote-table tfoot tr td p {
          font-size: 14px;
          line-height: 20px;
        }
        .price_quote-request-view-pdf .quote-table tfoot tr td p .amount {
          font-weight: bold;
          text-align: right;
        }
        .price_quote-request-view-pdf .quote-table .totals{
          padding: 0 0 10px 0;
          margin: 0px !important;
        }
        .price_quote-request-view-pdf .quote-table .totals.grand {
          margin-top: 15px;
          border-top: solid 1px #f5f5f5;
          font-weight: 600;
        }
        .grand-total .price{
          font-size: 14px;
          font-weight: 700;
          color: #ff6000 !important;
          text-align: right;
          display: block;
        }
        .price-quote-note {
          font-size: 13px;
          color: #3e3e3e;
          line-height: 18px;
        }

        .price-quote-note {
          font-size: 13px;
          color: #3e3e3e;
          line-height: 18px;
          padding-top: 15px;
        }

        .price-quote-note p {
          margin: 0;
          padding: 0;
          line-height: 20px;
        }
        .savings .price{
          color: #ff6000 !important;
        }
        .price-quote-note ul {
          list-style: none;
          padding-inline-start: 0 !important;
          margin: 0;
          padding: 0;
        }
        .price-quote-note ul li {
          line-height: 20px;
          font-size: 13px;
          color: #3e3e3e;
        }
        .price_quote-request-view-pdf{
          padding: 0 !important;
          margin: 0 !important;
        }
        .quote-request-view-pdf .cart-empty {
          padding: 0 10px;
          text-align: center;
        }
        .price_quote-request-view-pdf .cart-empty .cart-icon {
          color: #707070;
          font-size: 70px;
        }
        .price_quote-request-view-pdf .cart-empty .btn-continue-shopping {
          color: #ffffff;
          border-color: #00409d;
          background-color: #00409d;
        }
        .sub{
          padding: 10px 0 !important;
        }
       
        .price_quote-request-view-pdf .cart-empty-sub {
          padding: 0 10px;
        }
        .totals.grand {
            font-weight: 600;
            padding: 15px 0 !important;
        }
        .totals .vat-info {
            font-style: italic;
            font-weight: 400 !important;
            font-size: 12px;
            color: #707070;
            display: block;
        }
        /* .price_quote-request-view-pdf .greeting-first{
          padding: 0px !important;
          margin: 0px !important;
        } */
        .price_quote-request-view-pdf .greeting-first tr > td {
            padding: 0px !important;
            margin: 0px !important;
        }
        .price_quote-request-view-pdf .greeting-first tr > td p{
            margin-bottom: 5px !important;
            margin-left: -15px !important;
        }
        .fas.fa-gift{
            font-size: 15px;
            color: #ef0000 !important;
        }
        .box-noti-gift {
            height: 100%;
            padding: 10px 15px;
            line-height: 20px;
            background-color: #fff7e3 !important;
        }
        .rules-list i {
            padding-right: 10px !important;
        }
        .span-product {
            padding-right: 10px !important;
        }
        .product-item-name span{
          display: block;
        }   
}
</style>
<div class="price_quote-request-view-pdf">
    <div class="page-wrapper container">
      <table style="width: 100%;">
          <tr>
              <td class="header-section" style="width: 63%;">
                  <div class="logo">
                  <img src="<?= $block->getViewFileUrl('images/logo-cho-truc-tuyen-desktop.png');  ?>"
                      alt="<?php echo $block->getLogoAlt() ?>"
                          <?php echo $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
                          <?php echo $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
                      />
                      </div>
              </td>
              <td class="header-section" style="width: 37%;">
                  <?= $this->getLayout()
                      ->createBlock('Magento\Cms\Block\Block')
                      ->setBlockId('price-quote-print-header-right')
                      ->toHtml(); ?>
              </td>
          </tr>
      </table>
  <?php 
    $request = $block->getPriceQuoteRequest(); 
    $company_name = $request->getData('company_name');
    $company_address = $request->getData('company_address');
    $company_vat_number = $request->getData('company_vat_number');
    $contact_name = $request->getData('contact_name');
    $contact_phone_number = $request->getData('contact_phone_number');
    $contact_email = $request->getData('contact_email');
  ?>
  <table style="width: 100%; ">
    <tr>
      <td class="quote-title">
        <h1><?= __("Price Quote Table") ?></h1>
        <p><?= __("Date") ?>: <?= $block->getRequestDate() ?></p>
      </td>
    </tr>
  </table>
  <table class="greeting-first" style="width: 100%; ">
    <tr>
      <td class="greeting-section" style="width: 62px; white-space: nowrap;">
        <p><?= __("Dear") ?>:</p>
      </td>
      <td class="greeting-section">
        <p><strong><?php echo $company_name; ?></strong> - <?php echo $company_vat_number; ?></p>
      </td>
    </tr>
    <tr>
      <td class="greeting-section" style="width: 62px;">
      </td>
      <td class="greeting-section">
        <p><?php echo $company_address; ?></p>
        <?php if ($contact_name || $contact_phone_number || $contact_email) : ?>
            <p><?= __("Contact/Price quote receiver info") ?></p>
            <?php if ($contact_name) : ?>
                <p> <?= __("Mr/Mrs") ?>&nbsp;<span class="contact-name"><?= $block->getContactName(); ?></span></p>
            <?php endif; ?>
                <p> 
                    <?= $contact_phone_number ? $contact_phone_number: ''; ?> <?= $contact_phone_number && $contact_email ? '-': ''; ?> <?= $contact_email ? $contact_email: ''; ?>
                </p>
        <?php endif; ?>
      </td>
    </tr>
    <tr>
      <td colspan="2" class="greeting-section">
  		<?= $this->getLayout()
  	        ->createBlock('Magento\Cms\Block\Block')
  	        ->setBlockId('price-quote-greeting')
  	        ->toHtml(); ?>
      </td>
    </tr>
  </table>
</div><!-- ./page-header -->
    <div class="page-content" style="width: 100%;">
            <?php if(! $block->isRequestNotFound()){ //Request EXIST ?>
                    <?php
                    // Cart - items
                    if ($block->getItemsCount($requestId) > 0) {
                      $requestQuote = $priceQuoteHelper->getCollectionRequest($requestId);
                      $originalTotal = $requestQuote->getData('original_total');
                      $savingsAmount = $requestQuote->getData('savings_amount');
                      $discountAmount = $requestQuote->getData('discount_amount');
                      $shippingAmount = $requestQuote->getData('shipping_amount');
                      $couponcode = $requestQuote->getData('coupon_code');
                      $grandTotal = $requestQuote->getData('grand_total');
                      $flagShipping = $requestQuote->getData('flag_shipping');
                      $requestItems = $priceQuoteHelper->getCollectionItems($requestId);
                      $arrayMain = array();
                      $arrayMain = $priceQuoteHelper->getListPriceQuote($requestItems);
                      $isReviewProduct = false;
                      if(!empty($arrayMain) && count($arrayMain) > 0){ 
                    ?>
                      <table class="quote-table" style="width: 100%;">
                          <tr style="border-bottom: solid 1px #f5f5f5 !important;">
                              <th colspan="2" style="text-align: left; white-space: nowrap;padding: 15px 15px 15px 0px;">
                              <?= $block->escapeHtml(__('Product information')) ?>
                              </th>
                              <th style="min-width: 170px; text-align: right; white-space: nowrap;padding: 15px 0;">
                              <?= $block->escapeHtml(__('Quantity x Price')) ?>
                              </th>
                              <th style="min-width: 120px; text-align: right; white-space: nowrap;padding: 15px 0px 15px 15px;">
                              <?= $block->escapeHtml(__('Amount')) ?>
                              </th>
                          </tr>
                          <tbody class="cart-items">
                          <?php foreach ($arrayMain as $item) :?>
                            <?php
                              $product = $objectManager->create('Magento\Catalog\Model\Product')->load($item['product_id']);
                              // guaranteeInfo
                              $guaranteeInfo = $item['guarantee'] ? $item['guarantee']:'';
                              
                              // productunit
                              $productunit = $item['product_unit'] ? $item['product_unit'] : '';
                              // all rule
                              // $ruleNames = $saleRuleFactory->create()->addFieldToFilter('rule_id', array('in' => json_decode($item['all_rule_ids'])) )->addFieldToSelect('name');
                              $applied_rule_ids = $item['applied_rule_ids'];
                              $parentrequestItemId = $item['id'];
                              $itemId = $item['item_id'];
                              $ruleNames = $priceQuoteHelper->getRulesNameWithPriceQuoteCTT($itemId,$requestId,$applied_rule_ids);
                              // brand id
                              $brandId = $item['product_brand_id'] ? $item['product_brand_id']: '';
                              $imageHelper = $objectManager->get(\Magento\Catalog\Helper\Image::class);
                              if($product){
                                  $productImage = $imageHelper->init($product, 'cart_page_product_thumbnail')->getUrl();
                              }else{
                                  $productImage = $imageHelper->getDefaultPlaceholderUrl('image');
                              }

                              // $isPromoItem = $priceQuoteHelper->isPromoItem($itemId);
                              $cartPromoOption = $item['cart_promo_option'];
                              $isPromoItem = $priceQuoteHelper->isPromoItemCTT($cartPromoOption);

                              $attributesOption = array();
                              if(isset($item['product_options'])){
                                  $attributesOption = json_decode($item['product_options']);
                              }
                            // url and image
                            $productidOfconfigurable = $item['product_id'];
                            if($attributesOption){
                                $itemQuote = $objectManager->get('Magento\Quote\Model\ResourceModel\Quote\Item\CollectionFactory');
                                $itemQuoteCollection = $itemQuote->create()->addFieldToFilter('parent_item_id',$item['item_id'])->addFieldToFilter('product_type','simple');
                                $lastItemQuote = $itemQuoteCollection->getLastItem();
                                $productidOfconfigurable = $lastItemQuote->getData('product_id');
                            }
                            $productTypeInstance = $objectManager->get('Magento\Catalog\Model\ResourceModel\Eav\Attribute');
                            if ($attributesOption) {
                                foreach ($attributesOption as $key => $attr) {
                                    $_attr = $productTypeInstance->load($key);
                                    $attributeCode = $_attr->getAttributeCode();
                                    $jacket[$attributeCode] = $attr;
                                }
                            }
                            $productModel = $item['model'];
                            if($productidOfconfigurable != $item['product_id']){
                                $productResourceConfiguration = $objectManager->create('Magento\Catalog\Model\Product')->load($productidOfconfigurable);
                                if(!$productModel){
                                  $productModel = $productResourceConfiguration->getData('model');
                                }
                                $productImage = $imageHelper->init($productResourceConfiguration, 'product_page_image_thumbnail')->setImageFile($productResourceConfiguration->getImage())->getUrl();
                            }else{
                                $productImage = $imageHelper->init($product, 'product_page_image_thumbnail')->setImageFile($product->getImage())->getUrl();
                            }
                            if (isset($productImage) && !($priceQuoteHelper->url_exists($productImage))) {
                              $productImage = $imageHelper->getDefaultPlaceholderUrl('thumbnail');
                            }
                            if (!isset($productImage)) {
                                $productImage = $imageHelper->getDefaultPlaceholderUrl('thumbnail');
                            }
                          ?>
                          <tr class="cart-item-body">
                              <td class="item-body" style="width: 130px;">
                              <div class="product-item-photo">
                                  <div class="img-box">
                                      <img src="<?=$productImage?>" alt="<?= $block->escapeHtml($item['name']) ?>" />
                                  </div>
                              </div>
                              </td>
                              <td class="item-body">
                              <p class="product-item-name">
                                <?php
                                      $itemId = $item->getData('item_id');
                                      $lastItemOptions = $itemOptions->create()->addFieldToFilter('item_id', array('eq' => $itemId));
                                      $lastItemOptions = $lastItemOptions->getLastItem();
                                      $rulesId = ''; $nameRule = '';
                                      if(isset($lastItemOptions['value'])){
                                          $arrRulesId = json_decode($lastItemOptions['value'], true);
                                          if(isset($arrRulesId["options"]) && isset($arrRulesId["options"]['ampromo_rule_id'])){
                                              $rulesId = $arrRulesId["options"]['ampromo_rule_id'];
                                          }
                                      }
                                      if($rulesId){
                                          $nameRule = $priceQuoteHelper->getRulesNameByIdRule($rulesId);
                                      }
                                  ?>
                                  <?php if($isPromoItem){ ?>
                                      <!-- Rule Name -->
                                      <?= $nameRule ? '<strong>'.$nameRule.'</strong>': ''; ?>
                                      <!-- Name Product -->
                                      <span><?= $product->getName(); ?></span>
                                  <?php }else{ ?>
                                      <?= $product->getNameLongHtml(); ?>
                                  <?php } ?>
                              </p>
                              <?php
                              $productBrand = $productBrandHelper->getBrandById($brandId);
                                  if ($productBrand ){
                              ?>
                              <p class="brand-name">
                                  <span><?php echo __('Brands: '); ?></span>
                                  <span class="name"><?php echo $productBrand->getName(); ?></span>
                              </p>
                              <?php } ?>
                              <?php
                                
                                  if ($productModel) {
                              ?>
                              <p class="model-name">
                                  <span><?php echo __('Model: '); ?></span>
                                  <span class="name"><?php echo $productModel; ?></span>
                              </p>
                              <?php } ?>

                              <?php if (!$isPromoItem) { ?>
                                <!-- Reviews -->
                                  <?php  if (false && $ratingSummary) { ?>
                                  <p class="rating-summary">
                                      <span class="rating-result" title="<?= $block->escapeHtmlAttr($ratingSummary); ?>%">
                                      <?php
                                      for ($x = 0; $x < $starSolid; $x++) {
                                          echo "<i class='fas fa-star star solid'></i>";
                                      }
                                      for ($x = 0; $x < $starTransparent; $x++) {
                                          echo "<i class='fas fa-star star'></i>";
                                      }
                                      ?>
                                      </span>
                                      <span class="rating-label">
                                      <?php if ($ratingCount == 0) {
                                      echo __('No review on product');
                                      } else {
                                      echo __('Have %1 reviews', $ratingCount);
                                      }
                                      ?>
                                      </span>
                                  </p>
                                  <?php } ?>
                                  <!-- Guarantee -->
                                  <?php if ($guaranteeInfo) { ?>
                                  <p class="guarantee-info">
                                      <span><?php echo __('Guarantee: '); ?></span>
                                      <span class="name"><?php echo $guaranteeInfo; ?></span>
                                  </p>
                                  <?php } ?>
                                  <!-- Options -->
                                  <?php if ($attributesOption) { ?>
                                    <p class="guarantee-info">
                                        <?php foreach($attributesOption as $key => $value): ?>
                                            <?php 
                                                $productTypeInstance = $objectManager->get('Magento\ConfigurableProduct\Model\Product\Type\Configurable');
                                                $productAttributeOptions = $productTypeInstance->getConfigurableAttributesAsArray($product);
                                                $labelOptions = '';
                                                $valueOptions = '';
                                                foreach ($productAttributeOptions as $key_o => $value_o) {
                                                    $tmp_option = $value_o['values'];
                                                    if(count($tmp_option) > 0)
                                                    {   
                                                        foreach ($tmp_option as $tmp) {
                                                            if($key_o == $key && $tmp['value_index'] == $value){
                                                                $labelOptions = $value_o['store_label'];
                                                                $valueOptions = $tmp['label'];
                                                                break;
                                                            }
                                                        }
                                                    }
                                                }
                                            ?>
                                              <span class="span-options-right"><?php echo $labelOptions; ?>: <?php echo $valueOptions; ?></span>
                                        <?php endforeach; ?>
                                    </p>
                                  <?php } ?>
                                  <!-- Cart Rules -->
                                  <?php if (!$isPromoItem) { ?>
                                      <?php if ((!empty($ruleNames)) && (count($ruleNames) > 0)) { ?>
                                        <div class="promotion-info">
                                            <ul class="rules-list">
                                                <?php foreach ($ruleNames as $key => $rules) { ?>
                                                    <?php if(count($rules['sku']) > 0){ ?>
                                                        <?php foreach($rules['sku'] as $index => $sku){ ?>
                                                            <?php 
                                                                $productData = $productRepository->loadByAttribute('sku',$sku);
                                                                if (!empty($productData)){
                                                                    $productId = $productData->getId();
                                                                    $nameproduct = $productData->getName();
                                                                    $unitProduct = $rules['unit_product'][$index] ? ' '.$rules['unit_product'][$index]: '';
                                                                    $qtyGift = $rules['qty'][$index] ? (int) $rules['qty'][$index] * (int) $item['qty']: '';
                                                                    $resultString = '('.$qtyGift.$unitProduct.')';
                                                            ?>
                                                            <li>
                                                                <i class="fas fa-gift text-danger"></i><strong><?php echo __('Gift: '); ?></strong><span class="span-product"><?php echo $nameproduct; ?> <?php echo $resultString; ?> </span>
                                                            </li>
                                                <?php }}}} ?>
                                            </ul>
                                        </div>
                                    <?php } ?>
                                  <?php } ?>
                                  <?php if(false && $isPromoItem){ ?>
                                  <div class="message-gift">
                                      <i class="fas fa-gift"></i> <span><?= $item['message']; ?></span>
                                  </div>
                                  <?php } ?>
                                <?php } ?>
                              </td>
                                <td class="item-body" style="text-align: right;">
                                  <?php if (!$isPromoItem) { ?>
                                    <div class="product-price">
                                        <p class="order-quantity"><?= (int) $item['qty'];  ?><?php if($productunit): ?> <?= $productunit;  ?><?php endif; ?></span></p>
                                      </p>
                                        <p class="order-price"><?= $block->formatPrice($item['price']);  ?></p>
                                        <?php
                                            $priceOriginal = $item['original_price'];
                                            $priceFinal = $item['price_incl_tax'];
                                            if ($priceFinal < $priceOriginal) {
                                                $savePercent = 100 - round(@($priceFinal / $priceOriginal ) * 100);
                                            } else {
                                                $savePercent = 0;
                                            }
                                            //$savePercent = ($priceOriginal == 0) ? 0 : 100 - round(@($priceFinal / $priceOriginal ) * 100);
                                            if ($savePercent != 0) {
                                        ?>
                                        <p class="order-save-price">
                                            <span class="save-percent">-<?= $savePercent; ?>%</span>
                                            <span class="price-original"><?= $block->formatPrice($priceOriginal); ?></span>
                                        </p>
                                    <?php } ?>
                                    </div>
                                  <?php } ?>
                                </td>
                                <td class="item-body" style="width: 140px;text-alight: right">
                                  <?php if (!$isPromoItem) { ?>
                                    <div class="sales-price" style="text-alight: right;padding:0">
                                        <?= $block->formatPrice($item['row_total']);  ?>
                                    </div>
                                  <?php } ?>
                                </td>
                          </tr><!-- /.cart-item-body -->
                          <?php endforeach ?>
                          </tbody>
                      </table>
                      <table class="quote-table" style="width: 100%;">
                        <tr>
                          <td style="width: 68%;"></td>
                          <td tyle="width: 32%;">
                            <p class="totals sub">
                                <?= $block->escapeHtml(__('Original Total')) ?>:
                            </p>
                            <?php if ((int)$savingsAmount > 0): ?>
                                <p class="totals">
                                <?= $block->escapeHtml(__('Savings Amount')) ?>:
                                </p>
                            <?php endif ?>
                            <?php if ((int)$discountAmount < 0): ?>
                                <p class="totals">
                                <?= $block->escapeHtml(__('Discount Amount')) ?>:
                                </p>
                            <?php endif ?>
                            <p class="totals shipping">
                                <?= $block->escapeHtml(__('Shipping & Handling(temp)')) ?>:
                            </p>
                            <p class="totals grand" style="font-weight: bold">
                              <?= $priceQuoteHelper->getCustomTitleGrandTotal($requestQuote) ?>:
                            </p>
                            <?php if($couponcode): ?>
                              <p class="totals couponcode" style="margin-top: 18px !important;">
                                  <?= __('Discount code'); ?>:
                              </p>
                            <?php endif; ?>
                          </td>
                          <td style="text-align: right;">
                            <p class="totals sub">
                                <span class="amount" style="font-weight: 600 !important;"><?= $block->formatPrice($originalTotal); ?></span>
                            </p>
                            <?php if ((int)$savingsAmount > 0): ?>
                                <p class="totals">
                                  <span class="amount savings" style="font-weight: 600 !important; color: #ff6000 !important;"><?= $block->formatPrice($savingsAmount); ?></span>
                                </p>
                            <?php endif ?>
                            <?php if ((int)$discountAmount < 0): ?>
                                <p class="totals">
                                <span class="amount" style="font-weight: 600 !important;">
                                  <?php 
                                      $discountAmount = (string) $discountAmount;
                                      $discountAmount = (int) substr($discountAmount, 1);
                                  ?>
                                  <?= $block->formatPrice($discountAmount); ?>
                              </span>
                                </p>
                            <?php endif ?>
                            <p class="totals shipping">
                                <span class="amount" style="font-weight: 600 !important;"><?= $priceQuoteHelper->getCustomShippingAmount($requestQuote); ?></span>
                            </p>
                            <p class="totals grand">
                                <span class="grand-total"><?= $block->formatPrice($grandTotal);?></span>
                                <span class="vat-info"><?php echo __('Include VAT') ?></span>
                            </p>
                            <?php if($couponcode): ?>
                              <p class="totals couponcode" style="font-weight: 600 !important;">
                                  <?= $couponcode;?>
                              </p>
                            <?php endif ?>
                          </td>
                        </tr>
                      </table>
                    <?php } ?>
                    <table style="width: 100%; margin-left: -15px;">
                        <tr>
                        <td class="price-quote-note">
                            <?= $this->getLayout()
                                ->createBlock('Magento\Cms\Block\Block')
                                ->setBlockId('price-quote-note')
                                ->toHtml(); ?>
                        </td>
                        </tr>
                    </table>
        <?php
            // Cart - empty
            } else{
        ?>
        <div class="cart-empty">
                <p>
                    <i class="fa fa-cart-plus cart-icon"></i>
                </p>
                <p>
                    <?= $block->escapeHtml(__('Shopping cart is empty')) ?>
                </p>
                <p>
                    <a href="<?= $block->escapeUrl($block->getContinueShoppingUrl()); ?>"
                        title="<?= $block->escapeHtml(__('Continue shopping')); ?>"
                        class="btn btn-primary btn-continue-shopping">
                        <?= $block->escapeHtml(__('Continue shopping')); ?>
                    </a>
                </p>
        </div>
            <?php
            }
            ?>
            <?php }else{ // Request NOT FOUND ?>
                <div class="page-title text-center mt-3">
                    <h3><?= __("Price Quote Not Found") ?></h3>
                </div>
            <?php } ?>
    </div><!-- .page-content -->
</div>