<link href="dist/css/bootstrap.min.css" rel="stylesheet">
<link href="maintenance.css" rel="stylesheet">
<div class="container py-3">
    <!-- For demo purpose-->
    <header class="text-center">
        <h1 class="display-4 mb-0">
          <img src="images/logo_chottvn_color.png" width="210" height="74.11">
        </h1>
        <h3 class="display-4 mb-0">
          <span style="font-weight: bold;font-size: 25px;color: #dbaf00;">BẢO TRÌ HỆ THỐNG</span>
        </h3>
    </header>
    <div class="py-3">
        <div class="row">
            <div class="col-lg-8 mx-auto">

                <p class="text-left">Website chotructuyen.co đang được bảo trì để nâng cao tính năng và trải nghiệm khách hàng,</p>
                <p class="text-left">Chợ Trực Tuyến chân thành cáo lỗi quý khách vì sự bất tiện này và chúng tôi sẽ đưa website trở lại hoạt động trong thời gian sớm nhất.</p>
                <p class="text-left" style="margin-bottom: 0px;">Trân trọng,</p>
                <p class="text-left">Chợ Trực Tuyến</p>

            </div>
        </div>
    </div>
</div>