<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" >
<head>
    <title><?= ($this->pageTitle == 'Error 503: Service Unavailable') ? 'Bảo Trì Hệ Thống': $this->pageTitle; ?></title>
    <base href="<?= $this->getViewFileUrl() ?>" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="*"/>
    <link rel="stylesheet" href="css/styles.css" type="text/css" />
    <link  rel="icon" type="image/x-icon" href="images/icon_chottvn_color.png" />
    <link  rel="shortcut icon" type="image/x-icon" href="images/icon_chottvn_color.png" />
</head>
<body>
    <main class="page-main">
        <?php require_once $contentTemplate; ?>
    </main>
</body>
</html>
