<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Chottvn\Address\Block\Widget\Email $block */
?>

<div class="field email <?= $block->isRequired() ? 'required' : '' ?>">
    <label for="email" class="label">
        <span>
            <?= $block->escapeHtml(__('Email')) ?>
        </span>
    </label>
    <div class="control">
            <?php
                $_validationClass = $block->escapeHtmlAttr(
                    $this->helper(\Magento\Customer\Helper\Address::class)
                        ->getAttributeValidationClass('email')
                );
            ?>
        <input type="text"
               data-validate="{'validate-email':true}"
               name="email"
               placeholder="<?= __('Input Email') ?>"
               id="email"
               value="<?= $block->escapeHtmlAttr($block->getCustomerEmail()) ?>"
               title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
               class="input-width-50 input-text <?= $_validationClass ?: '' ?>"
        >
    </div>
</div>
