<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Review\Block\Product\ReviewRenderer $block */

$url = '#customer-reviews';
$urlForm = '#review-form';

?>

<?php if ($block->getReviewsCount()) : ?>
    <?php $rating = $block->getRatingSummary(); ?>
    <div class="product-reviews-summary<?= !$rating ? ' no-rating' : '' ?>" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
        <?php if ($rating) :?>
        <!-- <div class="rating-summary">
             <span class="label"><span><?= $block->escapeHtml(__('Rating')) ?>:</span></span>
             <div class="rating-result" title="<?= $block->escapeHtmlAttr($rating); ?>%">
                 <span style="width:<?= $block->escapeHtmlAttr($rating); ?>%">
                     <span>
                         <span itemprop="ratingValue"><?= $block->escapeHtml($rating); ?></span>% of <span itemprop="bestRating">100</span>
                     </span>
                 </span>
             </div>
         </div> -->
            <?php
                // get star reviews
                echo $this->getLayout()
                    ->createBlock('Chottvn\Frontend\Block\ReviewSummary')
                    ->setTemplate("Chottvn_Frontend::review/review_stars.phtml")
                    ->setData(['percent_rating' => $rating])
                    ->toHtml();
            ?>
        <?php endif;?>
        <div class="reviews-actions">
            <a class="action view"
               href="#flag-review" id="scroll-review">
                <span itemprop="reviewCount" class="lowercase">
                    <?php echo __('Have %1 reviews', $block->getReviewsCount()); ?>
                </span>
            </a>
            <!-- <a class="action add" href="<?= $block->escapeUrl($urlForm) ?>"><?= $block->escapeHtml(__('Add Your Review')) ?></a> -->
        </div>
    </div>
<?php elseif ($block->getDisplayIfEmpty()) : ?>
    <div class="product-reviews-summary empty">
        <!-- <div class="reviews-actions">
            <a class="action add" href="#flag-review" id="scroll-review">
                <?= $block->escapeHtml(__('Be the first to review this product')) ?>
            </a>
        </div> -->
        <?php
            // get star reviews
            echo $this->getLayout()
                ->createBlock('Chottvn\Frontend\Block\ReviewSummary')
                ->setTemplate("Chottvn_Frontend::review/review_stars.phtml")
                ->setData(['percent_rating' => 0])
                ->toHtml();
        ?>
        <div class="reviews-actions"><?php echo __('No review on product'); ?></div>
    </div>
<?php endif; ?>