<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_ProductAttributesImportExport
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
// @codingStandardsIgnoreFile
/** @var $block \Bss\ProductAttributesImportExport\Block\Adminhtml\Notice */
?>
<?php
$moduleName = '<b>' . $block->getModuleName() . '</b>';
$isCoreDisabled = $block->isCoreModuleDisabled();
$coreLink = $block->getCoreModuleLink();
$coreLinkTag = '<a target="_blank" href="#">Bss_ImportExportCore</a>';
?>

<?php if ($isCoreDisabled): ?>
    <div class="message message-error error">
        <?= $block->escapeHtml(__("%1 error: You need install/enable the module(%2) to make this extension works properly.", $moduleName, $coreLinkTag)) ?>
    </div>
<?php endif; ?>
