<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
// create info
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();

// detect mobile
$detectMobile = $_objectManager->get('\Chottvn\Frontend\Helper\DetectMobile');
?>
<div data-block="minicart" class="minicart-wrapper" id="minicart-header-top">
    <a class="action showcart" href="<?php /* @escapeNotVerified */
	echo $block->getCheckoutUrl(); ?>"
       data-bind="scope: 'minicart_content'" title="<?= __("Shopping Cart"); ?>">
        <span class="text"><span class="df-text"><?php /* @escapeNotVerified */
				echo __('Shopping Cart'); ?></span><span class="hidden"><?php /* @escapeNotVerified */
				echo __('My Cart - '); ?></span></span>
        <span class="counter qty empty"
              data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
            <span class="counter-number">
                <!-- ko if: ( (getCartParam('summary_count') == 0) || (typeof getCartParam('summary_count') == 'undefined') ) -->
                    <!-- ko i18n: '0' --><!-- /ko -->
                <!-- /ko -->
                <!-- ko ifnot: ( (getCartParam('summary_count') == 0) || (typeof getCartParam('summary_count') == 'undefined') ) -->
                    <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                <!-- /ko -->
                </span>
            <span class="counter-label">
    			<!-- ko if: getCartParam('summary_count') -->
                    <span class="counter-desktop">
                        <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                        <!-- ko i18n: 'sản phẩm' --><!-- /ko -->
                    </span>
                <!-- /ko -->

                <!-- ko if: ( (getCartParam('summary_count') == 0) || (typeof getCartParam('summary_count') == 'undefined') ) -->
                    <span class="counter-desktop">
                        <!-- ko i18n: '0 sản phẩm' --><!-- /ko -->
                    </span>
                <!-- /ko -->
            </span>
        </span>
    </a>
	<?php if ($block->getIsNeedToDisplaySideBar()): ?>
        <div class="block block-minicart empty"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
			<?php echo $block->getChildHtml('minicart.addons'); ?>
        </div>
	<?php endif ?>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */
		echo $block->getJsLayout(); ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */
		echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
    </script>
    <script>
        // require(["jquery"], function ($) {
        //     if($('.block-minicart').is('.subtitle.empty')){
        //         $('.block-minicart').addClass('empty-cart');
        //     }

        //     $('#product-addtocart-button').click(function(){
        //         if($('.block-minicart').is('.subtitle .empty') == false){
        //             $('.block-minicart').removeClass('empty-cart');
        //         }
        //     });
        // });
        window.checkout = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
    </script>

    <?php if($detectMobile->isMobile() == true && $detectMobile->isTablet() == false){ ?>
        <div class="hidden dectect-mobile">mobile</div>
    <?php }else{ ?>
        <div class="hidden dectect-mobile">desktop&tablet</div>
    <?php } ?>
</div>
