<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**  @var $block \Magento\Checkout\Block\Cart */
?>
<div class="cart-empty">
    <div class="page-title-wrapper cart">
        <h1 class="page-title"><?= __("Cart"); ?> <span class="page-title-sub">(0 <?= __("product") ?>)</span></h1>
    </div><!-- ./cart-title -->
    <?= $block->getChildHtml('checkout_cart_empty_widget') ?>
    <div class="cart-empty-notes">
        <p>
            <i class="fas fa-cart-plus cart-icon"></i>
        </p>
        <p>
            <?= $block->escapeHtml(__('Shopping cart is empty')) ?>
        </p>
        <p class="continue-shopping">
            <a href="<?= $block->escapeUrl($block->getContinueShoppingUrl()); ?>"
                title="<?= $block->escapeHtml(__('Continue shopping')); ?>"
                class="action continue-shopping primary btn-action btn-continue-shopping">
                <?= $block->escapeHtml(__('Continue shopping')); ?>
            </a>
        </p>
    </div>
    <?= $block->getChildHtml('shopping.cart.table.after') ?>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Checkout/js/empty-cart": {}
    }
}
</script>
