<?php
$str_less = "
		body{
		  background-color: @body_background_color;
		  font-family: @body_font_family;
		  font-size: @body_font_size;
		  color: @text_color;
		  line-height: 1.66;
			background-image:url('@{background_path}');
			background-repeat: @background_repeat;
			background-position: @background_position;
		}

		.label{
		  color: @text_color;
		}

		a,
		a:focus,
		a:visited{
		  color: @link_color;
		}

		a:hover{
		  color: @link_hover_color;
		}

		/* GENERAL */
		.action.primary:hover,
		.smcqp-btn,
		.spcqp-count,
		.owl-controls .owl-nav div:hover,
		.page-title:before,
		button:hover,
		.cart-container .action.continue:hover,
		a.action.primary:hover,
		.sambar-inner:before{
		  background-color: @theme_color;
		}
		
		#page-loader .loader span{
			background-color: @theme_color;
		}

		.fotorama__thumb-border{
			border-color: @theme_color!important;
		}

		.fotorama__active .fotorama__dot{
			border-color: @theme_color!important;
			background-color: @theme_color;
		}

		.cart-container .cart.table-wrapper .product-item-photo .product-image-photo:hover{
			border-color: @theme_color;
		}

		.cartpro-modal .cpmodal-button{
			background-color: @theme_color;
		}

		#btn-gallery:hover{
			background-color: @theme_color;
		}

		.owl-dots .owl-dot:hover,
		.owl-dots .owl-dot.active{
			background-color: @theme_color;
		}

		.cart-container .cart-summary .coupon .actions-toolbar .primary .apply.primary:hover,
		.modal-footer .action-primary.action-accept:hover,
		.slider-ourmember .owl-dots .owl-dot:hover,
		.slider-ourmember .owl-dots .owl-dot.active,
		.navigation ul > li:hover > a,
		.navigation > ul:before,
		.control-qty .quantity-controls:hover{
		  background-color: @theme_color;
		}
		
		.smrv-block-content-wrap .smrv-handle:hover .smrv-icon, 
		.smrv-block-content-wrap.smrv-over .smrv-handle .smrv-icon,
		.sm-recently-viewed .smrv-clear:hover,
		.sm-recently-viewed .product-item-info a:hover .product-image-wrapper:hover:after{
			background-color: @theme_color;
		}
		
		.sm-listing-tabs .ltabs-items .ltabs-loadmore .ltabs-loadmore-btn{
			background-color: @theme_color;
			
			&:hover{
				background-color: darken(@theme_color, 10%);
			}
		}

		.block-minicart .minicart-items .product-item-details .product-item-name a:hover{
		  color: @theme_color;
		}

		.fotorama__nav-wrap--horizontal .fotorama__thumb__arr--right:hover,
		.fotorama__nav-wrap--horizontal .fotorama__thumb__arr--left:hover{
		  background-color: @theme_color;
		  border-color: @theme_color;
		}

		.fotorama-item .fotorama__nav--thumbs .fotorama__nav__frame.fotorama__active{
		  border-color: @theme_color;
		}

		.more-w .more-view:hover{
		  color: @theme_color;
		}

		.cartpro-imageload{
			border-color: @theme_color!important;
			color: @theme_color!important;
		}

		.direction_rtl .breadcrumbs .items .item:hover,
		.breadcrumbs .items .item:hover{
		  border-color: @theme_color;

		  &:before,
		  &:after{
			border-color: @theme_color;
		  }
		}

		/* END GENERAL */

		/* LISTING */
		
		#price-slider .ui-slider-range{
			background-color: @theme_color;
		}
		
		#price-slider .ui-slider-handle{
			color: @theme_color;
		}

		.block{
		  .block-title{
			&:before{
			  background-color: @theme_color;
			}
		  }
		}

		#sm_slider_price .ui-slider-range{
			background-color: @theme_color;
		}

		#sm_slider_price .ui-slider-handle{
			border-color: @theme_color;
		}

		.products-grid {
		  .item {
			.item-inner {
			  .box-info {
				.bottom-action{
				  .btn-action.btn-cart{

					&:hover{
					  background-color: @theme_color;
					  border-color: @theme_color!important;
					}
				  }

				  .btn-action{
					&.link-wishlist{
					  &:hover{
						&:before{
						  color: @theme_color;
						}
					  }
					}

					&.link-compare{
					  &:hover{
						&:before{
						  color: @theme_color;
						}
					  }
					}

					&:hover{
					  border-color: @theme_color!important;
					}
				  }
				}
			  }
			}
		  }
		}

		.products-list {
		  .item {
			.item-inner {
			  .box-info-list {
				.bottom-action{
				  form{
					.btn-action{
					  &:hover{
						background-color: @theme_color;
						border-color: @theme_color!important;
					  }
					}
				  }


				  .btn-action{
					&.link-wishlist,
					&.link-compare{
					  &:hover{
					  	border-color: @theme_color!important;

					  	&:before{
					  		color: @theme_color!important;
							border-color: @theme_color!important;
					  	}

					  }
					}
				  }
				}
			  }
			}
		  }
		}

		.toolbar{
		  .modes{
			.modes-mode{
			  &.mode-grid{
				&:hover,
				&.active{
				  border-color: @theme_color;
				  background-color: @theme_color;
				}
			  }

			  &.mode-list{
				&:hover,
				&.active{
					border-color: @theme_color;
				  background-color: @theme_color;
				}
			  }
			}
		  }


		  .pages{
			.pages-items{
			  .item{
				&:hover a{
				  background-color: @theme_color;
				  border-color: @theme_color;
				}

				&.current strong{
				  background-color: @theme_color;
				  border-color: @theme_color;
				}

			  }
			}
		  }

		}

		.products-sidebar{
		  .item{
			.item-inner{
			  .box-image{
				&:hover{
				  border-color: @theme_color;
				}
			  }
			}
		  }
		}

		/* END LISTING */

		/* DETAIL */
		
		.services-sidebar li .service-content .service-icon{
			color: @theme_color;
		}

		.accordion-style .resp-accordion.resp-tab-active{
			background-color: @theme_color!important;
			border-color: @theme_color!important;
		}


		.detail-title{
		  &:before{
			background-color: @theme_color;
		  }
		}

		.related-upsell-wrapper .owl-controls .owl-nav div:hover,
		.upsell-wrapper .owl-controls .owl-nav div:hover,
		.resp-vtabs .resp-tabs-list li:hover,
		.resp-vtabs .resp-tabs-list li.resp-tab-active{
		  color: @theme_color;
		}


		.related-upsell-wrapper,
		.upsell-wrapper{

		  .owl-controls{
			.owl-nav{
			  div{
				&:hover{
				  border-color: @theme_color!important;
				  background-color: @theme_color!important;
				}
			  }
			}
		  }
		}



		.product-info-main{

		  .product-options-bottom,
		  .product-add-form{
			.box-tocart{
			  .fieldset{
				.actions{
				  button{
					background-color: @theme_color;
				  }
				}
			  }
			}
		  }

		  .product-social-links{
			.action{
			  &:hover{
				border-color: @theme_color!important;

				&:before{
				  color: @theme_color!important;
				}
			  }
			}
		  }
		}

		/* horizontal full */


		.product-image-detail{
		  .thumbs-container{
			.thumb-slider{
			  .thumb-item{
				.thumb-image{
					&:hover,
					&.thumb-active{
						border-color:@theme_color;
					}
				}
			  }
			}
		  }
		}

		/* end horizontal full */

		/* END DETAIL */

		/* TAB */

		.default-style{
		  .resp-tabs-list{
			li{
			  &:hover{
				color: @theme_color;
			  }

			  &.active{
				color: @theme_color;

				&:before{
				  background-color: @theme_color;
				}
			  }
			}
		  }
		}

		.vertical-style{
		  .resp-tabs-list li {
			&.active{
			  &:before{
				background-color: @theme_color;
			  }
			}
		  }
		}



		/* END TAB */
		
		/* HEADER */
		/* END HEADER */

		/* HOME */

		/* END HOME */

		/* FOOTER */
		
		/* END FOOTER */

		/* LISTING DEALS */
		.sm-listingdeals .listingdeals-items .listingdeals-loadmore .listingdeals-loadmore-btn,
		.sm-listingdeals .listingdeals-tabs-container ul .listingdeals-tab:hover:before,
		.sm-listingdeals .listingdeals-tabs-container ul .listingdeals-tab.tab-sel:before{
			background-color: @theme_color;
		}
		/* END LISTING DEALS */

		/* LISTING EXTEND */

		.sm-listing-extend .owl-controls .owl-dots .owl-dot:hover,
		.sm-listing-extend .owl-controls .owl-dots .owl-dot.active,
		.sm-listing-extend .owl-controls .owl-nav div:hover{
			border-color: @theme_color;
		}

		/* END LISTING EXTEND */

		/* BONUS */

		.cart-container .cart.main.actions .action,
		.cart-container .cart.table-wrapper .actions-toolbar .action-edit:hover,
		.cart-container .cart.table-wrapper .actions-toolbar .action-delete:hover,
		.cart-container .checkout-methods-items .action.primary.checkout{
		  background-color: @theme_color;
		}

		/* END BONUS */

		/* PAGE */

		.pricing-title {
		  h2 {
			&:before {
			  background-color: @theme_color;
			}
		  }
		}

		.table-style-1 {
		  .table-container {
			.table-column .table-content .table-detail .button-container a {
			  &:hover{
				background-color: @theme_color;
			  }
			}
		  }
		}

		.table-style-2 {
		  .table-container {
			.table-column.column-active .table-content .table-detail .table-header {
			  color: @theme_color;
			}

			.table-column.column-active .table-content .table-detail .table-price .price{
			  color: @theme_color;
			}

			.table-column .table-content .button-container a{
				&:hover,
				&:before{
					background-color: @theme_color!important;
				}
			}

			.table-column.column-active .table-content .button-container a {
			  &:hover,
			  &:before{
				background-color: @theme_color;
			  }
			}
		  }
		}

		.table-style-4 {
		  .table-container {
			.table-column .table-content{
				.table-header,
				.button-container a {
				  background-color: @theme_color;
				}
			}
		  }
		}

		.team-style-2 {
		  .team-container {
			.team-inner .team-info {
			  background-color: @theme_color;
			}
		  }
		}

		.team-style-4 {
		  .team-container {
			.team-inner .team-info .socials li a {
			  background-color: @theme_color;
			}
		  }
		}

		.category-item .image-category .title-category h2 a:hover{
			color:@theme_color!important;
		}

		.accordion-type-1,
		.accordion-type-2,
		.accordion-type-4,
		.accordion-type-5{
			.accordion-heading .panel-title a:hover{
				color: @theme_color;
			}
		}

		.link-list {
		  li {
			a {
			  &:hover{
				color: @link_hover_color;
			  }
			}

			&.category-link-title a {
			  color: @theme_color;
			}
		  }
		}

		.testimonials-style-1 {
		  .testimonials-info {
			.name-client {
			  color: @theme_color;
			}
		  }
		}

		.events-list {
		  .item {
			.event-info {
			  .bottom-info a{
				color: @theme_color;
			  }
			}

			.event-info .event-title h2 a {
			  &:hover{
				color: @link_hover_color;
			  }
			}

		  }
		}

		.w-newsletter {
		  .newsletter-info {
			.form-newsletter-popup .action-newsletter button {
			  background-color: @theme_color;
			}
		  }
		}

		.socials-popup {
		  li {
			a:hover {
			  background-color: @theme_color;
			  border-color: @theme_color;
			}
		  }
		}

		/* END PAGE */
		
		/* MOBILE */

		.page-header .sticky-bottom .block-bottom.active .button-sticky-bottom,
		.page-header .sticky-bottom .block-bottom .button-sticky-bottom.button-home:hover,
		.page-header .search-dropdown .block-content .actions .action.search,
		.page-header .dropdown-header-sticky .title-sticky-bottom .close-sticky-bottom,
		.page-header .myaccount-dropdown .block-customer-login button,
		.page-header .myaccount-dropdown .block-customer-login .actions-toolbar .create-account-button:hover,
		.page-header .navigation-dropdown .navigation-mobile > ul > li a:hover:before,
		.page-header .header-top-content .dropdown-categories-header > ul > li ul li a:hover:before,
		.page-header .mycart-dropdown .actions .action.viewcart,
		.page-header .mycart-dropdown .actions .action.checkout,
		.block-footer .title-footer:before,
		.newsletter-footer .block-newsletter .actions button,
		.socials-block ul li a:hover,
		.product-add-form .box-tocart .actions .tocart, body .product-add-form .box-tocart .actions .tocart,
		.cms-index-index .page-header .sticky-bottom .block-bottom .button-sticky-bottom.button-home{
			background-color: @theme_color;
		}
		
		
		.grid-product-type .product-item .item-inner .product-item-info .product-item-details .product-item-inner .tocart:hover,
		.grid-product-type .product-item .item-inner .product-item-info .product-item-details .product-item-inner .towishlist:hover, 
		.grid-product-type .product-item .item-inner .product-item-info .product-item-details .product-item-inner .tocompare:hover,
		.list-product-type .product-item .item-inner .product-item-info .product-item-details .product-item-inner .actions-primary .tocart:hover,
		.list-product-type .product-item .item-inner .product-item-info .product-item-details .product-item-inner .towishlist:hover, 
		.list-product-type .product-item .item-inner .product-item-info .product-item-details .product-item-inner .tocompare:hover{
			background-color: @theme_color;
			border-color: @theme_color;
		}
		
		.grid-product-type .product-item .item-inner .product-item-info .product-item-image .quickview-handler,
		.list-product-type .product-item .item-inner .product-item-info .product-item-image .quickview-handler{
			background-color: @theme_color;
		}
		
		.page-header .navigation-dropdown .navigation-mobile > ul > li a:hover,
		.page-header .header-top-content .dropdown-categories-header > ul > li ul li a:hover,
		.page-header .header-top-content .dropdown-categories-header > ul > li.parent-active > a,
		.page-header .header-top-content .dropdown-categories-header > ul > li > a:hover,
		.page-header .myaccount-dropdown .block.account-nav .content .account-nav .nav.items .nav.item strong,
		.page-header .myaccount-dropdown .content-dropdown > .header.links > li.greet.welcome span,
		.block-footer ul li a:hover,
		.newsletter-footer .title-footer,
		.copyright-payment .copyright a{
			color: @theme_color;
		}
		
		.page-header .header-top-content .categories-header .btn-categories.active,
		.product-add-form .product-social-links .action:hover{
			background-color: @theme_color;
			border-color: @theme_color;
		}
		
		.footer-top-mobile .block-newsletter .actions button{
			background-color: @theme_color;
		}
		
		.accordion-footer .block-footer.active .title-footer::after,
		.categories-footer ul li a:hover{
			color: @theme_color;
		}
		
		.socials-wrap ul li a:hover{
			background-color: @theme_color;
		}
		
		body .product-info-main .product-social-links .action:hover, 
		body .product-add-form .product-social-links .action:hover{
			background-color: @theme_color;
			border-color: @theme_color;
		}
		
		.slider-home .owl-controls .owl-dots .owl-dot{
			&:hover,
			&.active{
				background-color: @theme_color;
			}
		}

		/* END MOBILE */

		// RESPONSIVE

		@media (min-width: 1200px) {
		  .header-style-1 .header-top .header-top-links .toplinks-wrapper .header.links li.myaccount-link a {
			background-color: @theme_color;
		  }

		  .header-style-7 .header-top .header-top-links .toplinks-wrapper .header.links li.myaccount-link a {
			background-color: @theme_color;
		  }

		  .header-style-8 .header-top .header-top-links .toplinks-wrapper .header.links li.myaccount-link a {
			background-color: @theme_color;
		  }
		}

		@media (min-width: 992px) and (max-width: 1199px) {

		}

		@media (min-width: 768px) and (max-width: 991px) {
			.header-style-1 .header-middle .middle-right-content .sm-searchbox .sm-searchbox-content .actions .btn-searchbox{
				background-color: @theme_color!important;
			}

			.header-style-9 .btn-mobile,
			.header-style-11 .btn-mobile,
			.header-style-12 .btn-mobile{
				background-color: @theme_color;
			}

			.header-style-10 .header-top .toplinks-wrapper .header.links li a:hover{
				color: @theme_color;
			}

			.header-style-14 .header-middle .search-header .sm-searchbox .sm-searchbox-content .actions .btn-searchbox{
				background-color: @theme_color!important;
			}

			.header-style-14 .btn-mobile .button-mobile{
				color: @theme_color!important;
			}

			.header-style-15 .header-middle .menu-header .menu-container{
				background-color: @theme_color;
			}
		}

		@media (max-width: 768px) {
			.header-style-5 .header-middle .search-wrapper:before{
				background-color:@theme_color;
			}

			.header-style-1 .header-middle .middle-right-content .sm-searchbox .sm-searchbox-content .actions .btn-searchbox{
				background-color: @theme_color!important;
			}

			.resp-accordion.resp-tab-active{
				background-color:@theme_color;
				border-color:@theme_color;
			}

			.header-style-9 .btn-mobile,
			.header-style-11 .btn-mobile,
			.header-style-12 .btn-mobile{
				background-color: @theme_color;
			}

			.header-style-10 .header-top .toplinks-wrapper .header.links li a:hover{
				color: @theme_color;
			}


			.header-style-14 .header-middle .search-header .sm-searchbox .sm-searchbox-content .actions .btn-searchbox{
				background-color: @theme_color!important;
			}

			.header-style-14 .btn-mobile .button-mobile{
				color: @theme_color!important;
			}

			.header-style-15 .header-middle .menu-header .menu-container{
				background-color: @theme_color;
			}

		}

		@media (max-width: 480px) {

		}
	";
?>