<?php
$_config = $this->helper('Sm\Market\Helper\Data');
?>
<div class="footer-container">
	<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-mobile')->toHtml(); ?>


    <div class="copyright-payment">
		<div class="container">
			<div class="copyright">
				<?php if ($_config->getAdvanced('custom_copyright')) { ?>
                    <address><?php echo $_config->getAdvanced('copyright_content') ?></address>
				<?php } else { ?>
                    <address><?php /* @escapeNotVerified */
						echo $block->getCopyright() ?></address>
				<?php } ?>
			</div>

			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-payment-mobile')->toHtml(); ?>
		</div>
	</div>
</div>	
	

