<?php
$_config      = $this->helper('Sm\Market\Helper\Data');
$compile_less = $_config->getAdvanced('compile_less');
if ($compile_less) {
	//include (dirname(__FILE__).'/compile_less.phtml');
	echo $this->getLayout()->createBlock("Magento\Theme\Block\Html\Header")->setTemplate("Magento_Theme::html/compile_less.phtml")->toHtml();
}
?>

<header class="page-header">
	<div class="container">
		<div class="header-top-content">
			<div class="logo-categories">
				<?php echo $this->getChildHtml("logo"); ?>
				<?php echo $this->getChildHtml("page.main.title"); ?>
                <div class="categories-header">
					<a class="btn-categories" href="javascript:void(0);"><i class="fa fa-bars"></i> <?php echo __('Categories') ?></a>
				</div>
			</div>
			
			<div class="dropdown-categories-header block-menu">
				<?php
				echo $this->getChildHtml("categoriesmenu_default");
				?>
			</div>
		</div>
	</div>
	
	<div class="sticky-bottom">
		<div class="container">
			<div class="content-group-block">
				<div class="group-block">
					<div class="block-bottom">
						<a class="button-sticky-bottom button-home" href="<?php echo $this->getUrl('') ?>">
							<i class="fa fa-home" style="font-size: 22px;"></i>
							<span><?php echo __('Home'); ?></span>
						</a>
					</div>
					
					<div id="search-drop" class="block-bottom">
						<a class="button-sticky-bottom" href="javascript:void(0)" data-drop="search-drop">
							<i class="fa fa-search" style="font-size: 18px;"></i>
							<span><?php echo __('Search'); ?></span>
						</a>
						
						<div class="dropdown-header-sticky search-dropdown">
							<div class="content-dropdown-sticky">
								<div class="title-sticky-bottom">
									<?php echo __('Search Box') ?>
                                    <a class="toggle-button-sticky close-sticky-bottom" data-drop="search-drop"><i class="fa fa-times"></i></a>
								</div>
								
								<div class="content-dropdown">
									<?php echo $this->getChildHtml("top.search"); ?>
								</div>
							</div>
						</div>
					</div>

					<?php echo $this->getChildHtml("minicart"); ?>

                    <div id="myaccount-drop" class="block-bottom">
						<a class="button-sticky-bottom" href="javascript:void(0)" data-drop="myaccount-drop">
							<i class="fa fa-user" style="font-size: 18px;"></i>
							<span><?php echo __('My Account'); ?></span>
						</a>
						
						<div class="dropdown-header-sticky myaccount-dropdown">
							<?php $login = $block->getLayout()->createBlock('Magento\Customer\Block\Account\Customer'); ?>
                            <div class="content-dropdown-sticky">
								<div class="title-sticky-bottom">
									<?php echo __('My Account'); ?>
                                    <a class="toggle-button-sticky close-sticky-bottom" data-drop="myaccount-drop"><i class="fa fa-times"></i></a>
								</div>
								
								<div class="content-dropdown">
									<?php if ($login->customerLoggedIn()) {
										echo $this->getChildHtml('header.links');
									} else {
										echo $this->getChildHtml("customer_form_login_sticky");
									} ?>
								</div>
							</div>
						</div>
					</div>
					
					<div id="menu-drop" class="block-bottom">
						<a class="button-sticky-bottom" href="javascript:void(0)" data-drop="menu-drop">
							<i class="fa fa-bars" style="font-size: 18px;"></i>
							<span><?php echo __('Menu'); ?></span>
						</a>
						
						<div class="dropdown-header-sticky navigation-dropdown">
							<div class="content-dropdown-sticky">
								<div class="title-sticky-bottom">
									<div class="language-currency-sticky">
										<?php echo $this->getChildHtml("store_language"); ?>
										<?php echo $this->getChildHtml("currency"); ?>
									</div>
									<a class="toggle-button-sticky close-sticky-bottom" data-drop="menu-drop"><i class="fa fa-times"></i></a>
								</div>
								
								<div class="content-dropdown">
									<?php echo $this->getChildHtml("nav.mobile"); ?>
								</div>
							</div>
						</div>
					</div>
				</div>

		</div>
	</div>
</header>