<?php

$_config           = $this->helper('Sm\Market\Helper\Data');
$enableLadyLoading = $_config->getAdvanced('enable_ladyloading');
$url_static        = $_config->getUrlStatic();
$store_id          = $_config->getStoreId();
$locale            = $_config->getLocale();
$config_href       = $url_static . 'frontend/Sm/market/' . $locale . '/css/config_' . $store_id . '.css';
?>

<?php
$main_font                = $_config->getGeneral('body_font');
$main_google_font         = $_config->getGeneral('body_google_font');
$google_font_element      = $_config->getGeneral('google_font_targets');
$element_google_font_name = $_config->getGeneral('element_google_font');
$homeStyle                = $_config->getThemeLayout('home_style');
$headerStyle              = $_config->getThemeLayout('header_style');
?>
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $config_href; ?>"/>
<?php if ($main_font == 'google_font') { ?>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=<?php echo $main_google_font ?>"/>
<?php } ?>
<?php if ($google_font_element != '') { ?>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=<?php echo $element_google_font_name ?>"/>
<?php } ?>


<!--CUSTOM CSS-->
<style>
	<?php echo $_config->getAdvanced('custom_css');?>
</style>

<script type="text/javascript">
	require([
        'jquery',
        'domReady!',
        'jquerybootstrap',
        'jqueryunveil',
        'yttheme'
    ], function ($) {
		<?php if($enableLadyLoading){ ?>
        function _runLazyLoad() {
            $("img.lazyload").unveil(0, function () {
                $(this).load(function () {
                    this.classList.remove("lazyload");
                });
            });
        }

        _runLazyLoad();
        $(document).on("afterAjaxLazyLoad", function (event) {
            _runLazyLoad();
        });

		<?php } ?>
    });
</script>


<!--CUSTOM JS-->
<?php echo $_config->getAdvanced('custom_js'); ?>

<script type="text/javascript">
	require([
        'jquery',
        'domReady!'
    ], function ($) {
        if ($('.breadcrumbs').length == 0) {
            $('body').addClass("no-breadcrumbs");
        }
    });

</script>

<!--LISTING CONFIG-->
<style>
<?php echo $google_font_element ?>
{
    font-family:
<?php $namegooglefont_element = explode(":",str_replace("+", " ", $element_google_font_name));
		echo $namegooglefont_element[0];
	?>
;
}
</style>
