<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @see \Magento\Theme\Block\Html\Topmenu
 */
?>

<?php
$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menu        = $block->getHtml('level-top', 'submenu', $columnsLimit);
?>

<div class="block-navigation-mobile">
	<nav class="navigation-mobile">
		<ul>
			<?php /* @escapeNotVerified */
			echo $_menu; ?>
		</ul>
	</nav>
</div>


