<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */

$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');

$_config = $this->helper('Sm\Market\Helper\Data');

?>

<?php
switch ($type = $block->getType()) {

	case 'related-rule':
		if ($exist = $block->hasItems()) {
			$type  = 'related';
			$class = $type;

			$image             = 'related_products_list';
			$hover_image       = 'category_page_grid-hover';
			$title             = __('Related Products');
			$items             = $block->getAllItems();
			$limit             = $_config->getProductDetail('related_limit');
			$shuffle           = (int)$block->isShuffled();
			$canItemsAddToCart = $block->canItemsAddToCart();

			$showAddTo    = true;
			$showCart     = false;
			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;;
			$description = false;
		}
		break;

	case 'related':
		/** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
		if ($exist = $block->getItems()->getSize()) {
			$type  = 'related';
			$class = $type;

			$image             = 'related_products_list';
			$hover_image       = 'category_page_grid-hover';
			$title             = __('Related Products');
			$items             = $block->getItems();
			$limit             = $_config->getProductDetail('related_limit');
			$shuffle           = 0;
			$canItemsAddToCart = $block->canItemsAddToCart();

			$showAddTo    = true;
			$showCart     = false;
			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;;
			$description = false;
		}
		break;

	case 'upsell-rule':
		if ($exist = $block->hasItems()) {
			$type  = 'upsell';
			$class = $type;

			$image       = 'upsell_products_list';
			$hover_image = 'category_page_grid-hover';
			$title       = __('Upsell Products');
			$items       = $block->getAllItems();
			$limit       = $_config->getProductDetail('upsell_limit');
			$shuffle     = (int)$block->isShuffled();

			$showAddTo    = false;
			$showCart     = false;
			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;;
			$description       = false;
			$canItemsAddToCart = false;
		}
		break;

	case 'upsell':
		/** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
		if ($exist = count($block->getItemCollection()->getItems())) {
			$type  = 'upsell';
			$class = $type;

			$image       = 'upsell_products_list';
			$hover_image = 'category_page_grid-hover';
			$title       = __('Upsell Products');
			$items       = $block->getItemCollection()->getItems();
			$limit       = $_config->getProductDetail('upsell_limit');
			$shuffle     = 0;

			$showAddTo    = false;
			$showCart     = false;
			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;;
			$description       = false;
			$canItemsAddToCart = false;
		}
		break;
}
?>

<?php if ($exist): ?>


    <div class="block block-detail <?php /* @escapeNotVerified */
	echo $class; ?>">
    <div class="primary-title">
        <h2 id="block-<?php /* @escapeNotVerified */
		echo $class ?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */
			echo $title; ?></h2>
    </div>
    <div class="block-content content scroll-container" aria-labelledby="block-<?php /* @escapeNotVerified */
	echo $class ?>-heading">
        <div class="scroll-block grid products-grid products-<?php /* @escapeNotVerified */
		echo $type; ?>">
            <div class="grid-product-type products list items product-items item-table">
                <?php $i = 0;
				foreach ($items as $_item): $i++; ?>
                    <div class="item product product-item item-table-cell">
					<div class="item-inner">
						<div class="product-item-info">
							<div class="product-item-image box-image">
								<a href="<?php /* @escapeNotVerified */
								echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
									<?php echo $block->getImage($_item, $image)->toHtml(); ?>
								</a>
							</div>
							
							<div class="product details product-item-details">
								<div class="product name product-item-name">
									<a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */
									echo $block->getProductUrl($_item) ?>">
										<?php echo $block->escapeHtml($_item->getName()) ?>
									</a>
								</div>

								<?php echo $block->getReviewsSummaryHtml($_item, $templateType, true) ?>

								<?php /* @escapeNotVerified */
								echo $block->getProductPrice($_item); ?>


                                <div class="product-item-inner">
									<div class="product actions product-item-actions">
										<?php if ($_config->getAdvanced('show_wishlist_button')) { ?>
											<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                <a href="#" data-post='<?php /* @escapeNotVerified */
												echo $block->getAddToWishlistParams($_item); ?>' class="action towishlist btn-action link-wishlist" data-action="add-to-wishlist" title="<?php /* @escapeNotVerified */
												echo __('Add to Wish List') ?>">
													<span><?php /* @escapeNotVerified */
														echo __('Add to Wish List') ?></span>
												</a>
											<?php endif; ?>
										<?php } ?>

										<?php if ($_config->getAdvanced('show_addtocart_button')) { ?>
                                            <div class="actions-primary">
												<?php if ($_item->isSaleable()): ?>
													<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <button class="action tocart btn-action btn-cart" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */
														echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */
														echo __('Add to Cart') ?>">
															<span><?php /* @escapeNotVerified */
																echo __('Add to Cart') ?></span>
														</button>
													<?php else: ?>
														<?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
														$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
														?>
                                                        <button class="action tocart btn-action btn-cart" data-post='<?php /* @escapeNotVerified */
														echo $postData; ?>' type="button" title="<?php /* @escapeNotVerified */
														echo __('Add to Cart') ?>">
															<span><?php /* @escapeNotVerified */
																echo __('Add to Cart') ?></span>
														</button>
													<?php endif; ?>
												<?php else: ?>
													<?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */
																echo __('In stock') ?></span></div>
													<?php else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */
																echo __('Out of stock') ?></span></div>
													<?php endif; ?>
												<?php endif; ?>
											</div>
										<?php } ?>

										<?php if ($_config->getAdvanced('show_compare_button')) { ?>
											<?php if ($block->getAddToCompareUrl()): ?>
												<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                <a href="#" class="action tocompare btn-action link-compare" data-post='<?php /* @escapeNotVerified */
												echo $compareHelper->getPostDataParams($_item); ?>' data-role="add-to-links" title="<?php /* @escapeNotVerified */
												echo __('Add to Compare'); ?>">
													<span><?php /* @escapeNotVerified */
														echo __('Add to Compare') ?></span>
												</a>
											<?php endif; ?>
										<?php } ?>
									</div>
								</div>

								
							</div>
						</div>
					</div>
                </div>
					<?php if ($i == $limit) break; ?>
				<?php endforeach ?>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
