<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */
$item = $block->getItem();
$product = $item->getProduct();
$productBrandHelper = $this->helper('Ves\Brand\Helper\ProductBrand');
$amPromoHelper = $this->helper('Amasty\Promo\Helper\Item');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$productResource = $objectManager->create('Magento\Catalog\Model\Product')->load($product->getId());
$checkoutHelper = $objectManager->get('Chottvn\PriceDecimal\Helper\Data');
$helperbg = $this->helper('Chottvn\PriceQuote\Helper\Data');
$imageHelper = $this->helper('Magento\Catalog\Helper\Image');
$productRepository = $objectManager->get('\Magento\Catalog\Model\Product');
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
$cartPromoOption = $item->getCartPromoOption();
$quoteId = $item->getQuoteId();
$quoteItemId = $item->getId();
$qtyCurrent = $item->getQty();
$attributesOption = $helperbg->getOptionsAttributes($quoteItemId);
$productidOfconfigurable = $product->getId();
$defaultStockconfigurable = 0;
if($attributesOption){
    $itemQuote = $objectManager->get('Magento\Quote\Model\ResourceModel\Quote\Item\CollectionFactory');
    $itemQuoteCollection = $itemQuote->create()->addFieldToFilter('parent_item_id',$quoteItemId)->addFieldToFilter('product_type','simple');
    $lastItemQuote = $itemQuoteCollection->getLastItem();
    $productidOfconfigurable = $lastItemQuote->getData('product_id');
    $defaultStockconfigurable = $helperbg->checkDefaultStock($productidOfconfigurable);
}else{
    $defaultStockconfigurable = $helperbg->checkDefaultStock($product->getId());
}
// Huy add func show message task: 965
$outOfStock = false;
$defaultStockQty = 0;
//
$guaranteeInfo = $productResource->getData('guarantee');
$productunit = $productResource->getData('product_unit') ? $productResource->getData('product_unit'): '';
// $reviewFactory = $objectManager->create('Magento\Review\Model\Review');
$storeId = $storeManager->getStore()->getId();
// $reviewFactory->getEntitySummary($productResource, $storeId);
// $ratingSummary = $productResource->getRatingSummary()->getRatingSummary();
// $ratingCount = $productResource->getRatingSummary()->getReviewsCount();

$blockRules = $block->getLayout()->createBlock('Chottvn\Frontend\Block\Rules');
// $cartRuleNames = $blockRules->getCartRuleByProduct($product);
// $catalogRuleNames = $blockRules->getCatalogRuleByProduct($product);
// $ruleNames = array_merge($cartRuleNames, $catalogRuleNames);

$priceQuoteHelper = $this->helper('Chottvn\PriceQuote\Helper\Data');
$ruleIdsApplied = $item->getAppliedRuleIds();
$ruleNames = $helperbg->getRulesNameWithQuoteCTT($quoteItemId, $quoteId ,$ruleIdsApplied);
// $isPromoItem = $amPromoHelper->isPromoItem($item);
$isPromoItem = $helperbg->isPromoItemCTT($cartPromoOption);
// detect mobile
$detectMobile = $objectManager->get('\Chottvn\Frontend\Helper\DetectMobile');
$messages_prefix = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('ampromo/messages/prefix');
// url and image
$helperbg = $this->helper('Chottvn\PriceQuote\Helper\Data');
$jacket = array();
$productidOfconfigurable = $product->getId();
$attributesOption = array();
$productTypeInstance = $objectManager->get('Magento\Catalog\Model\ResourceModel\Eav\Attribute');
$_options = $block->getOptionList();
$itemOptions = $objectManager->get('Magento\Quote\Model\ResourceModel\Quote\Item\Option\CollectionFactory');
if ($_options){
    $quoteItemId = $item->getId();
    $itemQuote = $objectManager->get('Magento\Quote\Model\ResourceModel\Quote\Item\CollectionFactory');
    $itemQuoteCollection = $itemQuote->create()->addFieldToFilter('parent_item_id',$quoteItemId)->addFieldToFilter('product_type','simple');
    $lastItemQuote = $itemQuoteCollection->getLastItem();
    $productidOfconfigurable = $lastItemQuote->getData('product_id');
    $defaultStockQty = $helperbg->checkDefaultStock($productidOfconfigurable);
}else{
    $websiteCode = $storeManager->getWebsite()->getCode();
    $stockResolver = $objectManager->get('Magento\InventorySalesApi\Api\StockResolverInterface');
    $productSalableQty = $objectManager->get('Magento\InventorySalesApi\Api\GetProductSalableQtyInterface');
    $stock = $stockResolver->execute(Magento\InventorySalesApi\Api\Data\SalesChannelInterface::TYPE_WEBSITE, $websiteCode);
    $stockId = $stock->getStockId();
    $product_sku = $productResource->getSku();
    $defaultStockQty = $productSalableQty->execute($product_sku, $stockId);
}
$messageCTT = '';
if ($defaultStockQty == 0) {
    $outOfStock = true;
    $messageCTT = __('Out of stock');
}
if ($defaultStockQty != 0 && ($defaultStockQty < $block->getQty())) {
    $messageCTT = __('Only %1 item left', $defaultStockQty);
}
$attributesOption = $helperbg->getOptionsAttributes($item->getId());
if ($attributesOption) {
    foreach ($attributesOption as $key => $attr) {
        $_attr = $productTypeInstance->load($key);
        $attributeCode = $_attr->getAttributeCode();
        $jacket[$attributeCode] = $attr;
    }
}
$getProductUrl = $product->getProductUrl();
if ($jacket) {
    $getProductUrl = $getProductUrl . '#';
    foreach($jacket as $key => $value){
        $getProductUrl = $getProductUrl .$key. '='. $value .'&';
    }
    $getProductUrl = substr($getProductUrl, 0, -1);
}
$productModel = $productResource->getData('model');
$productImage = null;
if($productidOfconfigurable != $product->getId()){
    $productResourceConfiguration = $objectManager->create('Magento\Catalog\Model\Product')->load($productidOfconfigurable);
    if(!$productModel){
        $productModel = $productResourceConfiguration->getData('model');
    }
    $productImage = $imageHelper->init($productResourceConfiguration, 'product_page_image_thumbnail')->setImageFile($productResourceConfiguration->getImage())->getUrl();
}else{
    $productCatalog = $objectManager->create('Magento\Catalog\Model\Product')->load($product->getId());
    $productImage = $imageHelper->init($product, 'product_page_image_thumbnail')->setImageFile($productCatalog->getImage())->getUrl();
}
if (isset($productImage) && !($priceQuoteHelper->url_exists($productImage))) {
    $productImage = $imageHelper->getDefaultPlaceholderUrl('thumbnail');
}
if (!isset($productImage)) {
    $productImage = $imageHelper->getDefaultPlaceholderUrl('thumbnail');
}

?>

<tbody class="cart item">
    <tr class="item-info">
            <?php if ($detectMobile->isMobile() == true && $detectMobile->isTablet() == false) { ?>
                <!-- Mobile View -->
                <td data-th="<?= __('Product'); ?>" class="col item">
                                                <!-- Mobile View -->
                                                <?php if (!$isPromoItem) { ?>
                                                    <div class="product-item-details-mobile clearfix">
                                                        <div class="product-item-name">
                                                            <?php if ($block->hasProductUrl($product)) : ?>
                                                                <a href="<?= $block->escapeUrl($getProductUrl) ?>" title="<?= $block->escapeHtml($block->getProductName()) ?>">
                                                                    <?= $productResource->getNameLongHtml(); ?>
                                                                </a>
                                                            <?php else : ?>
                                                                <span><?= $productResource->getNameLongHtml(); ?></span>
                                                            <?php endif; ?>
                                                        </div>
                                                    </div>
                                                <?php } ?>
                                                <!-- Brand, Model -->
                                                <?php
                                                        $productBrand = $productBrandHelper->getFirstBrandByProduct($product);
                                                        $model = $productResource->getData('model');
                                                        if ($productBrand || $model){
                                                    ?>
                                                    <div class="brand-model-mobile clearfix">
                                                        <?php 
                                                            if ($productBrand ){
                                                        ?>
                                                            <div class="brand-name">
                                                                <span><?php echo __('Brands: '); ?></span>
                                                                <span class="name"><?php echo $productBrand->getName(); ?></span>
                                                            </div>
                                                        <?php } ?>
                                                        <?php if($model){ ?>
                                                            <div class="model-name">
                                                                <span class="label"><?php echo __('Model: '); ?></span>
                                                                <span class="name"><?php echo $model; ?></span>
                                                            </div>
                                                        <?php } ?>
                                                    </div>
                                                <?php } ?>
                                                <?php if (!$isPromoItem) { ?>
                                                    <!-- Guarantee -->
                                                    <?php if ($guaranteeInfo) { ?>
                                                        <div class="guarantee-info line-height-mobile">
                                                            <span><?php echo __('Guarantee: '); ?></span>
                                                            <span class="name"><?php echo $guaranteeInfo; ?></span>
                                                        </div>
                                                    <?php } ?>
                                                <?php } ?>
                                                <!-- options -->
                                                <?php if (!$isPromoItem) { ?>
                                                    <?php if ($attributesOption) { ?>
                                                        <div class="guarantee-info line-height-mobile">
                                                        <?php foreach($attributesOption as $key => $value): ?>
                                                        <?php 
                                                            $productTypeInstance = $objectManager->get('Magento\ConfigurableProduct\Model\Product\Type\Configurable');
                                                            $productAttributeOptions = $productTypeInstance->getConfigurableAttributesAsArray($productResource);
                                                            $labelOptions = '';
                                                            $valueOptions = '';
                                                            foreach ($productAttributeOptions as $key_o => $value_o) {
                                                                $tmp_option = $value_o['values'];
                                                                if(count($tmp_option) > 0)
                                                                {   
                                                                    foreach ($tmp_option as $tmp) {
                                                                        if($key_o == $key && $tmp['value_index'] == $value){
                                                                            $labelOptions = $value_o['store_label'];
                                                                            $valueOptions = $tmp['label'];
                                                                            break;
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        ?>
                                                            <span class="span-options-right"><?php echo $labelOptions; ?>: <?php echo $valueOptions; ?></span>
                                                        <?php endforeach; ?>
                                                        </div>
                                                    <?php } ?>
                                                <?php } ?>
                                                <div class="product-item-photo-mobile">
                                                    <?php if ($block->hasProductUrl($product)) : ?>
                                                        <a href="<?= $block->escapeUrl($getProductUrl) ?>" title="<?= $block->escapeHtml($block->getProductName()) ?>" tabindex="-1" class="product-item-photo">
                                                            <span class="product-image-container">
                                                                <span class="product-image-wrapper">
                                                                    <img class="product-image-photo " src="<?= $productImage ?>" width="" height="" alt="<?= $block->escapeHtml($block->getProductName()) ?>">
                                                                </span>
                                                            </span>
                                                        </a>
                                                    <?php else : ?>
                                                        <a title="<?= $block->escapeHtml($block->getProductName()) ?>" tabindex="-1" class="product-item-photo">
                                                            <span class="product-image-container">
                                                                <span class="product-image-wrapper">
                                                                    <img class="product-image-photo " src="<?= $productImage ?>" width="" height="" alt="<?= $block->escapeHtml($block->getProductName()) ?>">
                                                                </span>
                                                            </span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                                <?php if (!$isPromoItem) { ?>
                                                    <div class="product-item-details">
                                                        <div class="field qty field-qty-mobile">
                                                            <div class="control qty">
                                                                <label for="cart-<?= $block->escapeHtmlAttr($item->getId()) ?>-qty">
                                                                    <?php if (!$isPromoItem) { ?>
                                                                    <span class="quantity-controls quantity-minus change-qty <?= $outOfStock ? "pointer-events" : "" ?> <?= $block->getQty() <= 1 ? "text-secondary" : ""  ?>" id="<?= /* @escapeNotVerified */ $item->getId() ?>-minus-qty">-</span>
                                                                    <input id="cart-<?= $block->escapeHtmlAttr($item->getId()) ?>-qty"
                                                                        data-post='<?= $item->getId(); ?>' 
                                                                        default-stock="<?= $defaultStockconfigurable; ?>" 
                                                                        oldQty="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                                                                        name="cart[<?= $block->escapeHtmlAttr($item->getId()) ?>][qty]"
                                                                        data-cart-item-id="<?= $block->escapeHtmlAttr($item->getSku()) ?>"
                                                                        value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                                                                        type="number"
                                                                        size="4"
                                                                        title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                                                                        class="input-text qty <?= $outOfStock ? "pointer-events" : "" ?> <?= $isPromoItem ? "disabled" : "" ?>"
                                                                        data-validate="{required:true,'validate-greater-than-zero':true}"
                                                                        data-role="cart-item-qty"
                                                                        <?= $isPromoItem ? "disabled" : "" ?>/>
                                                                    <span class="quantity-controls quantity-plus change-qty <?= $outOfStock ? "pointer-events" : "" ?>" id="<?= /* @escapeNotVerified */ $item->getId() ?>-plus-qty">+</span>
                                                                    <?php } else { ?>
                                                                    <span class="quantity">
                                                                        <?= $block->escapeHtml(__('Qty')) ?>
                                                                        <?= $block->getQty(); ?>
                                                                    </span>
                                                                    <?php } ?>
                                                                </label>
                                                            </div>
                                                            <?php if(isset($productunit)): ?>
                                                                <span class="unit-product-mobile"><?= $productunit ? $productunit : ''; ?></span>
                                                            <?php endif ?>
                                                        </div>
                                                        <!-- Item Price -->
                                                        <span class="price-excluding-tax price-excluding-tax-mobile" data-label="<?= __('Tax not include') ?>">
                                                            <span class="cart-price">
                                                                <span class="price"><?= $checkoutHelper->formatPrice($item->getPrice()); ?></span>
                                                            </span>
                                                        </span>
                                                        <?php
                                                        $priceOriginal = $productResource->getPrice();
                                                        $priceFinal = $item->getPriceInclTax();
                                                        $savePercent = ($priceOriginal == 0) ? 0 : 100 - round(@($priceFinal / $priceOriginal) * 100);
                                                        if ($savePercent != 0) { ?>
                                                            <div class="checkout-cart-save-price line-height-mobile">
                                                                <span class="save-percent">-<?= $savePercent; ?>%</span>
                                                                <span class="price-original"><span class="price"><?= $checkoutHelper->formatPrice($priceOriginal); ?></span></span>
                                                            </div>
                                                        <?php } ?>
                                                        <!-- </td> -->
                                                        <div class="subtotal subtotal-mobile">
                                                            <span class="price-excluding-tax" data-label="<?= __('Tax not include') ?>">
                                                                <span class="cart-price">
                                                                    <span><?= $block->escapeHtml(__('Into Money: ')) ?></span>
                                                                    <span class="price"><?= $checkoutHelper->formatPrice($item->getRowTotal()); ?></span>
                                                                </span>
                                                            </span>
                                                        </div>
                                                       <!-- Item Actions -->
                                                        <?php if (!$isPromoItem){ ?>
                                                            <div class="actions-toolbar">
                                                                <?= /* @noEscape */ $block->getActions($item) ?>
                                                            </div>
                                                        <?php } ?>
                                                    </div>
                                                <?php }else{ ?>
                                                    <?php
                                                        $itemId = $item->getId();
                                                        $lastItemOptions = $itemOptions->create()->addFieldToFilter('item_id', array('eq' => $itemId));
                                                        $lastItemOptions = $lastItemOptions->getLastItem();
                                                        $rulesId = '';
                                                        $nameRule = '';
                                                        if(isset($lastItemOptions['value'])){
                                                            $arrRulesId = json_decode($lastItemOptions['value'], true);
                                                            if(isset($arrRulesId["options"]) && isset($arrRulesId["options"]['ampromo_rule_id'])){
                                                                $rulesId = $arrRulesId["options"]['ampromo_rule_id'];
                                                            }
                                                        }
                                                        if($rulesId){
                                                            $nameRule = $helperbg->getRulesNameByIdRule($rulesId);
                                                        }
                                                        
                                                    ?>
                                                    <div class="product-item-details">
                                                        <div class="rules-name-mobile">
                                                            <?= $nameRule ? '<strong>'.$nameRule.'</strong>': ''; ?>
                                                            <br>
                                                            <?php if ($block->hasProductUrl($product)) : ?>
                                                                <a href="<?= $block->escapeUrl($getProductUrl) ?>" title="<?= $block->escapeHtml($block->getProductName()) ?>">
                                                                    <?= $productResource->getName(); ?>
                                                                </a>
                                                            <?php else : ?>
                                                                <span><?= $productResource->getName(); ?></span>
                                                            <?php endif; ?>
                                                        </div>
                                                    </div>
                                                <?php } ?>
                                                <!-- Cart Rules -->
                                                <?php if (!$isPromoItem) { ?>
                                                        <?php if ((!empty($ruleNames)) && (count($ruleNames) > 0)) { ?>
                                                            <div class="product-item-rule-mobile clearfix">
                                                                <div class="promotion-info">
                                                                    <ul class="rules-list">
                                                                        <?php foreach ($ruleNames as $key => $rules) { ?>
                                                                            <?php if(count($rules['sku']) > 0){ ?>
                                                                                <?php foreach($rules['sku'] as $index => $sku){ ?>
                                                                                    <?php 
                                                                                        $productData = $productRepository->loadByAttribute('sku',$sku);
                                                                                        if (!empty($productData)){
                                                                                            $productId = $productData->getId();
                                                                                            $nameproduct = $productData->getName();
                                                                                            $visibility = $helperbg->hasProductUrl($productRepository->load($productId));
                                                                                            $urlProduct = $productData->getProductUrl();
                                                                                            $unitProduct = $rules['unit_product'][$index] ? ' '.$rules['unit_product'][$index]: '';
                                                                                            $qtyGift = $rules['qty'][$index] ? (int) $rules['qty'][$index] * (int) $item['qty']: '';
                                                                                            $resultString = '('.$qtyGift.$unitProduct.')';
                                                                                            $arrayDefaultStockPromo = array();
                                                                                            $arrayDefaultStockPromo[$key]['name_product'][]= $nameproduct;
                                                                                            $arrayDefaultStockPromo[$key]['default_stock_promo'][] = (int) $rules['default-stock'][$index];
                                                                                            $arrayDefaultStockPromo[$key]['sum_default_stock'][] = (int) $rules['sum-default-stock'][$index];
                                                                                            $arrayDefaultStockPromo[$key]['qty_promo_current'][] = $qtyGift;
                                                                                    ?>
                                                                                    <li>
                                                                                        <i class="fas fa-gift text-danger"></i><strong><?php echo __('Gift: '); ?></strong><span class="span-product"><?php echo $nameproduct; ?> <?php echo $resultString; ?> </span>
                                                                                        <input type="hidden" value='<?= json_encode($arrayDefaultStockPromo); ?>' id="default-stock-promo-<?= $item->getId() ?>" />
                                                                                        <?php if($visibility){?>
                                                                                            <a class="see-more-rules" target="_blank" href= '<?php echo $urlProduct; ?>' title="<?= $nameproduct ?>">
                                                                                                <span class="span-load-more"><?= __('Load more details'); ?> &raquo;</span>
                                                                                            </a>
                                                                                        <?php }?>
                                                                                    </li>
                                                                        <?php }}}} ?>
                                                                    </ul>
                                                                </div>
                                                        </div>
                                                    <?php } ?>
                                                <?php } ?>
                                            </td>
            <?php } else { ?>
                 <!-- Desktop View -->
                 <td data-th="<?= __('Product'); ?>" class="col item">
                                                <div class="product-item-photo">
                                                    <div class="img-box">
                                                    <?php if ($block->hasProductUrl($product)) : ?>
                                                        <a href="<?= $block->escapeUrl($getProductUrl) ?>" title="<?= $block->escapeHtml($block->getProductName()) ?>" tabindex="-1" class="product-item-photo">
                                                            <span class="product-image-container">
                                                                <span class="product-image-wrapper">
                                                                    <img class="product-image-photo " src="<?= $productImage ?>" width="" height="" alt="<?= $block->escapeHtml($block->getProductName()) ?>">
                                                                </span>
                                                            </span>
                                                        </a>
                                                    <?php else : ?>
                                                        <a title="<?= $block->escapeHtml($block->getProductName()) ?>" tabindex="-1" class="product-item-photo">
                                                            <span class="product-image-container">
                                                                <span class="product-image-wrapper">
                                                                    <img class="product-image-photo " src="<?= $productImage ?>" width="" height="" alt="<?= $block->escapeHtml($block->getProductName()) ?>">
                                                                </span>
                                                            </span>
                                                        </a>
                                                    <?php endif; ?>
                                                    </div>
                                                </div>
                                                <div class="product-item-details">
                                                    <div class="product-item-name">
                                                        <?php
                                                            $itemId = $item->getId();
                                                            $lastItemOptions = $itemOptions->create()->addFieldToFilter('item_id', array('eq' => $itemId));
                                                            $lastItemOptions = $lastItemOptions->getLastItem();
                                                            $rulesId = ''; $nameRule = '';
                                                            if(isset($lastItemOptions['value'])){
                                                                $arrRulesId = json_decode($lastItemOptions['value'], true);
                                                                if(isset($arrRulesId["options"]) && isset($arrRulesId["options"]['ampromo_rule_id'])){
                                                                    $rulesId = $arrRulesId["options"]['ampromo_rule_id'];
                                                                }
                                                            }
                                                            if($rulesId){
                                                                $nameRule = $helperbg->getRulesNameByIdRule($rulesId);
                                                            }
                                                        ?>
                                                        <?php if ($block->hasProductUrl($product)) : ?>
                                                            <a href="<?= $block->escapeUrl($getProductUrl) ?>" title="<?= $block->escapeHtml($block->getProductName()) ?>">
                                                                <?php if($isPromoItem){ ?>
                                                                    <!-- Rule Name -->
                                                                    <?= $nameRule ? '<strong>'.$nameRule.'</strong>': ''; ?>
                                                                    <span><?= $productResource->getName(); ?></span>
                                                                <?php }else{ ?>
                                                                    <?= $productResource->getNameLongHtml(); ?>
                                                                <?php } ?>
                                                            </a>
                                                        <?php else : ?>
                                                                <?php if($isPromoItem){ ?>
                                                                    <!-- Rule Name -->
                                                                    <?= $nameRule ? '<strong>'.$nameRule.'</strong>': ''; ?>
                                                                    <!-- Name Product -->
                                                                    <span style="display: block;"><?= $productResource->getName(); ?></span>
                                                                <?php }else{ ?>
                                                                    <?= $productResource->getNameLongHtml(); ?>
                                                                <?php } ?>
                                                        <?php endif; ?>
                                                    </div>
                                                    <?php if(!$isPromoItem){ ?>
                                                        <!-- Brand, Model -->
                                                        <div class="brand-model clearfix">
                                                            <div class="brand-name">
                                                                <?php
                                                                $productBrand = $productBrandHelper->getFirstBrandByProduct($product);
                                                                if ($productBrand) {
                                                                ?>
                                                                    <span><?php echo __('Brands: '); ?></span>
                                                                    <span class="name"><?php echo $productBrand->getName(); ?></span>
                                                                <?php } ?>
                                                            </div>
                                                            <div class="model-name">
                                                                <?php
                                                                if ($productModel) {
                                                                ?>
                                                                    <span><?php echo __('Model: '); ?></span>
                                                                    <span class="name"><?php echo $productModel; ?></span>
                                                                <?php } ?>
                                                            </div>
                                                        </div>
                                                    <!-- Reviews -->
                                                    <!-- Guarantee -->
                                                    <?php if ($guaranteeInfo) { ?>
                                                        <div class="guarantee-info">
                                                            <span><?php echo __('Guarantee: '); ?></span>
                                                            <span class="name"><?php echo $guaranteeInfo; ?></span>
                                                        </div>
                                                    <?php } ?>
                                                    <?php if ($attributesOption) { ?>
                                                        <div class="options-info">
                                                            <?php foreach($attributesOption as $key => $value): ?>
                                                            <?php 
                                                                $productTypeInstance = $objectManager->get('Magento\ConfigurableProduct\Model\Product\Type\Configurable');
                                                                $productAttributeOptions = $productTypeInstance->getConfigurableAttributesAsArray($productResource);
                                                                $labelOptions = '';
                                                                $valueOptions = '';
                                                                foreach ($productAttributeOptions as $key_o => $value_o) {
                                                                    $tmp_option = $value_o['values'];
                                                                    if(count($tmp_option) > 0)
                                                                    {   
                                                                        foreach ($tmp_option as $tmp)  {
                                                                            if($key_o == $key && $tmp['value_index'] == $value){
                                                                                $labelOptions = $value_o['store_label'];
                                                                                $valueOptions = $tmp['label'];
                                                                                break;
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            ?>
                                                                <span class="span-options-right"><?php echo $labelOptions; ?>: <?php echo $valueOptions; ?></span>
                                                            <?php endforeach; ?>
                                                        </div>
                                                        <?php } ?>
                                                    <?php } ?>
                                                    <!-- Cart Rules -->
                                                    <?php if (!$isPromoItem) { ?>
                                                        <?php if ((!empty($ruleNames)) && (count($ruleNames) > 0)) { ?>
                                                            <div class="promotion-info">
                                                                <ul class="rules-list">
                                                                    <?php foreach ($ruleNames as $key => $rules) { ?>
                                                                        <?php if(count($rules['sku']) > 0){ ?>
                                                                            <?php foreach($rules['sku'] as $index => $sku){ ?>
                                                                                <?php 
                                                                                    $productData = $productRepository->loadByAttribute('sku',$sku);
                                                                                    if (!empty($productData)){
                                                                                        $productId = $productData->getId();
                                                                                        $nameproduct = $productData->getName();
                                                                                        $visibility = $helperbg->hasProductUrl($productRepository->load($productId));
                                                                                        $urlProduct = $productData->getProductUrl();
                                                                                        $unitProduct = $rules['unit_product'][$index] ? ' '.$rules['unit_product'][$index]: '';
                                                                                        $qtyGift = $rules['qty'][$index] ? (int) $rules['qty'][$index] * (int) $item->getQty() : '';
                                                                                        $resultString = '('.$qtyGift.$unitProduct.')';
                                                                                        $arrayDefaultStockPromo = array();
                                                                                        $arrayDefaultStockPromo[$key]['name_product'][]= $nameproduct;
                                                                                        $arrayDefaultStockPromo[$key]['default_stock_promo'][] = (int) $rules['default-stock'][$index];
                                                                                        $arrayDefaultStockPromo[$key]['sum_default_stock'][] = (int) $rules['sum-default-stock'][$index];
                                                                                        $arrayDefaultStockPromo[$key]['qty_promo_current'][] = $qtyGift;
                                                                                ?>
                                                                                <li>
                                                                                    <i class="fas fa-gift text-danger"></i><strong><?php echo __('Gift: '); ?></strong><span class="span-product"><?php echo $nameproduct; ?> <?php echo $resultString; ?> </span>
                                                                                    <input type="hidden" value='<?= json_encode($arrayDefaultStockPromo); ?>' id="default-stock-promo-<?= $item->getId() ?>" />
                                                                                    <?php if($visibility){?>
                                                                                        <a class="see-more-rules" target="_blank" href= '<?php echo $urlProduct; ?>' title="<?= $nameproduct ?>">
                                                                                            <span class="span-load-more"><?= __('Load more details'); ?> &raquo;</span>
                                                                                        </a>
                                                                                    <?php }?>
                                                                                </li>
                                                                    <?php }}}} ?>
                                                                   
                                                                </ul>
                                                            </div>
                                                        <?php } ?>
                                                    <?php } ?>
                                                </div>
                                            </td>
            <?php } ?>
        <td class="col qty hidden-xs" data hidden-xs-th="<?= $block->escapeHtml(__('Qty')) ?>">
            <?php if(!$isPromoItem){ ?>
                <?php if ($detectMobile->isMobile() == false) { ?>
                    <div class="field qty">
                    <div class="control qty">
                        <label for="cart-<?= $block->escapeHtmlAttr($item->getId()) ?>-qty">
                            <?php if (!$isPromoItem) { ?><span class="quantity-controls quantity-minus change-qty <?= $outOfStock ? "pointer-events" : "" ?> <?= $block->getQty() <= 1 ? "text-secondary" : ""  ?>" id="<?= /* @escapeNotVerified */ $item->getId() ?>-minus-qty">-</span>
                            <input  id="cart-<?= $block->escapeHtmlAttr($item->getId()) ?>-qty"
                                    data-post='<?= $item->getId(); ?>' 
                                    default-stock="<?= $defaultStockconfigurable; ?>" 
                                    oldQty="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                                    id-prd="<?= $item->getId() ?>"
                                    name="cart[<?= $block->escapeHtmlAttr($item->getId()) ?>][qty]"
                                    data-cart-item-id="<?= $block->escapeHtmlAttr($item->getSku()) ?>"
                                    value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                                    type="number"
                                    size="4"
                                    title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                                    class="input-text qty <?= $outOfStock ? "pointer-events" : "" ?> <?= $isPromoItem ? "disabled" : "" ?>"
                                    data-validate="{required:true,'validate-greater-than-zero':true}"
                                    data-role="cart-item-qty"
                                    <?= $isPromoItem ? "disabled" : "" ?>/>
                            <span class="quantity-controls quantity-plus change-qty <?= $outOfStock ? "pointer-events" : "" ?>" id="<?= /* @escapeNotVerified */ $item->getId() ?>-plus-qty">+</span>
                            <?php } else { ?>
                                <span class="quantity">
                                    <?= $block->escapeHtml(__('Qty')) ?>
                                    <?= $block->getQty(); ?>
                                </span>
                            <?php } ?>
                        </label>
                    </div>
                </div>
                <?php if ($messageCTT): ?>
                    <div class="cart-item-message-error">
                        <span class="label-error"><?= $messageCTT; ?></span>
                    </div>
                <?php endif ?>
                <?php } ?>
                <!-- <div class="cart-item-message-error hide-mess-error" id="flag-mess-over-qty-<?= $item->getId() ?>">
                    <span class="label-error"></span>
                </div> -->
                <!-- Item Price -->
                <?php if ($canApplyMsrp) :?>
                    <!-- <td class="col msrp" data-th="<?= $block->escapeHtml(__('Price')) ?>"> -->
                        <span class="pricing msrp">
                            <span class="msrp notice"><?= $block->escapeHtml(__('See price before order confirmation.')) ?></span>
                            <?php $helpLinkId = 'cart-msrp-help-' . $item->getId(); ?>
                            <a href="#" class="action help map"
                            id="<?= ($block->escapeHtmlAttr($helpLinkId)) ?>"
                            data-mage-init='{"addToCart":{
                                                    "helpLinkId": "#<?= $block->escapeJs($block->escapeHtml($helpLinkId)) ?>",
                                                    "productName": "<?= $block->escapeJs($block->escapeHtml($product->getName())) ?>",
                                                    "showAddToCart": false
                                                    }
                                                }'
                            >
                                <span><?= $block->escapeHtml(__("What's this?")) ?></span>
                            </a>
                        </span>
                    <!-- </td> -->
                <?php else :?>
                    <!-- <td class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>"> -->
                        <div class="price-unit-product">
                            <?= $block->getUnitPriceHtml($item) ?><span class="unit-product"><?= $productunit ? '/'.$productunit : ''; ?></span>
                        </div>
                        <?php
                            $priceOriginal = $this->getProduct()->getPrice();
                            $priceFinal= $item->getPriceInclTax();
                            if ($priceFinal < $priceOriginal) {
                            $savePercent = 100 - round(@($priceFinal / $priceOriginal ) * 100);
                            } else {
                            $savePercent = 0;
                            }
                            if ($savePercent != 0) {
                        ?>
                        <div class="checkout-cart-save-price">
                            <span class="save-percent">-<?php echo $savePercent; ?>%</span>
                            <span class="price-original"><span class="price"><?= $checkoutHelper->formatPrice($priceOriginal); ?></span></span>
                        </div>
                        <?php } ?>
                    <!-- </td> -->
                <?php endif; ?>
                <!-- Item Actions -->
                <?php if (!$isPromoItem){ ?>
                <div class="actions-toolbar">
                    <?= /* @noEscape */ $block->getActions($item) ?>
                </div>
                <?php } ?>
            <?php } ?>
        </td>        
        <td class="col subtotal hidden-xs" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
            <?php if(!$isPromoItem){ ?>
                <?php if ($canApplyMsrp) :?>
                    <span class="cart msrp subtotal">--</span>
                <?php else :?>
                    <?= $block->getRowTotalHtml($item) ?>
                    <?php
                        $totalOriginal = $priceOriginal * $item->getQty();
                        $totalFinal= $item->getRowTotalInclTax();
                        $totalSavePercent = 100 - round(@($totalFinal / $totalOriginal ) * 100);
                        if ($totalSavePercent != 0) {
                    ?>
                    <!-- <div class="checkout-cart-save-price">
                        <span class="price-original"><?php //echo $this->convertPrice($totalOriginal, true); ?></span>
                        <span class="save-percent btn btn-danger">-<?php //echo $totalSavePercent; ?>%</span>
                    </div> -->
                    <?php } ?>
                <?php endif; ?>
            <?php } ?>
        </td>
    </tr>
    <!-- <tr class="item-actions">
        <td colspan="4">
            <div class="actions-toolbar">
                <? /* @noEscape */ //$block->getActions($item) ?>
            </div>
        </td>
    </tr> -->
</tbody>


