<?php
/**
 *
 * SM Listing Tabs - Version 2.5.0
 * Copyright (c) 2017 YouTech Company. All Rights Reserved.
 * @license - Copyrighted Commercial Software
 * Author: YouTech Company
 * Websites: http://www.magentech.com
 */

$list = $this->getData('list');
if (sizeof($list) > 1) {
?>
<div class="ltabs-tabs-wrap" tabindex="-1">
	<span class="ltabs-current-select"></span>
	<ul class="ltabs-tabs cf">
		<?php
		$cat_ids = "";
		foreach ($list as $tab) {
			$cat_ids = $cat_ids . $tab['cat_children'] . ",";
			?>
            <li class="ltabs-tab <?php echo isset($tab['sel']) ? '  tab-sel tab-loaded' : ''; ?>  "
                data-tab-id="<?php echo $tab['id_tab']; ?>" data-catids="<?php echo $tab['cat_children'] ?>">
				<span
                        class="ltabs-tab-label">
						<?php echo $tab['name_tab']; ?>
				</span>
			</li>
			<?php
		} ?>
        <!-- <li class="ltabs-tab ltabs-tab-all" data-tab-id="<?php echo "all"; ?>" data-catids="<?php echo $cat_ids ;?>">
            <span class="ltabs-tab-label"><?php echo __('All') ?></span>
        </li> -->
	</ul>
</div>
<?php } ?>