<?php
/**
 *
 * SM Listing Tabs - Version 2.5.0
 * Copyright (c) iOMZone . All Rights Reserved.
 * @license
 * Author: iOMZone
 * Websites: 
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
if ($this->_isAjax()) {
	$products = $this->_ajaxLoad();
	$config   = $this->_getConfig();
} else {
	$config   = $this->getData('config');
	$products = $this->getData('products');
}
$_helper         = $this->helper('Magento\Catalog\Helper\Output');
$_config         = $this->helper('Sm\Market\Helper\Data');
$homeStyle       = $_config->getThemeLayout('home_style');
$viewMode        = 'grid';
$image           = 'category_page_grid';
$showDescription = false;
$templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$type_loadmore   = $config['type_show'] == 'loadmore' ? true : false;
$cls_mark        = $type_loadmore ? ' ltabs-mark ' : '';

$nb_type_show = $config['type_show'];

$nb_rows = 7;
$i       = 0;
$count   = count($products);
/**
 * Position for actions regarding image size changing in vde if needed
 */
$pos = $block->getPositioned();
?>
<div class="<?php /* @escapeNotVerified */
echo $viewMode; ?> products-<?php /* @escapeNotVerified */
echo $viewMode; ?>">
        <?php $iterator = 1; ?>
    <div class="products list items product-items  <?php echo $type_loadmore == false ? ' owl-carousel ' : ''; ?>" <?php echo $type_loadmore ? 'data-liffect="fadeIn"' : ''; ?>>
            <?php /** @var $_product \Magento\Catalog\Model\Product */ 
			$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
			?>
		<?php foreach ($products as $_product):
			$_product = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
			?>
			<?php /* @escapeNotVerified */
			echo ($iterator++ == 1) ? '<div class="item product product-item ' . $cls_mark . '">' : '</div><div class="item product product-item ' . $cls_mark . '">' ?>
            <div class="product-item-info" data-container="product-grid">
					<div class="item-inner">
						<?php
						$productImage = $block->getImage($_product, $image);
						if ($pos != null) {
							$position = ' style="left:' . $productImage->getWidth() . 'px;'
								. 'top:' . $productImage->getHeight() . 'px;"';
						}
						?>
						<?php // Product Image
						?>
                        <div class="box-image">
							<a href="<?php /* @escapeNotVerified */
							echo $_product->getProductUrl(false) ?>" data-url="<?php /* @escapeNotVerified */
							echo $_product->getProductUrl($_product,[]); ?>" class="product photo product-item-photo" tabindex="-1">
								<?php echo $productImage->toHtml(); ?>
							</a>

                            <!--LABEL PRODUCT-->							
							<?php
							$now      = date("Y-m-d");
							$newsFrom = substr($_product->getNewsFromDate(), 0, 10);
							$newsTo   = substr($_product->getNewsToDate(), 0, 10);


							if (($newsTo != '' || $newsFrom != '') && $_config->getAdvanced('show_newlabel')) {
								if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) { ?>
                                    <div class="label-product label-new">
											<span class="new-product-icon"><?php echo __('New'); ?></span>
										</div>
								<?php }
							} ?>
                            <!--END LABEL PRODUCT-->
						</div>
						
						<div class="product details product-item-details box-info">
							<?php
							$_productNameStripped = $block->stripTags($_product->getName(), null, true);
							?>
                            <h2 class="product name product-item-name product-name">
								<a class="product-item-link"
                                   href="<?php /* @escapeNotVerified */
								   echo $_product->getProductUrl() ?>">
									<?php /* @escapeNotVerified */
									echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
								</a>
							</h2>
							<?php //echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>
							<?php /* @escapeNotVerified */
							echo $block->getProductPrice($_product) ?>
							<?php echo $block->getProductDetailsHtml($_product); ?>

							<?php
							if ((int)$config['display_countdown'] && !empty($_product->getSpecialPrice()) && !empty($_product->getSpecialToDate())) {
								$specialToDate = $_product->getSpecialToDate();
								?>
                                <div class="deals-countdown" data-timer="<?php echo date("Y/m/d H:i:s", strtotime($specialToDate)); ?>">
								<div class="deals-time time-day"><div class="num-time"></div><div class="title-time"></div></div>
								<div class="deals-time time-hours"><div class="num-time"></div><div class="title-time"></div></div>
								<div class="deals-time time-mins"><div class="num-time"></div><div class="title-time"></div></div>
								<div class="deals-time time-secs"><div class="num-time"></div><div class="title-time"></div></div>
							</div>
							<?php } ?>							
						</div>
					</div>
                </div>
			<?php echo ($iterator == count($products) + 1) ? '</div>' : '' ?>
		<?php endforeach; ?>
        </div>
    </div>
