<?php
/**
 *
 * SM Listing Tabs - Version 2.5.0
 * Copyright (c) iOMZone . All Rights Reserved.
 * @license
 * Author: iOMZone
 * Websites:
 */

$config            = $this->getData('config');
$_cfg              = $this->_setSerialize($config);
$tag_id            = $this->getData('tagid');
$tag_int_id        = $this->getData('tag_int_id');
$_config           = $this->helper('Sm\Market\Helper\Data');
$homeStyle         = $_config->getThemeLayout('home_style');
$enableLadyLoading = $_config->getAdvanced('enable_ladyloading');
$responsive_items = isset($config['responsive_items']) ? $config['responsive_items'] : 0;
$slideby_matched_items = isset($config['slideby_matched_items']) ? $config['slideby_matched_items'] : 0;
//var_dump($list);
?>
<script type="text/javascript">
    var isGuest = '<?php echo $this->_isGuest(); ?>';
 require(['jquery', 'mageplaza/core/owl.carousel'], function ($) {
     ;
     (function (element) {
         var el = $(element),
             tabs_wrap = $('.ltabs-tabs-wrap', el),
             tab = $('.ltabs-tab', el),
             tab_active = $('.ltabs-tab.tab-sel .ltabs-tab-label', tabs_wrap),
             tab_content = $('.ltabs-items', el),
             ajax_url = '<?php echo $this->getAjaxUrl(); ?>',
             btn_loadmore = $('.ltabs-loadmore-btn', el),
             type_loadmore = <?php echo $config['type_show'] == 'loadmore' ? 'true' : 'false'; ?>,
             place_holder_tab = $('.ltabs-current-select', el),
             nb_column1 = 2, nb_column2 = 2, nb_column3 = 3, nb_column4 = 4, nb_column5 = 4, margin = 15;
             stagePadding = 0;
             
         var slide_by1 = 1, slide_by2 = 1, slide_by3 = 1, slide_by4 = 1, slide_by5 = 1;
        <?php 
            if($responsive_items != 0){
                $responsive_items = explode(',', $responsive_items);
        ?>
            nb_column1 = <?= $responsive_items[0]; ?>, nb_column2 = <?= $responsive_items[1]; ?>, nb_column3 = <?= $responsive_items[2]; ?>, nb_column4 = <?= $responsive_items[3]; ?>, nb_column5 = <?= $responsive_items[4]; ?>;
        <?php
            }elseif($responsive_items == 0 && $homeStyle == 'home-1'){ 
        ?>
            nb_column1 = 2, nb_column2 = 2, nb_column3 = 3, nb_column4 = 4, nb_column5 = 6;
        <?php 
            } 
        ?>
        <?php
            if($slideby_matched_items){
        ?>
            slide_by1 = nb_column1, slide_by2 = nb_column2, slide_by3 = nb_column3, slide_by4 = nb_column4, slide_by5 = nb_column5;
        <?php
            }
        ?>

         var _interval = setInterval(function () {
             if (document.readyState === 'complete') {
                 clearInterval(_interval);
                 el.removeClass('ltabs-loading-first');
                 _runAllScript();
             }
         }, 500);

         function _runAllScript() {
             place_holder_tab.text(tab_active.text());
             tabs_wrap.on('click', function (e) {
                 e.preventDefault();
                 var _that = $(this);
                 _that.toggleClass('active');
                 return false;
             });
             tab.off('click').on('click', function (e) {
                 e.preventDefault();
                 var _self = $(this);
                 if (_self.hasClass('tab-sel')) return false;
                 tab.removeClass('tab-sel');
                 _self.addClass('tab-sel');
                 place_holder_tab.text($('.ltabs-tab-label', _self).text());
                 var tab_id = _self.attr('data-tab-id'),
                     catids = _self.attr('data-catids'),
                     items_active = $('.ltabs-items-' + tab_id, el),
                     loading = $('.ltabs-loading', items_active),
                     loaded = items_active.hasClass('ltabs-items-loaded');
                 // var viewedProductIds =  Object.keys(JSON.parse(window.localStorage.getItem('recently_viewed_product')));
                 var viewedProductIds = {}
                 if(window.localStorage.getItem('recently_viewed_product')){
                    viewedProductIds = Object.keys(JSON.parse(window.localStorage.getItem('recently_viewed_product')));
                 }
                 tab_content.removeClass('ltabs-items-selected');
                 items_active.addClass('ltabs-items-selected');

                 if (!loaded && !items_active.hasClass('ltabs-process')) {
                     items_active.addClass('ltabs-process');
                     loading.show();
                     $.ajax({
                         type: 'POST',
                         url: ajax_url,
                         data: {
                             viewed_product_ids: viewedProductIds,
                             is_ajax_listing_tabs: 1,
                             ajax_listingtabs_start: 0,
                             tab_id: tab_id,
                             catids: catids,
                             moduleid: '<?php echo $tag_id; ?>',
                             config: <?php echo $_cfg; ?>
                         },
                         success: function (data) {
                             if (data.items_markup != '') {
                                 $('.ltabs-items-inner', items_active).html(data.items_markup);
                                 items_active.addClass('ltabs-items-loaded').removeClass('ltabs-process');
                                 if (type_loadmore) {
                                     $('.product-item', items_active).removeAttr('style');
                                     $('.product-items', items_active).removeClass('play');
                                     $('.product-item', items_active).addClass('ltabs-mark');
                                     animatesItems(items_active);
                                 } else {
                                     _runOwlCarousel(items_active);
                                 }
                                 $(document).trigger("afterAjaxProductsLoaded");
                                 loading.remove();
                                 updateStatus(items_active);
                                 <?php if($enableLadyLoading){ ?>
                                 $(document).trigger("afterAjaxLazyLoad");
                                 <?php } ?>
                             }
                         },
                         dataType: 'json'
                     });

                 } else {
                     if (type_loadmore) {
                         $('.product-item', items_active).removeAttr('style');
                         $('.product-items', items_active).removeClass('play');
                         $('.product-item', items_active).addClass('ltabs-mark');
                         animatesItems(items_active);
                     } else {
                         var owl = $('.owl-carousel', items_active);
                         owl = owl.data('owlCarousel');
                         if (typeof owl !== 'undefined')
                             owl.onResize();
                         else {
                             _runOwlCarousel(items_active);
                         }

                     }
                 }
             });

             btn_loadmore.off('click').on('click', function (e) {
                 e.preventDefault();
                 var _self = $(this);
                 if (_self.hasClass('loaded') || _self.hasClass('loading')) {
                     return false;
                 } else {
                     _self.addClass('loading');
                     $('.ltabs-image-loading', _self).css({display: 'inline-block'});
                     var rl_start = _self.parent().attr('data-rl_start'),
                         catids = _self.parent().attr('data-catids'),
                         tab_id = _self.parent().attr('data-tab-id'),
                         items_active = $('.ltabs-items-' + tab_id, el);
                     var viewedProductIds = Object.keys(JSON.parse(window.localStorage.getItem('recently_viewed_product')));
                     $.ajax({
                         type: 'POST',
                         url: ajax_url,
                         data: {
                             viewed_product_ids: viewedProductIds,
                             is_ajax_listing_tabs: 1,
                             ajax_listingtabs_start: rl_start,
                             tab_id: tab_id,
                             catids: catids,
                             moduleid: '<?php echo $tag_id; ?>',
                             config: <?php echo $_cfg; ?>
                         },
                         success: function (data) {
                             if (data.items_markup != '') {
                                var countItems = $('.product-item', $(data.items_markup)).length;
                                 $('.product-item', $(data.items_markup)).insertAfter($('.product-item:last-child', items_active));
                                 $('.ltabs-image-loading', _self).css({display: 'none'});
                                 animatesItems(items_active);
                                 if (isGuest){
                                    updateStatusGuest(items_active,countItems);
                                 }else{
                                    updateStatus(items_active);
                                 }
                                 $(document).trigger("afterAjaxProductsLoaded");
                                 <?php if($enableLadyLoading){ ?>
                                 $(document).trigger("afterAjaxLazyLoad");
                                 <?php } ?>
                             }
                         }, dataType: 'json'
                     });
                 }
                 return false;
             });

             function animatesItems(elem) {
                 var _item = $('.product-item.ltabs-mark', elem);
                 _item.stop(true, true).each(function (i) {
                     var newDelay = i * 200,
                         duration = 400;
                     $(this).attr("style", "-webkit-animation-delay:" + newDelay + "ms; "
                         + "-moz-animation-delay:" + newDelay + "ms; "
                         + "-o-animation-delay:" + newDelay + "ms; "
                         + "animation-delay:" + newDelay + "ms; "
                         + "-webkit-animation-duration:" + duration + "ms;"
                         + "-moz-animation-duration:" + duration + "ms;"
                         + "-o-animation-duration:" + duration + "ms;"
                         + "animation-duration:" + duration + "ms;");
                     if (i == _item.size() - 1) {
                         $('.product-items', elem).fadeIn(newDelay).addClass("play");
                         $('.product-item', elem).removeClass('ltabs-mark');
                     }
                 });
             }

             function updateStatus($el) {
                 $('.ltabs-loadmore-btn', $el).removeClass('loading');
                 var countitem = $('.product-item', $el).length;
                 $('.ltabs-image-loading', $el).css({display: 'none'});
                 $('.ltabs-loadmore-btn', $el).parent().attr('data-rl_start', countitem);
                 var rl_total = $('.ltabs-loadmore-btn', $el).parent().attr('data-rl_total');
                 var rl_load = $('.ltabs-loadmore-btn', $el).parent().attr('data-rl_load');
                 var rl_allready = $('.ltabs-loadmore-btn', $el).parent().attr('data-rl_allready');

                 if (countitem >= rl_total) {
                     $('.ltabs-loadmore-btn', $el).css({display: 'none'});
                     // $('.ltabs-loadmore-btn', $el).addClass('loaded');
                     // $('.ltabs-image-loading', $el).css({display: 'none'});
                     // $('.ltabs-loadmore-btn', $el).attr('data-label', rl_allready);
                     // $('.ltabs-loadmore-btn', $el).removeClass('loading');
                 }
                 _displayCountDown($el);
             }
             function updateStatusGuest($el,countItemRequest) {
                 $('.ltabs-loadmore-btn', $el).removeClass('loading');
                 var countitem = $('.product-item', $el).length;
                 var rl_load = $('.ltabs-loadmore-btn', $el).parent().attr('data-rl_load');
                 $('.ltabs-image-loading', $el).css({display: 'none'});
                 $('.ltabs-loadmore-btn', $el).parent().attr('data-rl_start', countitem);
                 var rl_allready = $('.ltabs-loadmore-btn', $el).parent().attr('data-rl_allready');
                 if (countItemRequest < rl_load) {
                     $('.ltabs-loadmore-btn', $el).css({display: 'none'});
                     // $('.ltabs-loadmore-btn', $el).addClass('loaded');
                     // $('.ltabs-image-loading', $el).css({display: 'none'});
                     // $('.ltabs-loadmore-btn', $el).attr('data-label', rl_allready);
                     // $('.ltabs-loadmore-btn', $el).removeClass('loading');
                 }else{
                    $('.ltabs-loadmore-btn', $el).css({display: 'inline-block'});
                 }
                 _displayCountDown($el);
             }

             function _countDown(date, id) {
                 dateNow = new Date();
                 amount = date.getTime() - dateNow.getTime();
                 delete dateNow;
                 if (amount < 0) {
                     id.html("Now!");
                 } else {
                     days = 0;
                     hours = 0;
                     mins = 0;
                     secs = 0;
                     out = "";
                     amount = Math.floor(amount / 1000);
                     days = Math.floor(amount / 86400);
                     amount = amount % 86400;
                     hours = Math.floor(amount / 3600);
                     amount = amount % 3600;
                     mins = Math.floor(amount / 60);
                     amount = amount % 60;
                     secs = Math.floor(amount);
                     $(".time-day .num-time", id).text(days);
                     $(".time-day .title-time", id).text(((days <= 1) ? "<?php echo __('Day')?>" : "<?php echo __('Days')?>"));
                     $(".time-hours .num-time", id).text(hours);
                     $(".time-hours .title-time", id).text(((hours <= 1) ? "<?php echo __('Hour')?>" : "<?php echo __('Hours')?>"));
                     $(".time-mins .num-time", id).text(mins);
                     $(".time-mins .title-time", id).text(((mins <= 1) ? "<?php echo __('Min')?>" : "<?php echo __('Mins')?>"));
                     $(".time-secs .num-time", id).text(secs);
                     $(".time-secs .title-time", id).text(((secs <= 1) ? "<?php echo __('Sec')?>" : "<?php echo __('Secs')?>"));
                     setTimeout(function () {
                         _countDown(date, id)
                     }, 1000);
                 }
             }

             function _displayCountDown($el) {
                 if ($(".deals-countdown", $el).length) {
                     $(".deals-countdown", $el).each(function () {
                         var timer = $(this).data('timer');
                         var data = new Date(timer);
                         _countDown(data, $(this));
                     });
                 }
             }

             function _runOwlCarousel(el) {
                 $('.owl-carousel', el).owlCarousel({
                     loop: false,
                     nav: true,
                     dots: false,
                     autoplay: false,
                     autoplayHoverPause: true,
                     margin: margin,
                     stagePadding: stagePadding,
                     responsive: {
                         0: {
                             items: nb_column1, slideBy: slide_by1
                         },
                         480: {
                             items: nb_column2, slideBy: slide_by2
                         },
                         768: {
                             items: nb_column3, slideBy: slide_by3
                         },
                         991: {
                             items: nb_column4, slideBy: slide_by4
                         },
                         1200: {
                             items: nb_column5, slideBy: slide_by5
                         }
                     }
                 });
             }

             if (type_loadmore) {
                 animatesItems($('.ltabs-items.ltabs-items-selected', el));
             } else {
                 _runOwlCarousel($('.ltabs-items.ltabs-items-selected', el));
             }
             _displayCountDown($('.ltabs-items.ltabs-items-selected', el));

             //---> If Guest Fetch first
             if(isGuest){
                //_self.addClass('loading');
                     //$('.ltabs-image-loading', _self).css({display: 'inline-block'});
                     var rl_start = 0,//_self.parent().attr('data-rl_start'),
                         catids = [2],//_self.parent().attr('data-catids'),
                         tab_id = '<?php echo $tag_id; ?>',//_self.parent().attr('data-tab-id'),
                         items_active = $('.ltabs-items-' + tab_id, el);
                     var viewedProductIds = {}
                     if(window.localStorage.getItem('recently_viewed_product')){
                        viewedProductIds = Object.keys(JSON.parse(window.localStorage.getItem('recently_viewed_product')));
                     }
                     $.ajax({
                         type: 'POST',
                         url: ajax_url,
                         data: {
                             viewed_product_ids: viewedProductIds,
                             is_ajax_listing_tabs: 1,
                             ajax_listingtabs_start: rl_start,
                             tab_id: tab_id,
                             catids: catids,
                             moduleid: '<?php echo $tag_id; ?>',
                             config: <?php echo $_cfg; ?>
                         },
                         success: function (data) {
                            //console.log(data);
                            if (data.items_markup != '') {
                                 //$('.product-item', $(data.items_markup)).insertAfter($('.anchor-guest:last-child', items_active));
                                 $('.ltabs-loading').css({display: 'none'});
                                 var countItems = $('.product-item', $(data.items_markup)).length;
                                 
                                 // if empty items -> set viewed container hidden
                                 if(countItems == 0){
                                    $('.viewed-product-container').css({display: 'none'});
                                 }
                                 //$('.anchor-guest').parent().html($('.product-item', $(data.items_markup)));
                                 $('.ltabs-items-inner', items_active).html(data.items_markup);
                                 //$('.anchor-guest').parent().html(data.items_markup);
                                 if (type_loadmore) {
                                     animatesItems(items_active);
                                 } else {
                                     _runOwlCarousel(items_active);
                                 }
                                 if (isGuest){
                                    updateStatusGuest(items_active,countItems);
                                 }else{
                                    updateStatus(items_active);
                                 }

                                 $(document).trigger("afterAjaxProductsLoaded");
                                 <?php if($enableLadyLoading){ ?>
                                 $(document).trigger("afterAjaxLazyLoad");
                                 <?php } ?>
                            }
                         }, dataType: 'json'
                     });
             }
         }
     })("#<?php echo $tag_id; ?>");
 });
</script>
