<?php
    $postCollectionCTT = $this->getCollection();
    $nameCategory = $this->getNameCategory();
    $lastVendorWebsiteId = 0;
    $url_main =  $this->getUrlCate();
    $helper = $this->helper('Chottvn\Blog\Helper\Data');
?>
<?php if (count($postCollectionCTT) > 0) {?>
<?php 
    $arrayIds = array();
?>
<?php foreach ($postCollectionCTT as $key => $post): ?>
    <?php 
        $vendorId = $post->getId();
        $publishDate = $post->getPublishDate();
        $arrayIds[] = $publishDate;
    ?>
       <div class="row">
            <div class="card-horizontal">
                <div class="c-display-flex">
                    <div class="col-6 flex-left">
                        <div class="post-thumb">
                            <a href="<?php echo $post->getUrl() ?>" class="thumb-zoom" title="<?php echo $post->getName() ?>">
                                <?php
                                    $url_image = $block->resizeImage($post->getImage()); 
                                    // $url_resize = $url_main."timthumb.php?src=".$url_image."&w=150&h=109";
                                ?>
                                <img title="<?php echo $post->getName() ?>" alt="<?php echo $post->getName() ?>" class="card-img-top card-img-top-resize border-small-image" src="<?php echo $url_image; ?>">
                                <?php if($post->getIsVideo()== 1): ?>
                                        <img src="<?php echo $block->getViewFileUrl('images/play-icon.png'); ?>" class="img-overlay-small" style="width: 30.6px;">
                                <?php endif;?>
                            </a>
                        </div>
                    </div>
                    <div class="col-6 flex-right">
                        <div class="card-body">
                            <h5 class="card-title">
                                <a class="c-post-title-resize block-with-text-title" href="<?php echo $post->getUrl() ?>" title="<?php echo $post->getName() ?>"><?php echo $post->getName() ?></a>
                            </h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
<?php endforeach; ?>
<!-- Set last id -->
 <?php 
    $lastVendorWebsiteId = min($arrayIds); 
?>
<script type="text/javascript">
            require(['jquery',
            ], function ($) {
                $(document).ready(function () {
                    $('#blog_mobile_show_more').data("pid", '<?php echo $lastVendorWebsiteId; ?>');
                });
            });
</script>
<?php } ?>
<?php
    $helper = $this->helper('Chottvn\Blog\Helper\Data');
    $postCollectionCTThide = $helper->checkPostCollectionTagCTT($lastVendorWebsiteId,'mobile'); 
?>
<?php if (count($postCollectionCTThide) < 5) {?>
    <script type="text/javascript">
            require(['jquery',
            ], function ($) {
                $(document).ready(function () {
                    $('#load-more-mobile-blog-ctt').hide();
                });
            });
    </script>
<?php } ?>