<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_CrossLinks
 */
?>
<?php
/* @var $block \Amasty\CrossLinks\Block\Adminhtml\Link\Edit\Form\Renderer\ReferenceResource */
$element = $block->getElement();
$note = $element->getNote() ?
    '<div class="note admin__field-note" id="' . $element->getId() . '-note">' . $element->getNote() . '</div>' :
    '';
$elementBeforeLabel = $element->getExtType() == 'checkbox admin__control-checkbox' ||
    $element->getExtType() == 'radio admin__control-radio';
$addOn = ($element->getBeforeElementHtml() || $element->getAfterElementHtml()) && !$element->getNoWrapAsAddon();
$fieldId = ($element->getHtmlContainerId()) ? ' id="' . $element->getHtmlContainerId() . '"' : '';
$fieldClass = "admin__field field field-{$element->getId()} {$element->getCssClass()}";
$fieldClass .= ($elementBeforeLabel) ? ' choice' : '';
$fieldClass .= ($addOn) ? ' with-addon' : '';
$fieldClass .= ($element->getRequired()) ? ' required _required' : '';
$fieldClass .= ($note) ? ' with-note' : '';
$fieldClass .= (!$element->getLabelHtml()) ? ' no-label' : '';

$fieldAttributes = $fieldId . ' class="' . $fieldClass . '" '
    . $block->getUiId('form-field', $element->getId())
    . ($element->getFieldExtraAttributes() ? ' ' . $element->getFieldExtraAttributes() : '');
?>

<script>
    require([
        'Amasty_CrossLinks/js/reference/resource/manager'
    ], function () {
        ResourceManager.init({
            <?= $block->getReferenceResourceText() ? "referenceResourceText:'{$block->getReferenceResourceText()}'," : ''?>
            <?= $block->getReferenceResourceValue() ? "referenceResourceValue:'{$block->getReferenceResourceValue()}'" : ''?>
        });
    })
</script>

<?php if (!$element->getNoDisplay()) : ?>
    <?php if ($element->getType() == 'hidden') : ?>
        <?= $element->getElementHtml() ?>
    <?php else : ?>
        <div <?= $fieldAttributes ?>>
            <?php if ($elementBeforeLabel) : ?>
                <?= $element->getElementHtml() ?>
                <?= $element->getLabelHtml('', $element->getScopeLabel()) ?>
                <?= /* @escapeNotVerified */ $note ?>
            <?php else : ?>
                <?= $element->getLabelHtml('', $element->getScopeLabel()) ?>
                <div class="admin__field-control control">
                    <?= $element->getElementHtml(); ?>
                    <?= $block->getCatalogFieldHtml(); ?>
                    <div class="control-category-picker" style="display:none;">
                        <?= /* @escapeNotVerified */ $block->getCategoryPickerHtml() ?>
                    </div>
                    <div class="control-product-picker"  style="display:none;">
                        <?= /* @escapeNotVerified */ $block->getProductPickerHtml() ?>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
