<?php
/*------------------------------------------------------------------------
# SM Filter Products - Version 1.0.0
# Copyright (c) 2016 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

use Magento\Framework\App\Action\Action;

?>

<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper            = $this->helper('Magento\Catalog\Helper\Output');
$_imagehelper       = $this->helper('Magento\Catalog\Helper\Image');

$_config       = $this->helper('Sm\Market\Helper\Data');
$keep_ratio    = $_config->getCategoryView('keep_image');
$image_width   = $_config->getCategoryView('image_width');
$image_height  = $_config->getCategoryView('image_height');
$product_hover = $_config->getCategoryView('hover_image_effect');

$show_addtocart     = $_config->getAdvanced('show_addtocart_button');
$show_addtocompare  = $_config->getAdvanced('show_compare_button');
$show_addtowishlist = $_config->getAdvanced('show_wishlist_button');

$show_newlabel  = $_config->getAdvanced('show_newlabel');
$new_label_text = $_config->getAdvanced('new_label_text');

$show_salelabel  = $_config->getAdvanced('show_salelabel');
$sale_label_text = $_config->getAdvanced('sale_label_text');
$show_pecent     = $_config->getAdvanced('show_salediscount');

$enableLadyLoading = $_config->getAdvanced('enable_ladyloading');
$mediaSrc          = $_config->getMediaUrl();
if ($enableLadyLoading) {
	$imgClass = 'lazyload';
} else {
	$imgClass = '';
}
?>

<div class="filter-products">
	<?php if (!empty($this->_getConfig('title_module'))) { ?>
        <div class="primary-title">
			<h2><?php echo $this->_getConfig('title_module'); ?></h2>
		</div>
	<?php } ?>

	<?php if (!$_productCollection->count()): ?>
        <div class="message info empty"><div><?php /* @escapeNotVerified */
				echo __('We can\'t find products matching the selection.') ?></div></div>
	<?php else: ?>
		<?php
		$image        = 'category_page_grid';
		$hover_image  = 'category_page_grid-hover';
		$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

		$tag_id = "sm_filterproducts_" . time() . rand() . "";
		?>

		
        <div class="scroll-block" id="<?php echo $tag_id; ?>">
			<div class="grid-product-type products list items product-items item-table">
				<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
				<?php foreach ($_productCollection as $_product): ?>
                    <div class="item product product-item item-table-cell">
						<div class="item-inner">
							<div class="product-item-info" data-container="product-grid">
								<?php
								if ((int)$this->_getConfig('display_countdown') && !empty($_product->getSpecialPrice()) && !empty($_product->getSpecialToDate())) {
									$specialToDate = $_product->getSpecialToDate();
									?>
                                    <div class="deals-countdown" data-timer="<?php echo date("Y/m/d H:i:s", strtotime($specialToDate)); ?>">
										<div class="deals-time time-day"><div class="num-time"></div><div class="title-time"></div></div>
										<div class="deals-time time-hours"><div class="num-time"></div><div class="title-time"></div></div>
										<div class="deals-time time-mins"><div class="num-time"></div><div class="title-time"></div></div>
										<div class="deals-time time-secs"><div class="num-time"></div><div class="title-time"></div></div>
									</div>
								<?php } ?>

                                <div class="product-item-image">
									<a href="<?php /* @escapeNotVerified */
									echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
										<?php
										if ($keep_ratio)
											$productImage = $_imagehelper->init($_product, $image)->constrainOnly(false)->keepAspectRatio(true)->keepFrame(false)->resize($image_width);
										else
											$productImage = $_imagehelper->init($_product, $image)->resize($image_width, $image_height);
										$productImageUrl = $productImage->getUrl();
										?>

                                        <span class="product-image-wrapper">
											<img class="product-image-photo default_image <?php echo $imgClass; ?>"
												<?php if ($enableLadyLoading) { ?>
                                                    src="<?php echo $mediaSrc . 'lazyloading/blank.png'; ?>"
                                                    data-src="<?php echo $productImageUrl; ?>"
												<?php } else { ?>
                                                    src="<?php echo $productImageUrl; ?>"
												<?php } ?>

                                                 alt="<?php echo $productImage->getLabel(); ?>"
                                            />

											<?php if ($product_hover == 'second_image') { ?>
												<?php
												if ($keep_ratio)
													$productHoverImage = $_imagehelper->init($_product, $hover_image)->constrainOnly(false)->keepAspectRatio(true)->keepFrame(false)->resize($image_width);
												else
													$productHoverImage = $_imagehelper->init($_product, $hover_image)->resize($image_width, $image_height);

												$productHoverImageUrl = $productHoverImage->getUrl();
												?>

												<?php if ($productImageUrl != str_replace("/thumbnail/", "/small_image/", $productHoverImageUrl)): ?>
                                                    <img class="product-image-photo hover_image"
                                                         src="<?php echo $productHoverImageUrl; ?>"

														<?php if ($enableLadyLoading) { ?>
                                                            src="<?php echo $mediaSrc . 'lazyloading/blank.png'; ?>"
                                                            data-src="<?php echo $productHoverImageUrl; ?>"
														<?php } else { ?>
                                                            src="<?php echo $productHoverImageUrl; ?>"
														<?php } ?>

                                                         alt="<?php echo $productHoverImage->getLabel(); ?>"
                                                    />
												<?php endif; ?>
											<?php } ?>
										</span>
										
									</a>

									<div class="actions-secondary" data-role="add-to-links">
										<?php if ($show_addtowishlist) { ?>
											<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                <a href="#"
                                                   data-post='<?php /* @escapeNotVerified */
												   echo $block->getAddToWishlistParams($_product); ?>'
                                                   class="action towishlist" data-action="add-to-wishlist"
                                                   title="<?php /* @escapeNotVerified */
												   echo __('Add to Wish List') ?>">
													<span><?php /* @escapeNotVerified */
														echo __('Add to Wish List') ?></span>
												</a>
											<?php endif; ?>
										<?php } ?>

										<?php if ($show_addtocompare) { ?>
											<?php if ($block->getAddToCompareUrl()): ?>
												<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                <a href="#" class="action tocompare"
                                                   data-post='<?php /* @escapeNotVerified */
												   echo $compareHelper->getPostDataParams($_product); ?>'
                                                   title="<?php /* @escapeNotVerified */
												   echo __('Add to Compare') ?>">
													<span><?php /* @escapeNotVerified */
														echo __('Add to Compare') ?></span>
												</a>
											<?php endif; ?>
										<?php } ?>
									</div>


                                    <!--Label-->
									<?php
									if ($show_newlabel) {
										$now      = date("Y-m-d");
										$newsFrom = substr($_product->getData('news_from_date'), 0, 10);
										$newsTo   = substr($_product->getData('news_to_date'), 0, 10);

										if ($newsTo != '' || $newsFrom != '') {
											if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {
												echo '<div class="product-label new-label">' . $new_label_text . '</div>';
											}
										}
									}

									if ($show_salelabel) {
										$orgprice        = $_product->getPrice();
										$specialprice    = $_product->getSpecialPrice();
										$specialfromdate = $_product->getSpecialFromDate();
										$specialtodate   = $_product->getSpecialToDate();
										$today           = time();

										if (!$specialprice)
											$specialprice = $orgprice;

										if ($specialprice < $orgprice) {
											if ((is_null($specialfromdate) && is_null($specialtodate)) || ($today >= strtotime($specialfromdate) && is_null($specialtodate)) || ($today <= strtotime($specialtodate) && is_null($specialfromdate)) || ($today >= strtotime($specialfromdate) && $today <= strtotime($specialtodate))) {
												if ($show_pecent) {
													$save_percent = 100 - round(($specialprice / $orgprice) * 100);
													echo '<div class="product-label sale-label">' . '-' . $save_percent . '%' . '</div>';
												} else {
													echo '<div class="product-label sale-label">' . $sale_label_text . '</div>';
												}
											}
										}
									}
									?>
                                    <!--End label-->
								</div>
								
								<div class="product details product-item-details">
									<?php
									$_productNameStripped = $block->stripTags($_product->getName(), null, true);
									?>
                                    <div class="product name product-item-name">
										<a class="product-item-link"
                                           href="<?php /* @escapeNotVerified */
										   echo $_product->getProductUrl() ?>">
											<?php /* @escapeNotVerified */
											echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
										</a>
									</div>

									<?php echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>

									<?php /* @escapeNotVerified */
									echo $block->getProductPrice($_product) ?>

									<?php echo $block->getProductDetailsHtml($_product); ?>

									<?php if ($show_addtocart) { ?>
                                        <div class="product-item-inner">
										<div class="product actions product-item-actions">
											<div class="actions-primary">
												<?php if ($_product->isSaleable()): ?>
													<?php $postParams = $this->getAddToCartPostParams($_product);
													$objectManager    = \Magento\Framework\App\ObjectManager::getInstance();
													$session          = $objectManager->get('\Magento\Framework\View\Element\FormKey');
													?>
                                                    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
													echo $postParams['action']; ?>" method="post">
														<input type="hidden" name="product" value="<?php /* @escapeNotVerified */
														echo $postParams['data']['product']; ?>">
														<input type="hidden" name="<?php /* @escapeNotVerified */
														echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */
														echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
														<?php echo $block->getBlockHtml('formkey') ?>
                                                        <input name="form_key" type="hidden" value="<?php echo $session->getFormKey(); ?>"/>
														<button type="submit"
                                                                title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                                class="action tocart primary">
															<span><?php /* @escapeNotVerified */
																echo __('Add to Cart') ?></span>
														</button>
													</form>
												<?php else: ?>
													<?php if ($_product->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */
																echo __('In stock') ?></span></div>
													<?php else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */
																echo __('Out of stock') ?></span></div>
													<?php endif; ?>
												<?php endif; ?>
											</div>
										</div>
									</div>
									<?php } ?>
								</div>

								
							</div>
						</div>
					</div>
				<?php endforeach; ?>
			</div>
		</div>

        <script type="text/javascript">
			require([
                'jquery'
            ], function ($) {
                var $element = $('#<?php echo $tag_id ?>');

                function CountDown(date, id) {
                    dateNow = new Date();
                    amount = date.getTime() - dateNow.getTime();
                    delete dateNow;
                    if (amount < 0) {
                        id.html("Now!");
                    } else {
                        days = 0;
                        hours = 0;
                        mins = 0;
                        secs = 0;
                        out = "";
                        amount = Math.floor(amount / 1000);
                        days = Math.floor(amount / 86400);
                        amount = amount % 86400;
                        hours = Math.floor(amount / 3600);
                        amount = amount % 3600;
                        mins = Math.floor(amount / 60);
                        amount = amount % 60;
                        secs = Math.floor(amount);
                        $(".time-day .num-time", id).text(days);
                        $(".time-day .title-time", id).text(((days <= 1) ? "Day" : "Days"));
                        $(".time-hours .num-time", id).text(hours);
                        $(".time-hours .title-time", id).text(((hours <= 1) ? "Hour" : "Hours"));
                        $(".time-mins .num-time", id).text(mins);
                        $(".time-mins .title-time", id).text(((mins <= 1) ? "Min" : "Mins"));
                        $(".time-secs .num-time", id).text(secs);
                        $(".time-secs .title-time", id).text(((secs <= 1) ? "Sec" : "Secs"));
                        setTimeout(function () {
                            CountDown(date, id)
                        }, 1000);
                    }
                }

                $(".deals-countdown", $element).each(function () {
                    var timer = $(this).data('timer');
                    var data = new Date(timer);
                    CountDown(data, $(this));
                });
            });
		</script>
		<?php if (!$block->isRedirectToCartEnabled()) : ?>
			
        <script type="text/x-magento-init">
			{
				"[data-role=tocart-form], .form.map.checkout": {
					"catalogAddToCart": {}
				}
			}
			</script>
	<?php endif; ?>
	<?php endif; ?>
</div>
	
	
