<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
//var_dump(get_class_methods($priceModel));die;

// get helper data format
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$checkoutHelper = $objectManager->get('Chottvn\PriceDecimal\Helper\Data');
?>

<?php
// If (Price = 0), Show Contact us
    if ( $finalPriceModel->getAmount()->getValue() <= 0){

        echo '<span class="price contact-custom price-label">'.__('Price: ').'</span>';
        echo '<span class="price contact-custom text-label">'.__('Price Contact').'</span>';
    }
    else{
?>

<?php if ($block->hasSpecialPrice()): ?>
    <span class="ctt-special-price">
        <span class="price-container price-final_price tax weee">
            <span id="product-price-<?php echo $block->getPriceId(); ?>" data-price-amount="<?php echo $finalPriceModel->getAmount()->getValue(); ?>" data-price-type="finalPrice" class="price-wrapper ">
                <span class="price"><?php echo $checkoutHelper->formatPrice($finalPriceModel->getAmount()->getValue()); ?></span></span>
        </span>

        <?php 
            // /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
            // //'display_label'     => __('Price'),
            // 'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            // 'price_type'        => 'finalPrice',
            // 'include_container' => true,
            // 'schema' => $schema
            // ]);
        ?>
        <span class="include-vat">
            <?php echo __('Include VAT') ?>
        </span>
    </span>
    <span class="ctt-old-price">
        <span class="price-container price-final_price tax weee">
            <span id="old-price-<?php echo $block->getPriceId(); ?>" data-price-amount="<?php echo $priceModel->getAmount()->getValue(); ?>" data-price-type="oldPrice" class="price-wrapper ">
                <span class="price"><?php echo $checkoutHelper->formatPrice($priceModel->getAmount()->getValue()); ?></span></span>
        </span>
        <?php 
            // /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
            // // 'display_label'     => __('Regular Price'),
            // 'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            // 'price_type'        => 'oldPrice',
            // 'include_container' => true,
            // 'skip_adjustments'  => true
            // ]); 
        ?>
    </span>
    <?php $save_percent = 100 - round(($finalPriceModel->getAmount()->getValue() / $priceModel->getAmount()->getValue()) * 100); ?>
    <span class="ctt-save-percent">
        <?php echo '-' . $save_percent . '%'; ?>
    </span>
<?php else: ?>
    <span class="ctt-special-price">
        <span class="price-container price-final_price tax weee">
            <span id="product-price-<?php echo $block->getPriceId(); ?>" data-price-amount="<?php echo $finalPriceModel->getAmount()->getValue(); ?>" data-price-type="finalPrice" class="price-wrapper ">
                <span class="price"><?php echo $checkoutHelper->formatPrice($finalPriceModel->getAmount()->getValue()); ?></span></span>
        </span>
        <?php 
            // /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
            // //'display_label'     => __('Price'),
            // 'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            // 'price_type'        => 'finalPrice',
            // 'include_container' => true,
            // 'schema' => $schema
            // ]); 
        ?>
         <span class="include-vat">
            <?php echo __('Include VAT') ?>
        </span>
    </span>
<?php endif; ?>
<span class="include-vat">
    <?php echo __('Include VAT') ?>
</span>
<?php if ($block->showMinimalPrice()): ?>
    <?php if ($block->getUseLinkForAsLowAs()):?>
        <a href="<?= /* @escapeNotVerified */ $block->getSaleableItem()->getProductUrl() ?>" class="minimal-price-link">
            <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
        </a>
    <?php else:?>
        <span class="minimal-price-link">
            <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
        </span>
    <?php endif?>
<?php endif; ?>

<?php } // Else of (Price=0) ?>
