<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php 
    $__item = $block->getItem()->getOrderItem();
    $_item = $block->getItem();
    $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
    if ($childProd = current($__item->getChildrenItems())) {
        $productImage = $_imagehelper->init($childProd->getProduct(), 'category_page_list', array('height' => 80 , 'width'=> 120))->getUrl();
    }
    else {
        $productImage = $_imagehelper->init($__item->getProduct(), 'category_page_list', array('height' => 80 , 'width'=> 120))->getUrl();
    }
?>
<?php $_order = $block->getItem()->getOrderItem()->getOrder() ?>
<tr id="order-item-row-<?= (int) $_item->getId() ?>">
    <td class="image">
        <div class="row">
            <div class="col-md-4 col-sm-4">
                <div class="img-box"><img src="<?= $productImage ?>" title="<?= $block->escapeHtml($_item->getName()) ?>" alt="<?= $block->escapeHtml($_item->getName()) ?>" /></div>
            </div>
            <div class="col-md-8 col-sm-8">
                <a href="<?= $__item->getProduct()->getProductUrl() ?>" class="order-title-sku" target="_blank"><strong class="product name product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong> </br><?= $block->prepareSku($block->getSku()) ?></a>
                <?php if ($_options = $block->getItemOptions()) : ?>
                    <dl class="item options">
                    <?php foreach ($_options as $_option) : ?>
                        <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                        <?php if (!$block->getPrintStatus()) : ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dd<?= (isset($_formatedOptionValue['full_view']) ? ' class="tooltip wrapper"' : '') ?>>
                                <?= $block->escapeHtml($_formatedOptionValue['value']) ?>
                                <?php if (isset($_formatedOptionValue['full_view'])) : ?>
                                <div class="tooltip content">
                                    <dl class="item options">
                                        <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                                        <dd><?= $block->escapeHtml($_formatedOptionValue['full_view']) ?></dd>
                                    </dl>
                                </div>
                                <?php endif; ?>
                            </dd>
                        <?php else : ?>
                            <dd><?= $block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])) ?></dd>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    </dl>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock) : ?>
                    <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
                <?php endif; ?>
                <?= $block->escapeHtml($_item->getDescription()) ?>
            </div>
        </div>
    </td>
    <td class="qty" data-th="<?= $block->escapeHtml(__('Qty Shipped')) ?>"><?= (int) $_item->getQty() ?></td>
</tr>
