<div class="affiliate-register">
	<div class="affiliate-register-img">
		<img style="width: 300px;" class="affiliate-register-success" src="<?= $this->getViewFileUrl('images/access_restricted.jpg');  ?>" alt="Chợ Trưc Tuyến"/>
	</div>
	<div class="affiliate-register-message">
		<p><?= $block->escapeHtmlAttr(__('Affiliate account activation link has expired.')); ?></p>
		<p><?= __("If you have any questions about collaborator's account, please contact Human Resources Department, Online Market Joint Stock Company via email: <a href='mailto:%1'>%1</a>", 'ctv@chotructuyen.co'); ?></p>
	</div>
</div>