
<div class="affiliate-register">
	<div class="affiliate-register-img">
		<img class="affiliate-register-success" src="<?= $this->getViewFileUrl('images/dang_ky_thanh_cong.png');  ?>" alt="Chợ Trưc Tuyến"/>
	</div>
	<div class="affiliate-register-message">
		<p><?= $block->escapeHtmlAttr(__('Affiliate Register Success')); ?></p>
		<p><?= $block->escapeHtmlAttr(__('Affiliate Please Waiting In 48hrs')); ?></p>
	</div>
</div>