<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
// create info
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_config = $this->helper('Sm\Market\Helper\Data');

$zoom_enable = $_config->getProductDetail('use_zoom_image');
$zoom_width  = $_config->getProductDetail('zoom_width');

$thumbstyle    = $_config->getProductDetail('thumbs_style');
$loop          = $_config->getProductDetail('image_loop');
$keyboard      = $_config->getProductDetail('image_keyboard');
$bigNav        = $_config->getProductDetail('image_navigation');
$fullscreen    = $_config->getProductDetail('image_fullscreen');
$thumbs_width  = $_config->getProductDetail('thumbs_width');
$thumbs_height = $_config->getProductDetail('thumbs_height');
$thumbs_nav    = $_config->getProductDetail('thumbs_navigation');

$breakpoints = $_config->getProductDetail('breakpoints_width');

// detect mobile
$detectMobile = $objectManager->get('\Chottvn\Frontend\Helper\DetectMobile');
?>
<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
    <div data-role="loader" class="loading-mask-gallery">
        <div class="loader">
            <img src="<?php /* @escapeNotVerified */
			echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
                 alt="<?php /* @escapeNotVerified */
				 echo __('Loading...') ?>">
        </div>
    </div>
</div>
<!--Fix for jumping content. Loader must be the same size as gallery.-->
<script>
    var config = {
            "width": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_medium', 'width'); ?>,
            "thumbheight": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_small', 'height')
			?: $block->getImageAttribute('product_page_image_small', 'width'); ?>,
            "navtype": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/navtype"); ?>",
            "height": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_medium', 'height'); ?>
        },
        thumbBarHeight = 0,
        loader = document.querySelectorAll('[data-gallery-role="gallery-placeholder"] [data-role="loader"]')[0];

    if (config.navtype === 'horizontal') {
        thumbBarHeight = config.thumbheight;
    }

    loader.style.paddingBottom = ( config.height / config.width * 100) + "%";
</script>
<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": {
					<?php if ($zoom_enable) { ?>
						"enabled": true,
					<?php } else { ?>
						"enabled": false,
					<?php } ?>
					
					"fullscreenzoom":"20",
					"top":"",
					"left":"",
					"height":"",
					
					"eventType":"hover",
					"width": <?php echo $zoom_width; ?>,
					"mode": "outside"
				},
                "data": <?php /* @escapeNotVerified */
	echo $block->getGalleryImagesJson(); ?>,
                "options": {
					<?php if ($thumbstyle == 'horizontal' || $thumbstyle == 'vertical') { ?>
						"nav": "thumbs",
						"navdir": "<?php echo $thumbstyle; ?>",
					<?php } else { ?>
						"nav": "dots",
					<?php } ?>
					
					<?php if ($loop) { ?>
						"loop": true,
					<?php } else { ?>
						"loop": false,
					<?php } ?>
					
					<?php if ($keyboard) { ?>
						"keyboard": true,
					<?php } else { ?>
						"keyboard": false,
					<?php } ?>
					
					<?php if ($bigNav) { ?>
						"arrows": true,
					<?php } else { ?>
						"arrows": false,
					<?php } ?>
					
					<?php if ($fullscreen) { ?>
						"allowfullscreen": true,
					<?php } else { ?>
						"allowfullscreen": false,
					<?php } ?>
                    
                    
                    
                    

                    <?php if (($block->getVar("gallery/caption"))): ?>
                        "showCaption": <?php /* @escapeNotVerified */
		echo $block->getVar("gallery/caption"); ?>,
                    <?php endif; ?>
					
                    "width": "<?php /* @escapeNotVerified */
	echo $block->getImageAttribute('product_page_image_medium', 'width'); ?>",
					
					<?php if ($block->getImageAttribute('product_page_image_medium', 'height') || $block->getImageAttribute('product_page_image_medium', 'width')): ?>
                        "height": <?php /* @escapeNotVerified */
		echo $block->getImageAttribute('product_page_image_medium', 'height')
			?: $block->getImageAttribute('product_page_image_medium', 'width'); ?>,
                    <?php endif; ?>
					
                    "thumbwidth": "<?php echo $thumbs_width; ?>",
                    "thumbheight": "<?php echo $thumbs_height; ?>",

                    <?php if ($block->getVar("gallery/transition/duration")): ?>
                        "transitionduration": <?php /* @escapeNotVerified */
		echo $block->getVar("gallery/transition/duration"); ?>,
                    <?php endif; ?>
                    "transition": "<?php /* @escapeNotVerified */
	echo $block->getVar("gallery/transition/effect"); ?>",
					
					<?php if ($thumbs_nav) { ?>
						"navarrows": true,
					<?php } else { ?>
						"navarrows": false,
					<?php } ?>

                    "navtype": "<?php /* @escapeNotVerified */
	echo $block->getVar("gallery/navtype"); ?>",

					"thumbmargin": <?php echo $_config->getProductDetail('thumbs_margin'); ?>,
					"thumbborderwidth": <?php echo $_config->getProductDetail('thumbs_borderwidth'); ?>
                },
				
                "fullscreen": {
                    "nav": "thumbs",
                    <?php if ($block->getVar("gallery/fullscreen/loop")): ?>
                        "loop": <?php /* @escapeNotVerified */
		echo $block->getVar("gallery/fullscreen/loop"); ?>,
                    <?php endif; ?>
                    "navdir": "<?php /* @escapeNotVerified */
	echo $block->getVar("gallery/fullscreen/navdir"); ?>",
                    <?php if ($block->getVar("gallery/transition/navarrows")): ?>
                        "navarrows": <?php /* @escapeNotVerified */
		echo $block->getVar("gallery/fullscreen/navarrows"); ?>,
                    <?php endif; ?>
                    "navtype": "<?php /* @escapeNotVerified */
	echo $block->getVar("gallery/fullscreen/navtype"); ?>",
                    <?php if ($block->getVar("gallery/fullscreen/arrows")): ?>
                        "arrows": <?php /* @escapeNotVerified */
		echo $block->getVar("gallery/fullscreen/arrows"); ?>,
                    <?php endif; ?>
                    <?php if ($block->getVar("gallery/fullscreen/caption")): ?>
                        "showCaption": <?php /* @escapeNotVerified */
		echo $block->getVar("gallery/fullscreen/caption"); ?>,
                    <?php endif; ?>
                    <?php if ($block->getVar("gallery/fullscreen/transition/duration")): ?>
                        "transitionduration": <?php /* @escapeNotVerified */
		echo $block->getVar("gallery/fullscreen/transition/duration"); ?>,
                    <?php endif; ?>
                    "transition": "<?php /* @escapeNotVerified */
	echo $block->getVar("gallery/fullscreen/transition/effect"); ?>"
                },
				
                "breakpoints":{
					"mobile":{
						"conditions":{
							"max-width":"<?php echo $breakpoints . 'px' ?>"
						},
						
						"options":{
							"options":{
								"nav":"dots"
							},
							
							"magnifierOpts": {
								"enabled": false
							}
						}
					}
				
				}
            }
        }
    }
</script>

<script type='text/javascript'>
require(['jquery','jquery/ui','jquery/jquery.mobile.custom'], function($){
	var $div = $(".gallery-placeholder");
    var html = $div.html();
    var checking = setInterval(function() {
        var newhtml = $div.html();
        if (html != newhtml) {
            myCallback();
        }
    },1000);
    
    function myCallback() {
    	// init gallery html
        $('.catalog-product-view .fotorama').append(getPositionGalleryHtml('init'));

        // check change content
        // on change thumbnail image
	    // var $div_thumb = $(".catalog-product-view .gallery-placeholder .fotorama__nav__shaft");
	    // console.log($div_thumb);
	    // var html_thumb = $div_thumb.html();
	    // var checking_thumb = setInterval(function() {
	    //     var newhtml_thumb = $div_thumb.html();
	    //     console.log(newhtml_thumb);
	    //     if (html_thumb != newhtml_thumb) {
	    //     	html_thumb = newhtml_thumb;
	    //         myThumbnailChange();
	    //     }
	    // },1000);
	    
        clearInterval(checking);
    }

    // function myThumbnailChange() {
    //     $('.catalog-product-view .fotorama').append(getPositionGalleryHtml('init'));
    //     clearInterval(checking);
    //     console.log('change thumbnail');
    // }

    $(document).on("click keyup keypress blur change swiperight swipeleft", ".catalog-product-view .fotorama", function () {
	    $('.catalog-product-view .fotorama .gallery-position').html(getPositionGalleryHtml('updated'));
	});

	function getPositionGalleryHtml(status){
    <?php if (($detectMobile->isMobile() != true && $detectMobile->isTablet() == false)
          || ($detectMobile->isMobile() == true && $detectMobile->isTablet() == true)) { ?>
      var div_thumb_detect = ".fotorama__nav__frame";
    <?php }else{ ?>
      var div_thumb_detect = ".fotorama__nav__frame.fotorama__nav__frame--dot";
    <?php } ?>
    var listItems = $(".catalog-product-view .fotorama__nav__shaft "+div_thumb_detect);

    var totalItems = listItems.length;

    if($('.catalog-product-view .fotorama__nav-wrap').css('display') != 'none'){
      if(totalItems == 0){totalItems = 1}
    }else{
      totalItems = 1;
    }
		
		var position = 1;
		listItems.each(function() {
			if(this.className.indexOf('fotorama__active') != -1){
			    return false;
			}else{
				position++;
			}
		});

		var html = '';
		var style = '';
		switch(status) {
			case 'init':
				if(totalItems == 1){
					style = 'style="margin-top:-50px;"';
				}
				html = '<div class="gallery-position" '+style+'>'+position+'/'+totalItems+'</div>';
			break;
			case 'updated':
				html = position+'/'+totalItems;
			break;
		}
		return html;
	}
});
</script>