<?php
/*------------------------------------------------------------------------
# SM Categories Menu - Version 1.0.0
# Copyright (c) 2016 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

$list = $this->_getList();
if (!empty($list)) { ?>
	<?php echo $list; ?>
	<?php
} ?>
