<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_InvisibleCaptcha
 */
?>
<?php
/**
 * Captcha block template
 *
 * @var \Amasty\InvisibleCaptcha\Block\Captcha $block
 * @var \Amasty\InvisibleCaptcha\Model\ConfigProvider $config
 */
$config = $block->getConfig();
?>
<script type="text/javascript">
    require(['jquery'], function ($) {
        var recaptcha = [],
            formsToProtect = '<?= $block->escapeJs(implode(',', $config->getAllFormSelectors())) ?>';

        window.formToProtectOnPage = [];
        $.each($(formsToProtect), function (index, formToProtect) {
            window.formToProtectOnPage.push(formToProtect);
        });

        if (window.formToProtectOnPage.length) {
            var recaptchaScript = document.createElement('script');
            recaptchaScript.src = 'https://www.google.com/recaptcha/api.js?onload=amInvisibleCaptchaOnloadCallback&render=explicit<?= $block->escapeHtml($config->getLanguage()); ?>';
            recaptchaScript.attributes = 'async defer';
            document.body.appendChild(recaptchaScript);
        }

        window.amInvisibleCaptchaOnloadCallback = function () {
            for (var i = 0; i < window.formToProtectOnPage.length; i++) {
                var tokenInput = document.createElement('input');
                tokenInput.type = 'hidden';
                tokenInput.name = 'amasty_invisible_token';
                window.formToProtectOnPage[i].appendChild(tokenInput);
            }

            var id = "<?= /* @noEscape */ $block->getData('id'); ?>";
            if (id) {
                var additionalForm = document.getElementById(id).form;
                if (additionalForm) {
                    window.formToProtectOnPage.push(additionalForm);
                }
            }

            var renderCaptcha = function(event, form, id) {
                recaptcha[i] = grecaptcha.render(id, {
                    'theme': '<?= $block->escapeHtml($config->getBadgeTheme()); ?>',
                    'badge': '<?= $block->escapeHtml($config->getBadgePosition()); ?>',
                    'sitekey': '<?= $block->escapeHtml($config->getSiteKey()); ?>',
                    'callback': function(token) {
                        if ($(form).valid()) {
                            form.querySelector("[name='amasty_invisible_token']").setAttribute('value', token);
                            $(form).submit();
                        }
                        for (var j = 0; j < recaptcha.length; j++) {
                            grecaptcha.reset(recaptcha[j]);
                        }
                    }
                });
            };

            for (var i = 0; i < window.formToProtectOnPage.length; i++) {
                var form = window.formToProtectOnPage[i];
                if (form.tagName.toLowerCase() != 'form') {
                    continue;
                }

                id = form.querySelector("[type='submit']");
                if (null == id) {
                    if (form.classList.contains('amform-form')) {
                        $(window).on(form.getAttribute('id'), renderCaptcha);
                    } else {
                        console.log(
                            'Amsty Google Invisible reCaptcha: can not protect form with id = '
                            + form.id
                            + ', please remove appropriate URL and Selector in the configuration of the extension.'
                        );
                    }
                    continue;
                }

                renderCaptcha(null, form, id);
            }
        };
    });
</script>
