<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Meta
 */

namespace Amasty\Meta\Controller\Adminhtml;

abstract class Custom extends \Amasty\Meta\Controller\Adminhtml\Config
{
    protected $_title = 'Meta Tags Template (Custom URLs)';
    protected $_isCustom = true;
    protected $_blockName = 'custom';

    protected function _isAllowed()
    {
        return $this->_authorization->isAllowed('Amasty_Meta::custom');
    }

    public function dispatch(\Magento\Framework\App\RequestInterface $request)
    {
        return parent::dispatch($request); // TODO: Change the autogenerated stub
    }


    public function execute()
    {
        return parent::execute();
    }

}
