<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$_config  = $this->helper('Sm\Market\Helper\Data');
$tabStyle = $_config->getProductDetail('tab_style');

$show_custom_tab   = $_config->getProductDetail('show_custom_tab');
$custom_tab_name   = $_config->getProductDetail('custom_tab_name');
$customtab_content = $_config->getProductDetail('customtab_content');
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')): ?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items accordion-style" data-mage-init='{"tabs":{"openedState":"active"}}'>

				<?php foreach ($detailedInfoGroup as $name): ?>
					<?php
					$html = $layout->renderElement($name);
					if (!trim($html)) {
						continue;
					}
					$alias = $layout->getElementAlias($name);
					$label = $block->getChildData($alias, 'title');
					?>
                    <h2 class="data item title resp-accordion"
                        aria-labeledby="tab-label-<?= /* @escapeNotVerified */
						$alias ?>-title"
                        data-role="collapsible" id="tab-label-<?= /* @escapeNotVerified */
					$alias ?>">
						<a class="data switch"
                           tabindex="-1"
                           data-toggle="switch"
                           href="#<?= /* @escapeNotVerified */
						   $alias ?>"
                           id="tab-label-<?= /* @escapeNotVerified */
						   $alias ?>-title">
							<?= /* @escapeNotVerified */
							$label ?>
						</a>
					</h2>

                    <div class="data item content resp-tab-content" id="<?= /* @escapeNotVerified */
					$alias ?>" data-role="content">
						<?= /* @escapeNotVerified */
						$html ?>
					</div>
				<?php endforeach; ?>
			<?php if ($show_custom_tab) { ?>
                <h2 id="tab-label-customtab" class="data item title resp-accordion" aria-labeledby="tab-label-customtab-title" data-role="collapsible" role="tab" data-collapsible="true" aria-controls="product.info.customtab" aria-selected="false" aria-expanded="true" tabindex="0">
						<a class="data switch"
                           tabindex="-1"
                           data-toggle="switch"
                           href="#<?= /* @escapeNotVerified */
						   $alias ?>"
                           id="tab-label-<?= /* @escapeNotVerified */
						   $alias ?>-title">
							<?php echo $custom_tab_name ?>
						</a>
					</h2>
                <div class="data item content resp-tab-content" id="customtab" data-role="content">
						<?php
						echo $customtab_content;
						?>
					</div>
			<?php } ?>
        </div>
    </div>
<?php endif; ?>
