<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
$signinPhoneNumberHelperData = $this->helper('Chottvn\SigninPhoneNumber\Helper\Data');
$loginKeyType = ($signinPhoneNumberHelperData->getSigninMode() == 1) ? "number" : "text";
$loginKeyLabel = ($signinPhoneNumberHelperData->getSigninMode() == 1) ? __('Phone Number') : __("Email or Phone");
$loginKeyPlaceholder = ($signinPhoneNumberHelperData->getSigninMode() == 1) ? __('Input Phone number') : __("Input Email or Phone");
?>
<div class="chottvn-ui-v2">
    <div class="block block-customer-login block-form">
        <div class="block-title">
            <h1><span id="block-customer-login-heading" role="heading" aria-level="2"><i class="fas fa-user"></i> <?= __('Sign In to chott') ?></span></h1>
        </div>
        <div class="block-content" aria-labelledby="block-customer-login-heading">
            <form class="form form-login" action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>" method="post" id="login-form" data-mage-init='{"validation":{}}'>
                <?= $block->getBlockHtml('formkey') ?>
                <!-- <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>"> -->
                <!-- <div class="field note"><?= $block->escapeHtml(__('If you have an account, sign in with your phone number.')) ?></div> -->
                <?php if ($signinPhoneNumberHelperData->isActive()) : ?>
                    <div class="field phone required">
                        <label class="label" for="phone"><span><?= /* @escapeNotVerified */ $loginKeyLabel //__("Email or Phone") 
                                    ?></span></label>
                        <div class="control">
                            <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off" <?php endif; ?> id="phone" type="tel" class="input-text" title="<?= $loginKeyLabel //__("Email or Phone")  //$block->getMode()->getTitle() 
                                                                                                                                                                                                                                                            ?>" placeholder="<?= $loginKeyPlaceholder ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-phone-VN': true}">
                        </div>
                    </div>
                <?php else : ?>
                    <div class="field email required">
                        <label class="label" for="email">
                            <span><?= $block->escapeHtml(__('Email')) ?></span>
                        </label>
                        <div class="control">
                            <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off" <?php endif; ?> id="email" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                        </div>
                    </div>
                <?php endif; ?>
                <div class="field password required">
                    <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control">
                        <input placeholder="<?= __('Input Password') ?>" name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off" <?php endif; ?> class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{'required-current-pass':true, required:true}">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <!-- <p><?=/* @escapeNotVerified */ __('*: Information required to enter') ?></p> -->
                <p class="remind-link"><a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= __('Forgot Password?') ?></span></a></p>
                <div class="actions-toolbar login-action">
                    <div class="primary"><button type="submit" class="action login primary button-submit-chott" name="send" id="send2"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button></div>
                </div>
                <p class="remind-text"><?= __('Have not account?') ?></p>
                <div class="actions-toolbar">
                    <div class="primary lightbox">
                        <a class="action create primary" href="/customer/account/create"><span><?= __('Create an Account') ?></span></a>
                    </div>
                </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>