<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Newsletter $block */
?>
<?= $block->getChildHtml('form_before') ?>
    <form class="form form-newsletter-manage" action="<?= $block->escapeUrl($block->getAction()) ?>" method="post" id="form-validate">
        <fieldset class="fieldset">
            <?= $block->getBlockHtml('formkey') ?>
            <legend class="legend"><span><?= $block->escapeHtml(__('Subscription option')) ?></span></legend><br>
            <div class="field choice">
                <input 
                    type="checkbox" 
                    name="is_subscribed" 
                    id="subscription" 
                    value="1" 
                    checked="checked"
                    class="checkbox css-checkbox">
                <label for="subscription" class="label">
                    <?php if ($block->getIsSubscribed()) : ?>
                        <span><?= $block->escapeHtml(__('You have subscribed to the newsletter from the Cho Truc Tuyen')) ?></span>
                    <?php else : ?>
                        <span><?= $block->escapeHtml(__('Please send me the newsletter of Cho Truc Tuyen')) ?></span>
                    <?php endif; ?>
                </label>
            </div>
            <?php /* Extensions placeholder */ ?>
            <?= $block->getChildHtml('customer.form.newsletter.extra') ?>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary"><button id="button-handle" type="submit" title="<?= $block->escapeHtmlAttr(__('Save')) ?>" class="action save primary"><span><?= $block->escapeHtml(__('Save')) ?></span></button></div>
            <div class="secondary" id="button-back"><a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a></div>
        </div>
    </form>
<?php /* Extensions placeholder */ ?>
<?= $block->getChildHtml('customer.form.newsletter.extra2') ?>
