<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper            = $this->helper('Magento\Catalog\Helper\Output');
$_config            = $this->helper('Sm\Market\Helper\Data');
$homeStyle          = $_config->getThemeLayout('home_style');
$productBrandHelper = $this->helper('Ves\Brand\Helper\ProductBrand');
$is_show_product_action_bar = 0;
?>
<?php if (!$_productCollection->count()): ?>
    <!-- <div class="message info empty"><div><?php /* @escapeNotVerified */
			echo __('We can\'t find products matching the selection.') ?></div></div> -->
<?php else: ?>
    <div class="toolbar-top">
    <?php echo $block->getToolbarHtml() ?>
	</div>
	<?php echo $block->getAdditionalHtml() ?>
	<?php
	if ($block->getMode() == 'grid') {
		$viewMode        = 'grid';
		$image           = 'category_page_grid';
		$showDescription = false;
		$templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
	} else {
		$viewMode        = 'list';
		$image           = 'category_page_list';
		$showDescription = true;
		$templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
	}
	/**
	 * Position for actions regarding image size changing in vde if needed
	 */
	$pos = $block->getPositioned();
	?>
    <div class="category-product products wrapper <?php /* @escapeNotVerified */
	echo $viewMode; ?> products-<?php /* @escapeNotVerified */
	echo $viewMode; ?>">
        <?php $iterator = 1; ?>

		<?php if ($viewMode == 'grid') { ?>

            <ol class="products list items product-items row">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
				<?php foreach ($_productCollection as $_product): ?>
                    <li class="item product product-item">
					<div class="product-item-info" data-container="product-grid">
						<div class="item-inner">
							<div class="box-image">
								<?php $productImage = $block->getImage($_product, $image); ?>

                                <!--LABEL PRODUCT-->

								<?php
								$orgprice             = $_product->getPrice();
								$specialprice         = $_product->getSpecialPrice();
								$specialPriceFromDate = $_product->getSpecialFromDate();
								$specialPriceToDate   = $_product->getSpecialToDate();

								$today = time();

								if ($specialprice && $_config->getAdvanced('show_salelabel')) {
									if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
										<?php if ($specialprice < $orgprice) {
											$save_percent = 100 - round(($specialprice / $orgprice) * 100);
											?>
                                            <div class="label-product label-sale">
											<span class="sale-product-icon">
												<?php echo '-' . $save_percent . '%'; ?>
											</span>
										</div>
										<?php } ?>
									<?php }
								}
								?>

								<?php

								$status_labels = isset($config['status_labels']) ? $config['status_labels'] : '[{"label_attribute":"best_seller","label_name":"Bán chạy","label_css":"best-seller"},{"label_attribute":"is_new_arrival","label_name":"Mới","label_css":"is-new-arrival"}]';
								$status_labels = json_decode($status_labels);
								$config = array();

								echo $this->getLayout()->createBlock("Sm\ListingTabs\Block\Ajax")->setData(['product' => $_product, 'config' => $config, 'status_labels' => $status_labels])->setTemplate("Sm_ListingTabs::status_labels.phtml")->toHtml();

								// $now      = date("Y-m-d");
								// $newsFrom = substr($_product->getNewsFromDate(), 0, 10);
								// $newsTo   = substr($_product->getNewsToDate(), 0, 10);
								// $now_year = date("Y");


								// if (($newsTo != '' || $newsFrom != '') && $_config->getAdvanced('show_newlabel')) {
								// 	if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) { 
								?>
	                                    <!-- <div class="label-product label-new">
												<span class="new-product-icon"><?php //echo __('New').' '.$now_year; ?></span>
											</div> -->
									<?php //}
								//} ?>


                                <!--END LABEL PRODUCT-->

								<a href="<?php /* @escapeNotVerified */
								echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
										<?php echo $productImage->toHtml(); ?>
								</a>

								<?php if ($homeStyle == 'home-16' || $homeStyle == 'home-17' || $homeStyle == 'home-18' || $homeStyle == 'home-19' || $homeStyle == 'home-20') { ?>
                                    <div class="button-action">
										<?php if ($_config->getAdvanced('show_wishlist_button')) { ?>
											<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                <a href="#" class="action towishlist btn-action link-wishlist" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */
												echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button">
													<span><?php /* @escapeNotVerified */
														echo __('Add to Wish List') ?></span>
												</a>
											<?php endif; ?>
										<?php } ?>

										<?php if ($_config->getAdvanced('show_compare_button')) { ?>
											<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                            <a href="#" class="action tocompare btn-action link-compare" title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" data-post='<?php /* @escapeNotVerified */
											echo $compareHelper->getPostDataParams($_product); ?>' role="button">
												<span><?php /* @escapeNotVerified */
													echo __('Add to Compare') ?></span>
											</a>
										<?php } ?>
									</div>
								<?php } ?>
							</div>

							<div class="product details product-item-details box-info">
								<?php
								$_productNameStripped = $block->stripTags($_product->getName(), null, true);
								?>
								<?php if($is_show_product_action_bar == 1){ ?>
                                <div class="product-action-bar">
									<?php
										// Show Brand
	                                    $productBrand = $productBrandHelper->getFirstBrandByProduct($_product);
	                                        if ($productBrand ){
	                                    ?>
	                                    <div class="brand-info">
	                                        <div class="brand-name">
	                                        	<a href="<?php echo $productBrand->getUrl(); ?>">
	                                        		<?php echo $productBrand->getName(); ?>
	                                        	</a>
	                                        </div>
	                                    </div>
	                                <?php } ?>

									<?php if ($homeStyle == 'home-16' || $homeStyle == 'home-17' || $homeStyle == 'home-18' || $homeStyle == 'home-19' || $homeStyle == 'home-20') { ?>
	                                    <div class="bottom-action">
											<?php if ($_config->getAdvanced('show_addtocart_button')) { ?>
												<?php if ($_product->isSaleable()): ?>
													<?php $postParams = $block->getAddToCartPostParams($_product); ?>
	                                                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
													echo $postParams['action']; ?>" method="post">
														<input type="hidden" name="product" value="<?php /* @escapeNotVerified */
														echo $postParams['data']['product']; ?>">
														<input type="hidden" name="<?php /* @escapeNotVerified */
														echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */
														echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
														<?php echo $block->getBlockHtml('formkey') ?>
	                                                    <button type="submit"
	                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
	                                                            class="action tocart primary btn-action btn-cart">
															<span><?php /* @escapeNotVerified */
																echo __('Add to Cart') ?></span>
														</button>
													</form>
												<?php else: ?>
													<?php if ($_product->getIsSalable()): ?>
	                                                    <div class="stock available"><span><?php /* @escapeNotVerified */
																echo __('In stock') ?></span></div>
													<?php else: ?>
	                                                    <div class="stock unavailable btn-action btn-cart"><span><?php /* @escapeNotVerified */
																echo __('Out of stock') ?></span></div>
													<?php endif; ?>
												<?php endif; ?>
											<?php } ?>
										</div>
									<?php } ?>

									<?php if ($homeStyle != 'home-16' && $homeStyle != 'home-17' && $homeStyle != 'home-18' && $homeStyle != 'home-19' && $homeStyle != 'home-20') { ?>
	                                    <div class="bottom-action">
											<?php if ($_config->getAdvanced('show_wishlist_button')) { ?>
												<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
	                                                <a href="#" class="action towishlist btn-action link-wishlist" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */
													echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button">
														<span><?php /* @escapeNotVerified */
															echo __('Add to Wish List') ?></span>
													</a>
												<?php endif; ?>
											<?php } ?>

											<?php if ($_config->getAdvanced('show_addtocart_button')) { ?>
												<?php if ($_product->isSaleable()): ?>
													<?php $postParams = $block->getAddToCartPostParams($_product); ?>
	                                                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
													echo $postParams['action']; ?>" method="post">
														<input type="hidden" name="product" value="<?php /* @escapeNotVerified */
														echo $postParams['data']['product']; ?>">
														<input type="hidden" name="<?php /* @escapeNotVerified */
														echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */
														echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
														<?php echo $block->getBlockHtml('formkey') ?>
	                                                    <button type="submit"
	                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
	                                                            class="action tocart primary btn-action btn-cart">
															<span><?php /* @escapeNotVerified */
																echo __('Add to Cart') ?></span>
														</button>
													</form>
												<?php else: ?>
													<?php if ($_product->getIsSalable()): ?>
	                                                    <div class="stock available"><span><?php /* @escapeNotVerified */
																echo __('In stock') ?></span></div>
													<?php else: ?>
	                                                    <div class="stock unavailable btn-action btn-cart"><span><?php /* @escapeNotVerified */
																echo __('Out of stock') ?></span></div>
													<?php endif; ?>
												<?php endif; ?>
											<?php } ?>

											<?php if ($_config->getAdvanced('show_compare_button')) { ?>
												<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
	                                            <a href="#" class="action tocompare btn-action link-compare" title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" data-post='<?php /* @escapeNotVerified */
												echo $compareHelper->getPostDataParams($_product); ?>' role="button">
													<span><?php /* @escapeNotVerified */
														echo __('Add to Compare') ?></span>
												</a>
											<?php } ?>
										</div>
									<?php } ?>
								</div>
								<?php } ?>

								<?php
									echo $this->getLayout()
										->createBlock('Chottvn\Frontend\Block\Rules')
										->setTemplate("Magento_Catalog::product/view/cartrules.phtml")
										->setData([
													'item_product' => $_product,
													'price_rules' => 'gift',
													'display_style' => 'icon',
													'rule_type' => 'ampromo_items',
													'css_class' => 'viewed-products-icon'
												])
										->toHtml();
								?>

								<?php
									// Hide Review Summary
									// echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>
								<h2 class="product name product-item-name product-name">
									<a class="product-item-link" href="<?php /* @escapeNotVerified */
									echo $_product->getProductUrl() ?>">
										<?php /* @escapeNotVerified */
										echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
									</a>
								</h2>
								<?php /* @escapeNotVerified */
								echo $block->getProductPrice($_product) ?>
								<?php echo $block->getProductDetailsHtml($_product); ?>

								<?php // Hide Review 
									echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>

								<?php
									// echo $this->getLayout()
									// ->createBlock('Chottvn\Frontend\Block\Rules')
									// ->setTemplate("Magento_Catalog::product/view/cartrules.phtml")
									// ->setData([
									// 			'item_product' => $_product,
									// 			'price_rules' => 'all',
									// 			'display_style' => 'icon',
									// 			'css_class' => 'viewed-products-icon'
									// 		])
									// ->toHtml();
								?>

							</div>
						</div>
					</div>
                </li>
				<?php endforeach; ?>
        </ol>

		<?php } else { ?>
            <ol class="products list items product-items">
				<?php foreach ($_productCollection as $_product): ?>
                    <li class="item respl-item-list product product-item">
						<div class="product-item-info" data-container="product-grid">
							<div class="item-inner">
								<div class="box-image-list">
									<?php $productImage = $block->getImage($_product, $image); ?>

                                    <!--LABEL PRODUCT-->

									<?php
									$specialprice         = $_product->getSpecialPrice();
									$specialPriceFromDate = $_product->getSpecialFromDate();
									$specialPriceToDate   = $_product->getSpecialToDate();

									$today = time();

									if ($specialprice && $_config->getAdvanced('show_salelabel')) {
										if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
                                            <div class="label-product label-sale">
														<span class="sale-product-icon">
															<?php echo __('Sale'); ?>
														</span>
													</div>
										<?php }
									}
									?>

									<?php
									$now      = date("Y-m-d");
									$newsFrom = substr($_product->getNewsFromDate(), 0, 10);
									$newsTo   = substr($_product->getNewsToDate(), 0, 10);


									if (($newsTo != '' || $newsFrom != '') && $_config->getAdvanced('show_newlabel')) {
										if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) { ?>
                                            <div class="label-product label-new">
														<span class="new-product-icon"><?php echo __('New'); ?></span>
													</div>
										<?php }
									} ?>


                                    <!--END LABEL PRODUCT-->

									<a href="<?php /* @escapeNotVerified */
									echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
											<?php echo $productImage->toHtml(); ?>
									</a>

								</div>

								<div class="product details product-item-details box-info-list">

									<?php
										echo $this->getLayout()
											->createBlock('Chottvn\Frontend\Block\Rules')
											->setTemplate("Magento_Catalog::product/view/cartrules.phtml")
											->setData([
														'item_product' => $_product,
														'price_rules' => 'gift',
														'display_style' => 'icon',
														'rule_type' => 'ampromo_items',
														'css_class' => 'viewed-products-icon'
													])
											->toHtml();
									?>

									
									<?php
									$_productNameStripped = $block->stripTags($_product->getName(), null, true);
									?>
                                    <h2 class="product name product-item-name product-name">
										<a class="product-item-link" href="<?php /* @escapeNotVerified */
										echo $_product->getProductUrl() ?>">
											<?php /* @escapeNotVerified */
											echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
										</a>
									</h2>

									<?php
										// Hide Reviews
									 	// echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                    <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                                    <?php echo $block->getProductDetailsHtml($_product); ?>

                                    <?php // Hide Review 
									echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>

                                    <div class="product-item-inner">
										<?php if ($showDescription): ?>
                                            <div class="product description product-item-description">
												<?php /* @escapeNotVerified */
												echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                                <a href="<?php /* @escapeNotVerified */
												echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */
												echo $_productNameStripped ?>"
                                                   class="action more"><?php /* @escapeNotVerified */
													echo __('Learn More') ?></a>
											</div>
										<?php endif; ?>
									</div>

									<?php if($is_show_product_action_bar == 1){ ?>
									<div class="product-action-bar">
										<?php
											// Show Brand
		                                    $productBrand = $productBrandHelper->getFirstBrandByProduct($_product);
		                                        if ($productBrand ){
		                                    ?>
		                                    <div class="brand-info">
		                                        <div class="brand-name">
		                                        	<a href="<?php echo $productBrand->getUrl(); ?>">
		                                        		<?php echo $productBrand->getName(); ?>
		                                        	</a>
		                                        </div>
		                                    </div>
		                                <?php } ?>
										<div class="bottom-action">
											<?php if ($_config->getAdvanced('show_addtocart_button')) { ?>
												<?php if ($_product->isSaleable()): ?>
													<?php $postParams = $block->getAddToCartPostParams($_product); ?>
	                                                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
													echo $postParams['action']; ?>" method="post">
														<input type="hidden" name="product" value="<?php /* @escapeNotVerified */
														echo $postParams['data']['product']; ?>">
														<input type="hidden" name="<?php /* @escapeNotVerified */
														echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */
														echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
														<?php echo $block->getBlockHtml('formkey') ?>
	                                                    <button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>" class="action tocart btn-action btn-cart">
															<span><?php /* @escapeNotVerified */
																echo __('Add to Cart') ?></span>
														</button>
													</form>
												<?php else: ?>
													<?php if ($_product->getIsSalable()): ?>
	                                                    <div class="stock available"><span><?php /* @escapeNotVerified */
																echo __('In stock') ?></span></div>
													<?php else: ?>
	                                                    <div class="stock unavailable btn-action btn-cart"><span><?php /* @escapeNotVerified */
																echo __('Out of stock') ?></span></div>
													<?php endif; ?>
												<?php endif; ?>
											<?php } ?>

	                                        <div class="add-to-links" data-role="add-to-links" class="actions-secondary">
												<?php if ($_config->getAdvanced('show_wishlist_button')) { ?>
													<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
	                                                    <a href="#" class="action towishlist btn-action link-wishlist" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */
														echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button">
															<span><?php /* @escapeNotVerified */
																echo __('Add to Wish List') ?></span>
														</a>
													<?php endif; ?>
												<?php } ?>

												<?php if ($_config->getAdvanced('show_compare_button')) { ?>
													<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
	                                                <a href="#" class="action tocompare btn-action link-compare" title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" data-post='<?php /* @escapeNotVerified */
													echo $compareHelper->getPostDataParams($_product); ?>' role="button">
														<span><?php /* @escapeNotVerified */
															echo __('Add to Compare') ?></span>
													</a>
												<?php } ?>
											</div>
										</div>
									</div>
									<?php } ?>
								</div>
							</div>
						</div>
					</li>
				<?php endforeach; ?>
			</ol>
		<?php } ?>
    </div>
    <div class="toolbar-bottom">
    <?php echo $block->getToolbarHtml() ?>
	</div>
	<?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
	<?php endif; ?>
<?php endif; ?>

<script type="text/javascript">
	// require([
 //        'jquery'
 //    ], function ($) {
 //    	$(window).load(function() {
	//         var rightmain_bg=$(".rightmain-bg").height();
	//         var sidebar_bg=$(".sidebar-bg").height();
	//         console.log("sidebar_bg:"+sidebar_bg); 
	//         console.log("rightmain_bg:"+rightmain_bg); 
	//         // Resize contain rightmain_bg & sidebar_bg
	//         if(rightmain_bg>sidebar_bg) {
	//         	$('.sidebar-bg').css('min-height', rightmain_bg+"px");
	//         	$('.rightmain-bg').css('min-height', rightmain_bg+"px");
	//         }
	//         else {
	//         	$('.rightmain-bg').css('min-height', sidebar_bg+"px");
	//         	$('.sidebar-bg').css('min-height', sidebar_bg+"px");
	//         }
 //        });

 //        var rightmain_bg_r=$(".rightmain-bg").height();
	//     var sidebar_bg_r=$(".sidebar-bg").height();
 //        // Catch resize rightmain_bg
 //        $('.rightmain-bg').attrchange({
	//         callback: function (e) {
	//             var curRHeight = $(this).height(); 
	//             console.log("curSHeight:"+curRHeight);           
	//             if (curRHeight > sidebar_bg_r) {
	//             	$('.sidebar-bg').css('min-height', curRHeight+"px");
 //        			$('.rightmain-bg').css('min-height', curRHeight+"px");
	//             }            
	//         }
	//     });
	//     // Catch resize rightmain_bg
 //        $('.sidebar-bg').attrchange({
	//         callback: function (e) {
	//             var curSHeight = $(this).height();  
	//             console.log("curSHeight:"+curSHeight);          
	//             if (curSHeight > rightmain_bg_r) {
	//             	$('.sidebar-bg').css('min-height', curSHeight+"px");
 //        			$('.rightmain-bg').css('min-height', curSHeight+"px");
	//             }            
	//         }
	//     });
 //    });
</script>