<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */
    $orderItem = $block->getItem();
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
    $saleRuleFactory = $objectManager->create('Magento\SalesRule\Model\ResourceModel\Rule\CollectionFactory');
    $reviewFactory = $objectManager->create('Magento\Review\Model\Review');
    // detect mobile
    $detectMobile = $objectManager->get('\Chottvn\Frontend\Helper\DetectMobile');
    $checkoutHelper = $objectManager->get('Chottvn\PriceDecimal\Helper\Data');
    $imageHelper = $this->helper('Magento\Catalog\Helper\Image');
    $storeId = $storeManager->getStore()->getId();
    $productBrandHelper = $this->helper('Ves\Brand\Helper\ProductBrand');
    $productRepository = $objectManager->get('\Magento\Catalog\Model\Product');
?>
    <?php
        $blockRules = $block->getLayout()->createBlock('Chottvn\Frontend\Block\Rules');
        $salesHelper = $this->helper('Chottvn\Sales\Helper\Data');
        $amPromoHelper = $this->helper('Amasty\Promo\Helper\Item');
        $product = $orderItem->getProduct();
        $productResource = $objectManager->create('Magento\Catalog\Model\Product')->load($product->getId());
        $guaranteeInfo = $orderItem->getData('guarantee');
        // đơn vị tính /cái
        $productunit = $productResource->getData('product_unit');
        $reviewFactory->getEntitySummary($productResource, $storeId);
        $ratingSummary = $productResource->getRatingSummary()->getRatingSummary();
        $ratingCount = $productResource->getRatingSummary()->getReviewsCount();
        $ruleIdsApplied = $orderItem->getAppliedRuleIds();
        // $rulesApplied = $saleRuleFactory->create()->addFieldToFilter('rule_id', array('in' => $ruleIdsApplied) )->addFieldToSelect('name');
        $productId = $orderItem->getProductId();
        $cartPromoItemids = $orderItem->getCartPromoItemIds();
        $orderId = $orderItem->getOrderId();
        $getQuoteItemId = $orderItem->getQuoteItemId();
        $rulesApplied = $salesHelper->getRulesNameByOrderCTT($getQuoteItemId,$orderId,$ruleIdsApplied);
        if ($childProd = current($orderItem->getChildrenItems())) {
            $productImage = $imageHelper->init($childProd->getProduct(), 'category_page_list')->getUrl();
        }
        else {
            $productImage = $imageHelper->init($orderItem->getProduct(), 'category_page_list')->getUrl();
        }
       
        // $isPromoItem = ($orderItem->getPrice() == 0);

        $quoteItem = $objectManager->create('Magento\Quote\Model\Quote\Item')->load($orderItem->getQuoteItemId());

        // $isPromoItem = $amPromoHelper->isPromoItem($quoteItem);
        $productOptions = $orderItem->getProductOptions();
        // $isPromoItem = $salesHelper->isPromoItem($productOptions);
        
        // cart promo option
        $cartPromoOption = $orderItem->getData('cart_promo_option');
        $isPromoItem = $salesHelper->isPromoItemCTT($cartPromoOption);

        $ruleId = $salesHelper->getRulesIdByProductOptions($productOptions);
        $nameRule = $salesHelper->getRulesNameByIdRule($ruleId);

        $messages_prefix = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('ampromo/messages/prefix');
        // options attributes
        $attributesOption = array();
        if(isset($orderItem->getProductOptions()["info_buyRequest"]["super_attribute"])){
            $attributesOption = $orderItem->getProductOptions()["info_buyRequest"]["super_attribute"];
        }
        $jacket = array();
        $productidOfconfigurable = $product->getId();
        if($attributesOption){
            $itemQuote = $objectManager->get('Magento\Quote\Model\ResourceModel\Quote\Item\CollectionFactory');
            $itemQuoteCollection = $itemQuote->create()->addFieldToFilter('parent_item_id',$orderItem->getQuoteItemId())->addFieldToFilter('product_type','simple');
            $lastItemQuote = $itemQuoteCollection->getLastItem();
            $productidOfconfigurable = $lastItemQuote->getData('product_id');
        
        }
        $productTypeInstance = $objectManager->get('Magento\Catalog\Model\ResourceModel\Eav\Attribute');
        if ($attributesOption) {
            foreach ($attributesOption as $key => $attr) {
                $_attr = $productTypeInstance->load($key);
                $attributeCode = $_attr->getAttributeCode();
                $jacket[$attributeCode] = $attr;
            }
        }
        
        $getProductUrl = $product->getProductUrl();
        if ($jacket) {
            $getProductUrl = $getProductUrl . '#';
            foreach($jacket as $key => $value){
                $getProductUrl = $getProductUrl .$key. '='. $value .'&';
            }
            $getProductUrl = substr($getProductUrl, 0, -1);
        }
        $productModel = $productResource->getData('model');
        if($productidOfconfigurable != $product->getId()){
            $productResourceConfiguration = $objectManager->create('Magento\Catalog\Model\Product')->load($productidOfconfigurable);
            if(!$productModel){
                $productModel = $productResourceConfiguration->getData('model');
            }
            $productImage = $imageHelper->init($productResourceConfiguration, 'product_page_image_thumbnail')->setImageFile($productResourceConfiguration->getImage())->getUrl();
        }else{
            $productImage = $imageHelper->init($product, 'product_page_image_thumbnail')->setImageFile($product->getImage())->getUrl();
        }

        if (isset($productImage) && !($salesHelper->url_exists($productImage))) {
            $productImage = $imageHelper->getDefaultPlaceholderUrl('thumbnail');
        }
        if (!isset($productImage)) {
            $productImage = $imageHelper->getDefaultPlaceholderUrl('thumbnail');
        }
    ?>
<style>
    .rules-list i{
        padding-right: 10px;
    }
</style>
    <div class="col-sm-8 item-body clearfix">
    <?php if ($detectMobile->isMobile() == true && $detectMobile->isTablet() == false) { ?>
        <!-- Mobile View -->
        <!-- name product -->
        <?php if(!$isPromoItem){ ?>
            <div class="product-item-details-mobile clearfix">
                <?php if ($product) :?>
                    <?php if ($salesHelper->hasProductUrl($product)) :?>
                        <a href="<?= $block->escapeUrl($getProductUrl) ?>" target="_blank" title="<?= $block->escapeHtml($orderItem->getName()) ?>">
                            <?= $orderItem->getProductNameLongHtml(); ?>
                        </a>
                    <?php else :?>
                        <?= $orderItem->getProductNameLongHtml(); ?>
                    <?php endif; ?>
                <?php else :?>
                    <?= $orderItem->getProductNameLongHtml(); ?>
                <?php endif; ?>
            </div>
        <?php } ?>
        <!-- Brand, Model -->
            <?php
                if($product){
                    $productBrand = $productBrandHelper->getFirstBrandByProduct($product);
                }else{
                    $productBrand = $productBrandHelper->getFirstBrandFromOrderItem($orderItem);
                }
                if ($productBrand || $productModel){
            ?>
            <div class="brand-model-mobile clearfix">
                <div class="brand-name">
                    <?php
                        if ($productBrand) {
                    ?>
                    <span><?php echo __('Brands: '); ?></span>
                    <span class="name"><?php echo $productBrand->getName(); ?></span>
                <?php } ?>
                </div>
                <div class="model-name">
                <?php
                    if ($productModel) {
                ?>
                    <span><?php echo __('Model: '); ?></span>
                    <span class="name"><?php echo $productModel; ?></span>
                <?php } ?>
                </div>
            </div>
        <?php } ?>
        <?php if (!$isPromoItem) { ?>
            <!-- Guarantee -->
            <?php if ($guaranteeInfo) { ?>
                <div class="guarantee-info">
                    <span><?php echo __('Guarantee: '); ?></span>
                    <span class="name"><?php echo $guaranteeInfo; ?></span>
                </div>
            <?php } ?>
            <!-- Options -->
            <?php if ($attributesOption) { ?>
                <div class="guarantee-info">
                    <?php foreach($attributesOption as $key => $value): ?>
                        <?php 
                            $productTypeInstance = $objectManager->get('Magento\ConfigurableProduct\Model\Product\Type\Configurable');
                            $productAttributeOptions = $productTypeInstance->getConfigurableAttributesAsArray($productResource);
                            $labelOptions = '';
                            $valueOptions = '';
                            foreach ($productAttributeOptions as $key_o => $value_o) {
                                $tmp_option = $value_o['values'];
                                if(count($tmp_option) > 0)
                                {   
                                    foreach ($tmp_option as $tmp) {
                                        if($key_o == $key && $tmp['value_index'] == $value){
                                            $labelOptions = $value_o['store_label'];
                                            $valueOptions = $tmp['label'];
                                            break;
                                        }
                                    }
                                }
                            }
                        ?>
                        <span class="span-options-right"><?php echo $labelOptions; ?>: <?php echo $valueOptions; ?></span>
                    <?php endforeach; ?>
                </div>
            <?php } ?>
        <?php } ?>
        <div class="product-item-photo mobile-view">
            <?php if ($product) :?>
                <?php if ($salesHelper->hasProductUrl($product) && $product) :?>
                    <a href="<?= $block->escapeUrl($getProductUrl) ?>" target="_blank" title="<?= $block->escapeHtml($orderItem->getName()) ?>">
                        <div class="img-box">
                            <img src="<?=$productImage?>" alt="<?= $block->escapeHtml($orderItem->getName()) ?>" />
                        </div>
                    </a>
                <?php else :?>
                    <div class="img-box">
                        <img src="<?=$productImage?>" alt="<?= $block->escapeHtml($orderItem->getName()) ?>" />
                    </div>
                <?php endif; ?>
            <?php else :?>
                <div class="img-box">
                    <img src="<?=$productImage?>" alt="<?= $block->escapeHtml($orderItem->getName()) ?>" />
                </div>
            <?php endif; ?>
        </div>
        <?php if (!$isPromoItem) { ?>
            <div class="product-item-info">
                <!-- Reviews -->
                <?php //if ($ratingSummary) :?>
                <div class="rating-summary" style="display: none;">
                        <div class="rating-result" title="<?= $block->escapeHtmlAttr($ratingSummary); ?>%">
                            <span style="width:<?= $block->escapeHtmlAttr($ratingSummary); ?>%">
                                <span>
                                    <span itemprop="ratingValue"><?= $block->escapeHtml($ratingSummary); ?></span>% of <span itemprop="bestRating">100</span>
                                </span>
                            </span>
                        </div>
                        <?= $block->escapeHtml($ratingCount) ?>&nbsp;<span><?php if ($ratingCount == 0) {
                            echo __("No review on product");
                        } else if ($ratingCount == 1) {
                            echo $block->escapeHtml(__('review turn'));
                        } else {
                            echo $block->escapeHtml(__('review turns'));
                        }
                        ?></span>
                    </div>
                <?php //endif;?>
                <!-- Product Price -->
                <div class="product-price product-price-mobile">
                    <?= $block->escapeHtml(__('Qty')) ?>:&nbsp;<span class="quantity"><?= (int) $orderItem->getQtyOrdered();  ?></span><?php if($productunit): ?> <?= $productunit;  ?><?php endif; ?></span>
                    <br/>
                    <?= $checkoutHelper->formatPrice($orderItem->getPrice());  ?><span class="price">
                    <?php
                        $priceOriginal = $orderItem->getOriginalPrice();
                        $priceFinal= $orderItem->getPrice();
                        if ($priceFinal < $priceOriginal) {
                            $savePercent = 100 - round(@($priceFinal / $priceOriginal ) * 100);
                        } else {
                            $savePercent = 0;
                        }
                        if ($savePercent != 0) {
                    ?>
                    <div class="order-save-price">
                        <span class="save-percent">-<?= $savePercent; ?>%</span>
                        <span class="price-original"><?= $checkoutHelper->formatPrice($priceOriginal); ?></span>
                    </div>
                    <?php } ?>
                </div>
                <!-- Sales Price -->
                <div class="sales-price sales-price-mobile">
                    <?= $block->escapeHtml(__('Subtotal')) ?>:
                    <?= $checkoutHelper->formatPrice($orderItem->getRowTotal());  ?>
                </div>
            </div>
        <?php }else{ ?>
                <div class="product-item-info">
                    <div class="rules-name-mobile">
                        <?= $nameRule ? '<strong>'.$nameRule.'</strong>': ''; ?>
                        <br>
                        <?php if ($salesHelper->hasProductUrl($product)) :?>
                            <a href="<?= $block->escapeUrl($getProductUrl) ?>" target="_blank" title="<?= $block->escapeHtml($orderItem->getName()) ?>">
                                <span><?= $orderItem->getData('product_name_short'); ?></span>
                            </a>
                        <?php else :?>
                            <span><?= $orderItem->getData('product_name_short'); ?></span>
                        <?php endif; ?>
                    </div>
                </div>
        <?php } ?>           
         <!-- Cart Rules -->
         <?php if (!$isPromoItem) { ?>
                <?php if ((!empty($rulesApplied)) && (count($rulesApplied) > 0)) { ?>
                    <div class="product-item-rule-mobile clearfix">
                        <div class="promotion-info">
                            <ul class="rules-list">
                                <?php foreach ($rulesApplied as $key => $rules) { ?>
                                    <?php if(count($rules['sku']) > 0){ ?>
                                        <?php foreach($rules['sku'] as $index => $sku){ ?>
                                            <?php 
                                                $productData = $productRepository->loadByAttribute('sku',$sku);
                                                if (!empty($productData)){
                                                    $productId = $productData->getId();
                                                    $nameproduct = $productData->getName();
                                                    $visibility = $salesHelper->hasProductUrl($productRepository->load($productId));
                                                    $urlProduct = $productData->getProductUrl();
                                                    $unitProduct = $rules['unit_product'][$index] ? ' '.$rules['unit_product'][$index]: '';
                                                    $qtyGift = $rules['qty'][$index] ? (int) $rules['qty'][$index] * (int) $orderItem->getQtyOrdered(): '';
                                                    $resultString = '('.$qtyGift.$unitProduct.')';
                                            ?>
                                            <li>
                                                <i class="fas fa-gift text-danger"></i><strong><?php echo __('Gift: '); ?></strong><span class="span-product"><?php echo $nameproduct; ?> <?php echo $resultString; ?> </span>
                                                <?php if($visibility){?>
                                                    <a class="see-more-rules" target="_blank" href= '<?php echo $urlProduct; ?>' title="<?= $nameproduct ?>">
                                                        <span class="span-load-more"><?= __('Load more details'); ?> &raquo;</span>
                                                    </a>
                                                <?php }?>
                                            </li>
                                <?php }}}} ?>
                            </ul>
                        </div>
                    </div>
                <?php } ?>
         <?php } ?>   
        <?php } else { ?>
        <!-- Desktop View -->
        <div class="product-item-photo">
            <div class="img-box">
                <?php if ($salesHelper->hasProductUrl($product)) :?>
                    <a href="<?= $block->escapeUrl($getProductUrl) ?>" target="_blank" title="<?= $block->escapeHtml($orderItem->getName()) ?>">
                        <div class="img-box">
                            <img src="<?=$productImage?>" alt="<?= $block->escapeHtml($orderItem->getName()) ?>" />
                        </div>
                    </a>
                <?php else :?>
                    <a title="<?= $block->escapeHtml($orderItem->getName()) ?>" target="_blank" tabindex="-1" class="product-item-photo">
                        <div class="img-box">
                            <img src="<?=$productImage?>" alt="<?= $block->escapeHtml($orderItem->getName()) ?>" />
                        </div>
                    </a>
                <?php endif; ?>
            </div>
        </div>
        <div class="product-item-info">
            <div class="product-item-details">
                <span class="product-item-name">
                    <?php if ($product) :?>
                            <?php if ($salesHelper->hasProductUrl($product)) :?>
                                <a href="<?= $block->escapeUrl($getProductUrl) ?>" target="_blank" title="<?= $block->escapeHtml($orderItem->getName()) ?>">
                                    <?php if($isPromoItem){ ?>
                                        <!-- Rule Name -->
                                        <?= $nameRule ? '<strong>'.$nameRule.'</strong>': ''; ?>
                                        <br><span><?= $orderItem->getData('product_name_short'); ?></span>
                                    <?php }else{ ?>
                                        <?= $orderItem->getProductNameLongHtml(); ?>
                                    <?php } ?>
                                </a>
                            <?php else :?>
                                    <?php if($isPromoItem){ ?>
                                        <!-- Rule Name -->
                                        <?= $nameRule ? '<strong>'.$nameRule.'</strong>': ''; ?>
                                        <br><span><?= $orderItem->getData('product_name_short'); ?></span>
                                    <?php }else{ ?>
                                        <?= $orderItem->getProductNameLongHtml(); ?>
                                    <?php } ?>
                            <?php endif; ?>
                        <?php else :?>
                            <?= $orderItem->getProductNameLongHtml(); ?>
                        <?php endif; ?>
                </span>
            </div>
            <!-- Brand, Model -->
            <div class="brand-model clearfix">
                <div class="brand-name">
                <?php
                    $productBrand = $productBrandHelper->getFirstBrandByProduct($product);
                    if ($productBrand ) {
                ?>
                    <span><?php echo __('Brands: '); ?></span>
                    <span class="name"><?php echo $productBrand->getName(); ?></span>
                <?php } ?>
                </div>
                <div class="model-name">
                <?php
                    if ($productModel) {
                ?>
                    <span><?php echo __('Model: '); ?></span>
                    <span class="name"><?php echo $productModel; ?></span>
                <?php } ?>
                </div>
            </div>
            <?php if (!$isPromoItem) { ?>
                <!-- Reviews -->
                <?php // if ($ratingSummary) :?>
                <div class="rating-summary" style="display: none;">
                        <div class="rating-result" title="<?= $block->escapeHtmlAttr($ratingSummary); ?>%">
                            <span style="width:<?= $block->escapeHtmlAttr($ratingSummary); ?>%">
                                <span>
                                    <span itemprop="ratingValue"><?= $block->escapeHtml($ratingSummary); ?></span>% of <span itemprop="bestRating">100</span>
                                </span>
                            </span>
                        </div>
                        <span class="rating-label">
                        <?php if ($ratingCount == 0) {
                        echo __('No review on product');
                        } else {
                        echo __('Have %1 reviews', $ratingCount);
                        }
                        ?>
                        </span>
                    </div>
                <?php //endif;?>
                <!-- Guarantee -->
                <?php if ($guaranteeInfo) { ?>
                    <div class="guarantee-info">
                        <span><?php echo __('Guarantee: '); ?></span>
                        <span class="name"><?php echo $guaranteeInfo; ?></span>
                    </div>
                <?php } ?>
                <!-- Options -->
                  <?php if ($attributesOption) { ?>
                    <div class="guarantee-info">
                        <?php foreach($attributesOption as $key => $value): ?>
                            <?php 
                                $productTypeInstance = $objectManager->get('Magento\ConfigurableProduct\Model\Product\Type\Configurable');
                                $productAttributeOptions = $productTypeInstance->getConfigurableAttributesAsArray($productResource);
                                $labelOptions = '';
                                $valueOptions = '';
                                foreach ($productAttributeOptions as $key_o => $value_o) {
                                    $tmp_option = $value_o['values'];
                                    if(count($tmp_option) > 0)
                                    {   
                                        foreach ($tmp_option as $tmp) {
                                            if($key_o == $key && $tmp['value_index'] == $value){
                                                $labelOptions = $value_o['store_label'];
                                                $valueOptions = $tmp['label'];
                                                break;
                                            }
                                        }
                                    }
                                }
                            ?>
                            <span class="span-options-right"><?php echo $labelOptions; ?>: <?php echo $valueOptions; ?></span>
                        <?php endforeach; ?>
                    </div>
                <?php } ?>
                <!-- Cart Rules -->
                <?php if (!$isPromoItem) { ?>
                    <?php if ((!empty($rulesApplied)) && (count($rulesApplied) > 0)) { ?>
                        <div class="promotion-info">
                            <ul class="rules-list">
                                <?php foreach ($rulesApplied as $key => $rules) { ?>
                                    <?php if(count($rules['sku']) > 0){ ?>
                                        <?php foreach($rules['sku'] as $index => $sku){ ?>
                                            <?php 
                                                $productData = $productRepository->loadByAttribute('sku',$sku);
                                                if (!empty($productData)){
                                                    $productId = $productData->getId();
                                                    $nameproduct = $productData->getName();
                                                    $visibility = $salesHelper->hasProductUrl($productRepository->load($productId));
                                                    $urlProduct = $productData->getProductUrl();
                                                    $unitProduct = $rules['unit_product'][$index] ? ' '.$rules['unit_product'][$index]: '';
                                                    $qtyGift = $rules['qty'][$index] ? (int) $rules['qty'][$index] * (int) $orderItem->getQtyOrdered(): '';
                                                    $resultString = '('.$qtyGift.$unitProduct.')';
                                            ?>
                                        
                                            <li>
                                                <i class="fas fa-gift text-danger"></i><strong><?php echo __('Gift: '); ?></strong><span class="span-product"><?php echo $nameproduct; ?> <?php echo $resultString; ?> </span>
                                                <?php if($visibility){?>
                                                    <a class="see-more-rules" target="_blank" href= '<?php echo $urlProduct; ?>' title="<?= $nameproduct ?>">
                                                        <span class="span-load-more"><?= __('Load more details'); ?> &raquo;</span>
                                                    </a>
                                                <?php }?>
                                            </li>
                                <?php }}}} ?>
                            </ul>
                        </div>
                    <?php } ?>
                <?php } ?>
              
            <?php } ?>
        </div>
    <?php } ?>
    </div>
    <div class="col-sm-2 hidden-xs item-body p-l-r">
        <?php if (!$isPromoItem) { ?>
            <div class="product-price">
                <!-- <span class="d-inline-block d-sm-none" >
                        <?= $block->escapeHtml(__('Qty')) ?>:&nbsp;
                        </span> -->
                        <span class="quantity"><?= (int) $orderItem->getQtyOrdered();  ?></span><?php if($productunit): ?> <?= $productunit;  ?><?php endif; ?></span>
                        <br/>
                        <?= $checkoutHelper->formatPrice($orderItem->getPrice());  ?><span class="price">
                        <?php
                            $priceOriginal = $orderItem->getOriginalPrice();
                            $priceFinal= $orderItem->getPrice();
                            if ($priceFinal < $priceOriginal) {
                                $savePercent = 100 - round(@($priceFinal / $priceOriginal ) * 100);
                            } else {
                                $savePercent = 0;
                            }
                            if ($savePercent != 0) {
                        ?>
                        <div class="order-save-price">
                            <span class="save-percent">-<?= $savePercent; ?>%</span>
                            <span class="price-original"><?= $checkoutHelper->formatPrice($priceOriginal); ?></span>
                        </div>
                    <?php } ?>
            </div>
        <?php } ?>
    </div>
    <div class="col-sm-2 hidden-xs text-right item-body">
        <?php if (!$isPromoItem) { ?>
            <div class="sales-price">
                <span class="d-inline-block d-sm-none">
                    <?= $block->escapeHtml(__('Subtotal')) ?>:&nbsp;
                </span>
                <?= $checkoutHelper->formatPrice($orderItem->getRowTotal());  ?>
            </div>
        <?php } ?>
    </div>
