<?php
/**
 * Copyright © Tuan Nguyen, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Mageplaza\Blog\Block\Post\View */
$helper = $this->helper(\Mageplaza\Blog\Helper\Data::class);
$_post = $block->getPost();

$title = $_post->getName();
$url = $_post->getUrl();
$shortDescription = $_post->getShortDescription();
$image = $_post->getImage() ? $block->getImageUrl($_post->getImage()) : $block->getDefaultImageUrl();
$published_time = $block->getDateFormat($_post->getPublishDate());
$author = $helper->getAuthorByPost($_post);
$authorName = $author !== null ? $author->getName() : '';
?>
<meta property="og:type" content="article">
<meta property="og:title" content="<?php echo $title; ?>">
<meta property="og:url" content="<?php echo $url; ?>">
<meta property="og:description" content="<?php echo $shortDescription; ?>" />
<meta property="og:image" content="<?php echo $image; ?>">
<meta property="article:published_time" content="<?php echo $published_time; ?>">
<meta property="article:author" content="<?php echo $authorName; ?>">