
<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $priceHelper = $objectManager->get('Chottvn\PriceDecimal\Helper\Data');
    $withdrawalRewardAmountMin = (int) $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('configuration/general/withdrawal_reward_amount_min');
?>
<div class="col-sm-12 order-timeline">
    <div class="row order-progress" >
        <div class="col-sm-4 col-4 order-progress-step complete">
            <div class="text-center order-progress-stepnum">&nbsp;</div>
            <div class="progress"><div class="progress-bar"></div></div>
            <a href="#" class="order-progress-dot"></a>
            <div class="order-progress-info">
                <!-- <img class="order-steps-icon" src="<?= $this->getUrlImage('images/icon-order-step-1.png');  ?>" alt=""/> -->
                <p class="order-steps-label" ><?= __('Step initialization'); ?></p>
            </div>
        </div>
        <div class="col-sm-4 col-4 order-progress-step active">
            <div class="text-center order-progress-stepnum">&nbsp;</div>
            <div class="progress"><div class="progress-bar"></div></div>
            <a href="#" class="order-progress-dot"></a>
            <div class="order-progress-info">
            <!-- <img class="order-steps-icon" src="<?= $this->getUrlImage('images/icon-order-step-2.png');  ?>" alt=""/> -->
                <p class="order-steps-label" ><?= __('Step confirm'); ?></p>
            </div>
        </div>
        <div class="col-sm-4 col-4 order-progress-step disabled">
            <div class="text-center order-progress-stepnum">&nbsp;</div>
            <div class="progress"><div class="progress-bar"></div></div>
            <a href="#" class="order-progress-dot"></a>
            <div class="order-progress-info">
                <!-- <img class="order-steps-icon" src="<?= $this->getUrlImage('images/icon-order-step-3.png');  ?>" alt=""/> -->
                <p class="order-steps-label" ><?= __('Step result'); ?></p>
            </div>
        </div>
    </div>
</div><!-- /.order-progress -->
<div class="chottvn-ui-form">
    <div class="block block-send-otp block-form">
        <!-- <div class="block-title">
            <h1><span id="block-customer-login-heading" role="heading" aria-level="2"><i class="fas fa-user"></i> <?= __('Your account') ?></span></h1>
        </div> -->
        <div class="block-content" aria-labelledby="block-customer-login-heading">
            <p class="request-amount"><?= __('Request amount'); ?>: <?= /* @escapeNotVerified */ $priceHelper->formatPrice($block->getAmount()) ?></p>
            <form class="form form-login" action="<?= $block->escapeUrl($block->getPostVerifyPhoneNumber()) ?>" method="post" id="login-form" data-mage-init='{"validation":{}}'>
                    <input name="phone_number" type="hidden" id="phone_number" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" data-validate="{required:true}" value="<?= $block->getVerifyingPhone() ?>">
                    <input name="rate" type="hidden" id="rate" value="<?= $block->getRate() ?>">
                    <input name="amount" type="hidden" id="amount"value="<?= $block->getAmount() ?>">
                    <input name="transaction_type_id" type="hidden" id="transaction_type_id" value="<?= $block->getTransactionTypeId() ?>">
                    <input name="request_id" type="hidden" id="request_id" value="<?= $block->getRequest() ?>">
                    <input name="accountamountavailable" type="hidden" id="accountamountavailable" value="<?= $block->getAccountAmountAvailable() ?>">
                    <input name="withdrawalrewardamountmin" type="hidden" id="withdrawalrewardamountmin" value="<?= $withdrawalRewardAmountMin; ?>">
                <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                    <div class="field note">
                        <label class="label send-announcement" for="auth_code" style="display: none;"><span><?= $block->escapeHtml(__('Please enter the verification code we just sent to your phone number %1', $block->getVerifyingPhone())) ?></span></label>
                        <label class="label resend-announcement" for="auth_code" style="display: none;"><span><?= $block->escapeHtml(__('Please input OTP code we have just sent to your phone number', $block->getVerifyingPhone())) ?></span></label>
                    </div>
                    <!-- <div class="field required">
                        <label for="phone_number" class="label"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
                        <div class="control">
                            <input name="phone_number" type="tel" id="phone_number" class="input-text" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-phone-VN': true}" value="<?= $block->getVerifyingPhone() ?>">
                        </div>
                    </div> -->
                    <div class="field required">
                        <label for="auth_code" class="label"><span><?= $block->escapeHtml(__('Authenticate Code')) ?></span></label>
                        <div class="control">
                            <input name="auth_code" type="text" class="input-text" id="auth_code" placeholder="<?= $block->escapeHtmlAttr(__('Input Authenticate Code')) ?>" title="<?= $block->escapeHtmlAttr(__('Authenticate Code')) ?>" data-validate="{required:true}">
                        </div>
                    </div>
                    <!-- <div class="resend-section">
                        <a class="resend" href="javascript:;" id="send_otp" style="display: none;">
                            <div class="resend-icon">
                                <i class="fas fa-paper-plane"></i>
                            </div>
                            <span class="resend-text"><?= $block->escapeHtml(__('Send Authenticate Code')) ?></span>
                        </a>
                        <a class="resend" href="javascript:;" id="resend_otp" style="display: none;">
                            <div class="resend-icon">
                                <i class="fas fa-redo"></i>
                            </div>
                            <span class="resend-text"><?= $block->escapeHtml(__('Send Authenticate Code')) ?></span>
                        </a>
                        <div class="resend" id="count_down" style="display: none;">
                            <div class="resend-icon">
                            </div>
                            <span class="resend-text"><?= $block->escapeHtml(__('Send Authenticate Code')) ?></span>
                        </div>
                    </div> -->
                    <?= $block->getChildHtml('form_additional_info') ?>
                    <div class="actions-toolbar">
                        <div class="primary">
                            <button type="submit" class="action login primary" name="send" id="send">
                                <span><?= $block->escapeHtml(__('Complete Withdrawal')) ?></span>
                            </button>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>

<script>
    require([
        'Magento_Ui/js/modal/alert',
        'jquery'
    ], function(alert, $) {
        var sendOTPUrl = window.location.origin + "<?= $block->getAPISendOTPByPhone(); ?>";
        var timeToResendOTP = <?= $block->getTimeToResendOTP(); ?>;
        var effectiveTime = <?= $block->getEffectiveTime(); ?>;

        function intervalManager(flag, func, time) {
            if (flag) {
                var x = setInterval(func, time);
            } else {
                clearInterval(x);
            }
        }

        function countDown() {
            timeToResendOTP -= 1;
            displayCountDown(timeToResendOTP);
            if (timeToResendOTP <= 0) {
                intervalManager(false);
                hideCountDown();
                $("#resend_otp").show();
            }
        }

        function hideCountDown() {
            $(".resend-announcement").hide();
            $(".send-announcement").show();
            $("#count_down").hide();
        }

        function showCountDown() {
            $(".resend-announcement").show();
            $(".send-announcement").hide();
            $("#resend_otp").hide();
            $("#send_otp").hide();
            $("#count_down").show();
        }

        function displayCountDown(secs) {
            let min = Math.floor(secs / 60);
            let sec = secs % 60;
            let display_sec = (sec < 10) ? "0" + sec : sec;
            let time = min + ":" + display_sec;
            $("#count_down .resend-icon").html(time);
        }

        function sendOTP() {
            timeToResendOTP = effectiveTime;

            $.ajax({
                url: sendOTPUrl,
                type: "post",
                contentType: "application/json",
                dataType: "json",
                showLoader: true,
                data: JSON.stringify({
                    phoneNumber: $('#phone_number').val()
                }),
                success: function(result) {
                    let rs = JSON.parse(result);

                    let priority = 'danger';
                    if (rs.status) {
                        priority = 'info';
                        showCountDown();
                        intervalManager(true, countDown, 1000);
                    }

                    $.toaster({
                        priority: priority,
                        message: rs.message
                    });
                }
            });
        }

        $(document).ready(function() {
            if (timeToResendOTP > 0) {
                intervalManager(true, countDown, 1000);
                showCountDown();
            } else {
                hideCountDown();
                $("#send_otp").show();
            }
        });

        $('#resend_otp').click(function() {
            sendOTP();
        });

        $('#send_otp').click(function() {
            sendOTP();
        });
    });
</script>