
<?php
    // Get arguments from block
    $viewAllUrl = $this->getData('view_all_url') ?? "";
    $title = $block->getData("title");
    $list_brand = $block->getBrandCollection();
    $url_main = $block->getUrl();
?>
<?php if ($list_brand->getSize() > 0): ?>
   <div class="sm-listing-tabs slidertype">
    <div class="ltabs-head">
            <div class="title-home-page"><span><?php echo $title; ?></span></div>
            <?php
                if (! empty($viewAllUrl) ) {
            ?>
                <div class="ltabs-view-all">
                    <a href="<?php echo $viewAllUrl; ?>"><span class=""><?php echo __('All') ?></span> <i class="fas fa-chevron-right"></i><i class="fas fa-chevron-right"></i></a>
                </div>
            <?php } ?>
        </div>
        <div class="ltabs-wrap post-related">
            <div class="grid products-grid">
                <div id="owl-list-brand" class="owl-carousel owl-theme">
                    <?php foreach ($list_brand as $_brand) :?>
                        <div class= "item">
                            <div class= "prod-box-item">
                                <div class="item-inner">
                                    <div class= "box-image-brand">
                                        <div class="brand-image"><a href="<?php echo $_brand->getUrl(); ?>" title="<?php echo $_brand->getName(); ?>"><img src="<?php echo $_brand->getThumbnailUrl(); ?>" alt="<?php echo $_brand->getName(); ?>"/></a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
   </div>
<?php endif; ?>
<script type="text/javascript" xml="space">
    require([
        'jquery',
        'owlcarousel'
    ], function($){
        $(document).ready(function() {
            var owl = $('#owl-list-brand');
            $('#owl-list-brand').owlCarousel({
            loop: false,
            items: 6, // Select Item Number
            autoplay: false,
            dots: false,
            nav: true,
            slideSpeed : 500,
            paginationSpeed : 800,
            rewindSpeed : 1000,
            autoplayHoverPause: true,
            responsiveClass:true,
            responsive:{
                0:{
                    items:2,
                    nav:true
                },
                500:{
                    items:2,
                    nav:true
                },
                800:{
                    items:3,
                    nav:true
                },
                1000:{
                    items:6,
                    nav:true,
                    loop:false
                }
            }
            });
          
        });
    });
</script>